Repository platformsh/platformsh-docs, pull requests merged in 2021-12, with the labels that each got.

#2023 :memo: Updated PostgreSQL dedicated versions
  docs/data/registry.json
  docs/src/configuration/services/postgresql.md
Labels: Quick task

#2022 :memo: Update Underscorejs version listed
  docs/src/integrations/activity/_index.md
Labels: Upcoming version, Quick task

#2034 :sparkles: Update PHP extensions for 8.1
  docs/src/languages/php/extensions.md
Labels: Quick task

#2038 :lock: Note lack of PCI compliance on DG3
  docs/src/dedicated-gen-3/overview.md
Labels: Quick task

#2044 :bug: Limit region table CSS to that table
  docs/static/styles/user-customizations.css
Labels: Quick task

#2045 :memo: Replace Bitbucket instructions with link
  docs/src/integrations/source/bitbucket.md
  docs/static/images/integrations/bitbucket_server.png
Labels: Quick task

#2048 :lipstick: Make ToC sticky on right
  docs/themes/avocadocs/layouts/_default/list.html
  docs/themes/avocadocs/layouts/_default/single.html
  docs/themes/avocadocs/static/styles/customizations.css
Labels: Website

#1998 :zap: Improve search experience
  README.md
  docs/layouts/_default/search.html
  docs/layouts/partials/meilindex/page.html
  docs/src/search.md
  docs/static/files/fetch/examples/relationships/elasticsearch
  docs/static/files/fetch/examples/relationships/influxdb
  docs/static/files/fetch/examples/relationships/kafka
  docs/static/files/fetch/examples/relationships/memcached
  docs/static/files/fetch/examples/relationships/mongodb
  docs/static/files/fetch/examples/relationships/mysql
  docs/static/files/fetch/examples/relationships/postgresql
  docs/static/files/fetch/examples/relationships/rabbitmq
  docs/static/files/fetch/examples/relationships/redis
  docs/static/files/fetch/examples/relationships/solr
  docs/static/files/fetch/examples/relationships/vault-kms
  docs/static/scripts/xss/.gitignore
  docs/static/scripts/xss/dist/config/.gitignore
  docs/static/scripts/xss/package-lock.json
  docs/static/scripts/xss/package.json
  docs/static/scripts/xss/src/App.js
  docs/static/scripts/xss/src/components/SuggestionsPrimary.js
  docs/static/scripts/xss/src/containers/Search.js
  docs/static/scripts/xss/src/index.js
  docs/static/scripts/xss/src/styles/searchbox.css
  docs/static/scripts/xss/webpack.dev.js
  docs/themes/avocadocs/static/styles/search.css
  search/.platform.app.yaml
  search/main.py
Labels: Website

#2009 :memo: New build and deploy page
  docs/src/overview/build-deploy.md
  docs/static/images/workflow/build-pipeline.svg
  styles/Vocab/Platform/accept.txt
Labels: Docs Rework

#2050 :memo: Update supported elasticsearch versions
  docs/data/registry.json
Labels: Quick task

#2062 :memo: Warn that custom domains override generated
  docs/src/domains/quick-start.md
Labels: Quick task

#2064 :memo: Clarify Let's Encrypt limits per env
  docs/src/configuration/routes/https.md
Labels: Quick task

#2063 :bricks: Make redirects go to specific headings
  .platform/routes.yaml
Labels: Quick task

#2057 :memo: Updating troubleshooting for git push out of disk issue
  docs/src/development/troubleshoot.md
Labels: Quick task

#2065 :bug: Fix CLI command
  .vale.ini
  docs/config/_default/config.yaml
  docs/layouts/shortcodes/guides/signup.html
  docs/layouts/shortcodes/guides/signup.md
  docs/layouts/shortcodes/guides/tools.html
  docs/layouts/shortcodes/guides/tools.md
  docs/src/guides/drupal9/deploy/_index.md
  docs/src/guides/gatsby/deploy/_index.md
  docs/src/guides/gatsby/headless/_index.md
  docs/src/guides/micronaut/deploy/_index.md
  docs/src/guides/quarkus/deploy/_index.md
  docs/src/guides/spring/deploy/_index.md
  docs/src/guides/typo3/deploy/_index.md
  docs/src/guides/wordpress/deploy/_index.md
  docs/src/guides/wordpress/vanilla/_index.md
Labels: Quick task
