Repository platformsh/platformsh-docs, pull requests merged in 2022-02, with the labels that each got.

#2116 :bug: Fix link to specific section
  docs/src/development/transfer-dedicated.md
Labels: Quick task

#2120 :bug: Exclude registry pages from search index
  docs/layouts/_default/index.json.json
Labels: Website

#2113 :memo: Clarify the need to restart PHP-FPM
  docs/src/languages/php/tuning.md
Labels: Quick task

#2088 :memo: Added additional PHP extensions for 8.x
  docs/src/languages/php/extensions.md
Labels: Upcoming version

#2112 :memo: Update SCA docs for time having passed
  docs/src/security/sca.md
  docs/static/images/sca/authenticate-payment.png
  docs/static/images/sca/sca-warning.png
Labels: Quick task

#2117 :memo: Clarify restriction on root location
  docs/src/configuration/app/app-reference.md
Labels: Quick task

#2070 :memo: Improve variables docs
  .platform/routes.yaml
  .vale.ini
  docs/.hugo_build.lock
  docs/layouts/shortcodes/guides/config-reader-info.html
  docs/layouts/shortcodes/guides/config-reader-nodejs.html
  docs/layouts/shortcodes/guides/config-reader-php.html
  docs/src/administration/users.md
  docs/src/administration/web/configure-environment.md
  docs/src/bestpractices/environment-build.md
  docs/src/configuration/app/app-reference.md
  docs/src/configuration/app/hooks.md
  docs/src/configuration/app/source-operations.md
  docs/src/configuration/app/troubleshoot-disks.md
  docs/src/configuration/routes/https.md
  docs/src/configuration/services/elasticsearch.md
  docs/src/configuration/services/headless-chrome.md
  docs/src/configuration/services/influxdb.md
  docs/src/configuration/services/kafka.md
  docs/src/configuration/services/memcached.md
  docs/src/configuration/services/mongodb.md
  docs/src/configuration/services/mysql/_index.md
  docs/src/configuration/services/opensearch.md
  docs/src/configuration/services/postgresql.md
  docs/src/configuration/services/rabbitmq.md
  docs/src/configuration/services/redis.md
  docs/src/configuration/services/solr.md
  docs/src/configuration/services/vault.md
  docs/src/dedicated/architecture/options.md
  docs/src/development/cli/api-tokens.md
  docs/src/development/email.md
  docs/src/development/troubleshoot.md
  docs/src/development/variables.md
  docs/src/development/variables/_index.md
  docs/src/development/variables/set-variables.md
  docs/src/development/variables/use-variables.md
  docs/src/domains/quick-start.md
  docs/src/frameworks/drupal7/faq.md
  docs/src/frameworks/drupal7/memcached.md
  docs/src/frameworks/ibexa/_index.md
  docs/src/gettingstarted/introduction/own-code/app-configuration.md
  docs/src/guides/general/composer-auth.md
  docs/src/guides/wordpress/redis.md
  docs/src/guides/wordpress/vanilla/customize.md
  docs/src/integrations/activity/_index.md
  docs/src/integrations/activity/discord.md
  docs/src/integrations/activity/slack.md
  docs/src/integrations/observability/blackfire.md
  docs/src/languages/elixir.md
  docs/src/languages/go.md
  docs/src/languages/java/migration.md
  docs/src/languages/lisp.md
  docs/src/languages/nodejs/node-version.md
  docs/src/languages/php/ini.md
  docs/src/other/changelog.md
  docs/static/images/management-console/variables-overridden.png
  docs/templates/service-reference.md
  styles/Platform/abbreviations.yml
  styles/Platform/contractions.yml
Labels: Docs Rework

#2164 :memo: Document agreed on standards
  contributing/content-style.md
  contributing/markup-format.md
  docs/src/development/logs.md
  docs/static/styles/user-customizations.css
Labels: Website

#2094 :memo: Change hooks docs into a tutorial
  docs/src/configuration/app/_index.md
  docs/src/configuration/app/app-reference.md
  docs/src/configuration/app/hooks.md
  docs/src/configuration/app/hooks/_index.md
  docs/src/configuration/app/hooks/hooks-and-dependencies.md
  docs/src/configuration/app/hooks/hooks-comparison.md
  docs/src/configuration/app/hooks/vary-hooks-by-environment.md
  docs/src/configuration/app/workers.md
  docs/src/development/logs.md
  docs/src/development/sanitize-db.md
  docs/src/development/troubleshoot.md
  docs/src/development/variables/use-variables.md
  docs/src/gettingstarted/introduction/own-code/app-configuration.md
  docs/src/guides/micronaut/deploy/customize.md
  docs/src/integrations/observability/new-relic/_index.md
  docs/src/languages/java/migration.md
  docs/src/languages/nodejs/node-version.md
  docs/src/languages/php/frameworks.md
  docs/src/languages/php/tuning.md
  docs/src/other/changelog.md
  docs/src/overview/build-deploy.md
  docs/static/styles/user-customizations.css
  styles/Vocab/Platform/accept.txt
Labels: Docs Rework

#2184 :fire: Remove dates from third-party resources
  docs/src/tutorials/third-party.md
Labels: Quick task

#2207 :memo: Add section on command not found
  docs/src/development/troubleshoot.md
Labels: Quick task

#2206 :memo: Clarify PORT and SOCKET variables
  docs/src/configuration/app/app-reference.md
  docs/src/development/troubleshoot.md
  docs/src/development/variables/use-variables.md
Labels: generalization
