Repository platformsh/platformsh-docs, pull requests merged in 2022-03, with the labels that each got.

#2210 :memo: Update availability wording
  docs/layouts/partials/tiered-features/body.html
Labels: Quick task

#2208 :memo: Generalize examples
  docs/src/configuration/app/_index.md
  docs/src/configuration/app/app-reference.md
  docs/src/configuration/app/hooks/hooks-comparison.md
  docs/src/configuration/app/multi-app.md
  docs/src/configuration/app/source-operations.md
  docs/src/configuration/routes/ssi.md
  docs/src/configuration/services/network-storage.md
  docs/src/configuration/services/redis.md
  docs/src/dedicated/architecture/options.md
  docs/src/development/local/_index.md
Labels: generalization

#2096 ✨ Document Organization creation and deletion
  docs/src/administration/organizations.md
  docs/static/styles/user-customizations.css
  docs/themes/avocadocs/layouts/shortcodes/codetabs.html
  docs/themes/avocadocs/static/styles/customizations.css
Labels: Upcoming version

#2233 :bug: Fix broken links
  docs/src/configuration/services/redis.md
  docs/src/guides/gatsby/headless/strapi.md
  docs/src/integrations/observability/new-relic/php.md
  docs/src/tutorials/third-party.md
Labels: Quick task

#2239 :memo: Note the need for support in cron job time
  docs/src/configuration/app/app-reference.md
Labels: Quick task

#2241 :bug: Fix broken link
  docs/src/guides/strapi/adding-frontends/gatsby.md
Labels: quick task

#2246 :bug: Fix broken link
  docs/src/guides/strapi/adding-frontends/gatsby.md
Labels: quick task

#2252 :memo: Clarify that workers don't run cron jobs
  docs/src/configuration/app/app-reference.md
  docs/src/configuration/app/workers.md
Labels: quick task
