Repository platformsh/platformsh-docs, pull requests merged in 2022-06, with the labels that each got.

#2407 🚚 Rename create apps
  docs/src/create-apps/_index.md
Labels: quick task

#2406 📝 Clarify service versions
  docs/src/add-services/_index.md
Labels: quick task

#2408 📝 Edit metrics timeframe for Dedicated
  docs/src/increase-observability/metrics/_index.md
Labels: upcoming version, quick task

#2411 ➖ Remove unnecessary deprecated dependency
  docs/config/_default/params.yaml
  docs/static/scripts/xss/package-lock.json
  docs/static/scripts/xss/package.json
  docs/static/scripts/xss/src/components/Suggestions.js
  search/poetry.lock
  search/pyproject.toml
Labels: website

#2414 📝 Note Xdebug is app only
  docs/src/languages/php/xdebug.md
Labels: quick task

#2362 :memo: Improve clarity of database backup on dedicated
  docs/src/dedicated/overview/grid.md
  docs/src/development/transfer-dedicated.md
Labels: quick task

#2424 📝 Update supported images
  docs/data/registry.json
  docs/src/other/changelog.md
Labels: quick task

#2425 ✨ Add a form to collect feedback
  .platform/services.yaml
  docs/.platform.app.yaml
  docs/404.js
  docs/config/_default/config.yaml
  docs/config/_default/params.yaml
  docs/data/templates.yaml
  docs/index.js
  docs/layouts/partials/footer/footer.html
  docs/package-lock.json
  docs/package.json
  docs/static/scripts/fetchTemplates.mjs
  docs/themes/avocadocs/layouts/_default/list.html
  docs/themes/avocadocs/layouts/_default/single.html
  docs/themes/avocadocs/layouts/partials/feedback-form.html
  docs/themes/avocadocs/layouts/partials/scripts/global.html
  docs/themes/avocadocs/static/docsuikit/assets/css/layout.css
  docs/themes/avocadocs/static/styles/customizations.css
  docs/themes/avocadocs/static/styles/search.css
Labels: website

#2420 📝 Rework Varnish doc
  docs/src/add-services/varnish.md
  docs/src/bestpractices/http-caching.md
Labels: docs rework

#2430 📝 Make it clear headers are for static files
  docs/src/create-apps/web/custom-headers.md
Labels: quick task

#2441 🔥 Remove changelog
  docs/src/other/changelog.md
Labels: quick task

#2439 📝 Clarify defaulting to mail()
  docs/src/development/email.md
Labels: quick task

#2429 ⬆️ Update dependencies
  docs/package-lock.json
  docs/package.json
  docs/static/scripts/xss/package-lock.json
  docs/static/scripts/xss/package.json
Labels: quick task, website

#2444 🔥 Redirect changelog directly
  .platform/routes.yaml
  docs/src/other/changelog.md
Labels: quick task

#2448 ✨ Build environments through a workflow
  .github/workflows/get-pr-info.yaml
  .github/workflows/manage-environment.yaml
Labels: s&c

#2449 📝 OpenSearch 2.0 available
  docs/data/registry.json
Labels: quick task

#2450 ✏️ Remove duplicate top-level key
  docs/src/create-apps/web/static.md
Labels: quick task
