Repository platformsh/platformsh-docs, pull requests merged in 2022-11, with the labels that each got.

#2651 Improve DDEV documentation
  docs/src/development/local/ddev.md
Labels: build-fork

#2652 Fix: Note
  docs/src/add-services/postgresql.md
Labels: build-fork

#2646 💚 Process fixes
  .github/workflows/comment-on-pr.yaml
  .github/workflows/manage-environment.yaml
Labels: quick task

#2654 📝 Add Node.js 18 support
  docs/data/registry.json
Labels: quick task

#2656 ⬆️ Update dependencies
  docs/data/templates.yaml
  docs/package-lock.json
  docs/package.json
  docs/static/files/fetch/examples/golang/mysql
  docs/static/files/fetch/examples/java/elasticsearch
  docs/static/files/fetch/examples/java/kafka
  docs/static/files/fetch/examples/java/memcached
  docs/static/files/fetch/examples/java/mongodb
  docs/static/files/fetch/examples/java/mysql
  docs/static/files/fetch/examples/java/postgresql
  docs/static/files/fetch/examples/java/rabbitmq
  docs/static/files/fetch/examples/java/redis
  docs/static/files/fetch/examples/java/solr
  docs/static/files/fetch/examples/python/mysql
  docs/static/scripts/xss/package.json
  search/.platform.app.yaml
  search/build.sh
  search/poetry.lock
  search/post_deploy.sh
Labels: quick task, website

#2661 📝 Add example of managing Maven versions
  docs/layouts/shortcodes/variable.html
  docs/src/languages/java/_index.md
Labels: quick task

#2662 📝 Update endpoint for MongoDB Enterprise
  docs/data/registry.json
Labels: quick task

#2663 📝 Update supported Vault versions
  docs/data/registry.json
Labels: quick task

#2665 📝 Note the X-Platform-Cache header
  docs/src/define-routes/cache.md
Labels: quick task

#2664 📝 Make it clear how to use nvm for runtime
  docs/src/languages/nodejs/node-version.md
Labels: quick task

#2650 📝 Rework migration tutorial
  docs/src/tutorials/migrating.md
Labels: docs rework

#2666 🐛 Fix broken links
  docs/src/add-services/redis.md
  docs/src/guides/wordpress/composer/migrate.md
Labels: quick task

#2667 🐛 Update instructions for properties
  docs/src/increase-observability/logs/forward-logs.md
Labels: quick task

#2447 :memo: Update DNS configuration instructions
  docs/src/define-routes/_index.md
  docs/src/define-routes/https.md
  docs/src/domains/_index.md
  docs/src/domains/cdn/_index.md
  docs/src/domains/cdn/cloudflare.md
  docs/src/domains/cdn/fastly.md
  docs/src/domains/checklist.md
  docs/src/domains/quick-start.md
  docs/src/domains/steps/_index.md
  docs/src/domains/steps/dns.md
  docs/src/domains/steps/subdomains.md
  docs/src/domains/steps/tls.md
  docs/src/domains/troubleshoot.md
  docs/src/environments/default-environment.md
  docs/src/gettingstarted/next-steps/going-live/configure-dns.md
  docs/src/gettingstarted/next-steps/going-live/first-steps.md
  docs/src/other/glossary.md
  docs/static/images/management-console/edit-plan.png
  docs/static/images/management-console/settings-upgrade-plan.png
Labels: docs rework

#2675 📝 Add support for PostgreSQL 14
  docs/data/registry.json
Labels: quick task

#2649 :memo: Rework access site page and add file transfer page
  docs/src/development/access-site.md
  docs/src/development/email.md
  docs/src/development/file-transfer.md
  docs/src/development/headers.md
  docs/src/tutorials/exporting.md
Labels: docs rework

#2679 The token needs admin access to the repository
  docs/src/integrations/source/bitbucket.md
Labels: build-fork

#2680 📝 Clarify HTTP access covers entire environment
  docs/src/environments/http-access-control.md
Labels: quick task

#2681 🐛 Fix broken links to headers
  docs/src/domains/checklist.md
  docs/src/domains/steps/dns.md
  docs/src/projects/region-migration.md
  docs/src/tutorials/migrating.md
Labels: quick task

#2682 Document direct connection to MongoDB service via app container
  docs/src/add-services/mongodb.md
Labels: build-fork

#2685 📝 Clarify custom domains for Dedicated Gen 2
  docs/src/domains/steps/_index.md
Labels: quick task

#2687 📝 Clarify how to restart a worker
  docs/src/create-apps/workers.md
Labels: quick task

#2678 Update solr.md to reflect removal of the search_api_solr_defaults module
  docs/src/guides/drupal9/solr.md
Labels: build-fork

#2696 📝 Make it clear logs in files can't be forwarded
  docs/src/increase-observability/logs/forward-logs.md
  styles/Vocab/Platform/accept.txt
Labels: quick task

#2699 :memo: Mark Go 1.19 as stable
  docs/data/registry.json
Labels: quick task

#2704 📝 Clarify storage pricing per environment
  docs/src/administration/pricing/_index.md
Labels: quick task

#2703 📝 Clarify DNS challenge
  docs/src/define-routes/https.md
Labels: quick task

#2711 Observability forwarding token fix
  docs/src/increase-observability/logs/forward-logs.md
Labels: build-fork

#2712 📝 Switch OpenSearch to major version only
  .github/workflows/manage-environment.yaml
  docs/data/registry.json
  docs/src/add-services/opensearch.md
Labels: quick task

#2713 📝 Clarify thresholds for disk notifications
  docs/src/integrations/notifications.md
Labels: quick task

#2714 ♿️ Improve accessibility of codetabs
  docs/config/_default/params.yaml
  docs/static/styles/user-customizations.css
  docs/themes/avocadocs/layouts/partials/codetabs.html
  docs/themes/avocadocs/static/docsuikit/assets/css/theme.css
  docs/themes/avocadocs/static/styles/customizations.css
Labels: website

#2715 📝 Simplify examples for copying and pasting
  contributing/content-style.md
  contributing/markup-format.md
  docs/layouts/shortcodes/guides/deployment.html
  docs/src/add-services/_index.md
  docs/src/add-services/mysql/_index.md
  docs/src/administration/cli/_index.md
  docs/src/create-apps/app-reference.md
  docs/src/development/access-site.md
  docs/src/development/file-transfer.md
  docs/src/development/local/_index.md
  docs/src/development/local/docksal.md
  docs/src/development/local/lando.md
  docs/src/development/ssh/_index.md
  docs/src/development/transfer-dedicated.md
  docs/src/environments/_index.md
  docs/src/guides/drupal9/deploy/next-steps.md
  docs/src/guides/strapi/local-development/local-development-v4.md
  docs/src/languages/php/extensions.md
  docs/src/projects/delete-project.md
  docs/src/tutorials/exporting.md
Labels: quick task

#2720 📝 Deprecate PHP 7.4
  docs/data/registry.json
Labels: quick task

#2702 :memo: Rework PHP-FPM sizing
  docs/src/languages/php/fpm.md
  docs/static/images/php/PHP-FPM-Workers-Calculation.png
  docs/static/images/php/phpfpmworkers.png
Labels: docs rework

#2708 :memo: Rework Redis and Drupal guide
  docs/layouts/shortcodes/endpoint-description.md
  docs/src/guides/drupal9/redis.md
Labels: docs rework

#2722 rename gitlab to github in integration:add
  docs/src/integrations/source/github.md
Labels: quick task, build-fork

#2723 📝 Note when automated backups are taken
  docs/src/environments/backup.md
  docs/src/projects/change-project-timezone.md
Labels: quick task
