Repository platformsh/platformsh-docs, pull requests merged in 2022-09, with the labels that each got.

#2525 Mark geoip as available for PHP 8.0 and 8.1
  docs/src/languages/php/extensions.md
Labels: quick task

#2526 🐛 Fix broken link
  docs/src/tutorials/third-party.md
Labels: quick task

#2522 🐛 Fix improper version in app example
  docs/src/create-apps/_index.md
Labels: quick task

#2511 📝 Rework default environment guide
  contributing/markup-format.md
  docs/src/environments/default-environment.md
  docs/static/images/management-console/defaultbranch-main.png
  docs/static/images/management-console/existing-parentnull.png
  docs/static/images/management-console/main-newparent.png
  docs/themes/avocadocs/layouts/_default/single.html
  docs/themes/avocadocs/layouts/shortcodes/codetabs.html
  styles/Vocab/Platform/accept.txt
Labels: docs rework

#2524 📝 Update YAML introduction
  docs/layouts/shortcodes/guides/config-desc.md
  docs/src/create-apps/upgrading.md
  docs/src/languages/java/migration.md
  docs/src/overview/yaml.md
  docs/src/overview/yaml/_index.md
  docs/src/overview/yaml/platform-yaml-tags.md
  docs/src/overview/yaml/what-is-yaml.md
  docs/static/images/yaml/basic.svg
  docs/static/images/yaml/mapping.svg
  docs/static/images/yaml/multi-line.svg
  docs/static/images/yaml/sequence.svg
  styles/Vocab/Platform/accept.txt
Labels: docs rework

#2530 🐛 Fix improper syntax in app config
  docs/src/create-apps/web/custom-headers.md
Labels: quick task

#2541 📝 Make restore description more precise
  docs/src/administration/backup-and-restore.md
Labels: quick task

#2544 📝 Add note on status page
  docs/src/development/troubleshoot.md
Labels: quick task

#2535 📝 Clarify need for .environment file to run drush
  docs/src/guides/drupal9/deploy/customize.md
Labels: quick task

#2553 📝 Add rdkafka PHP extension
  docs/src/languages/php/extensions.md
Labels: quick task

#2545 📝 Document API token for Lando
  docs/src/development/local/lando.md
Labels: quick task

#2563 📝 Update list of features not available on legacy
  docs/src/create-apps/app-reference.md
  docs/src/projects/region-migration.md
Labels: quick task

#2555 Fixing encoding issues
  docs/static/scripts/xss/package-lock.json
  docs/static/scripts/xss/package.json
  docs/static/scripts/xss/src/components/Suggestions.js
  docs/static/scripts/xss/src/components/SuggestionsPrimary.js
Labels: build-fork

#2552 🐛 Fix broken links
  docs/src/guides/gatsby/headless/drupal.md
Labels: quick task

#2546 📝 Clarify SEO visibility setting
  docs/src/environments/search-engine-visibility.md
Labels: quick task

#2580 📝 Clarify shallow clone problem for GitLab
  docs/src/development/troubleshoot.md
Labels: quick task

#2579 🚚 Move npm workspace to docs
  .github/workflows/pr-check-links.yaml
  README.md
  docs/package-lock.json
  docs/package.json
  docs/static/files/fetch/examples/relationships/vault-kms
  docs/static/scripts/xss/package-lock.json
  docs/static/scripts/xss/package.json
  package-lock.json
  package.json
Labels: website

#2572 📝 Update images and sort
  docs/data/registry.json
Labels: quick task

#2590 📝 Clarify where metrics are available
  docs/src/increase-observability/metrics/_index.md
  docs/src/increase-observability/metrics/dedicated.md
  docs/src/increase-observability/metrics/grid.md
Labels: quick task

#2591 🐛 Make shortcodes in codetabs work
  contributing/markup-format.md
  docs/layouts/shortcodes/icon.html
  docs/layouts/shortcodes/icon.md
  docs/src/administration/backup-and-restore.md
  docs/src/administration/users.md
  docs/src/create-apps/source-operations.md
  docs/src/development/access-site.md
  docs/src/development/email.md
  docs/src/development/troubleshoot.md
  docs/src/domains/quick-start.md
  docs/src/domains/steps/tls.md
  docs/src/environments/change-parent.md
  docs/src/environments/deactivate-environment.md
  docs/src/environments/http-access-control.md
  docs/src/environments/search-engine-visibility.md
  docs/src/other/glossary.md
  docs/src/projects/delete-project.md
Labels: website
