Repository platformsh/platformsh-docs, pull requests merged in 2022-04, with the labels that each got.

#2263 :bug: Fix Redis extension name
  docs/src/guides/drupal9/redis.md
Labels: quick task

#2259 :memo: Change Docksal doc into tutorial
  docs/src/development/local/docksal.md
Labels: docs rework

#2270 :memo: Orange Cloud is now encrypted
  docs/src/security/data-deletion.md
  docs/src/security/encryption.md
Labels: quick task

#2036 📝 Update Underscorejs version listed
  docs/src/integrations/activity/_index.md
Labels: upcoming version

#2215 :sparkles: Mark `services.yaml` as optional
  docs/layouts/partials/examples/servicedefn.html
  docs/layouts/shortcodes/endpoint-description.md
  docs/layouts/shortcodes/guides/config-desc.html
  docs/layouts/shortcodes/guides/config-service.md
  docs/src/configuration/app/web.md
  docs/src/configuration/services/_index.md
  docs/src/dedicated/architecture/options.md
  docs/src/gettingstarted/introduction/own-code/app-configuration.md
  docs/src/gettingstarted/introduction/own-code/project-configuration.md
  docs/src/gettingstarted/introduction/own-code/service-configuration.md
  docs/src/guides/drupal9/deploy/configure.md
  docs/src/guides/gatsby/deploy/configure.md
  docs/src/guides/general/deploy-button.md
  docs/src/guides/micronaut/deploy/configure.md
  docs/src/guides/quarkus/deploy/configure.md
  docs/src/guides/spring/deploy/configure.md
  docs/src/guides/typo3/deploy/configure.md
  docs/src/other/changelog.md
  docs/src/overview/structure.md
  styles/Vocab/Platform/accept.txt
Labels: upcoming version

#2230 :memo: Note routes resolve with trailing slashes
  docs/src/configuration/routes/_index.md
Labels: upcoming version

#2286 :bug: Fix broken links
  docs/layouts/shortcodes/guides/tools.md
  docs/src/development/private-repository.md
  docs/src/development/ssh/ssh-keys.md
  docs/src/development/tools.md
  docs/src/guides/drupal9/deploy/configure.md
  docs/src/integrations/activity/_index.md
  docs/src/integrations/source/github.md
  docs/src/other/changelog.md
Labels: quick task

#2299 📝 Clarify regions to migrate to
  docs/src/guides/general/region-migration.md
Labels: quick task

#2305 🐛 Use Vale version that recognizes workflow runs
  .github/workflows/lint-prose.yaml
Labels: quick task

#2308 📝 Clarify site scaling
  docs/src/development/faq.md
Labels: quick task
