Repository platformsh/platformsh-docs, pull requests merged in 2022-10, with the labels that each got.

#2592 🐛 Fix shortcode for create project link
  docs/layouts/shortcodes/create-project-link.html
Labels: quick task, website

#2594 ✏️ Remove extra word (the)
  docs/src/projects/region-migration.md
Labels: quick task

#2597 📝 Add note on necessary resources
  docs/src/create-apps/workers.md
Labels: quick task

#2589 🔥 Deprecate old images
  docs/data/registry.json
  docs/layouts/shortcodes/image-versions-legacy.md
Labels: quick task

#2595 📝 Add example of no build flavor
  docs/src/languages/php/_index.md
Labels: quick task

#2593 🐛 Fix broken links
  docs/src/guides/gatsby/headless/drupal.md
  docs/src/increase-observability/metrics/dedicated-generation-3.md
Labels: quick task

#2596 Show that n on platform is compatible with multiple types of node version declarations
  docs/src/languages/nodejs/node-version.md
Labels: build-fork

#2605 Do not propose to use a deprecated version
  docs/src/add-services/network-storage.md
Labels: build-fork

#2600 🐛 Fix partial call
  docs/src/create-apps/app-reference.md
Labels: quick task

#2604 📝 Update users permission
  docs/src/administration/organizations.md
Labels: upcoming version, quick task

#2607 📝 Add Go 1.19
  docs/data/registry.json
Labels: quick task

#2609 🐛 Fix additional host example
  docs/src/create-apps/app-reference.md
Labels: quick task

#2602 ✨ Add premium badges
  docs/config/_default/params.yaml
  docs/data/registry.json
  docs/layouts/partials/premium-features/badge.html
  docs/layouts/shortcodes/supported-services.md
  docs/src/add-services/_index.md
  docs/src/add-services/mongodb.md
  docs/static/styles/user-customizations.css
  docs/themes/avocadocs/layouts/partials/navigation/sidebar/list.html
Labels: website

#2612 Bump Redis and Relay versions
  docs/src/languages/php/redis.md
Labels: build-fork

#2615 📝 Add PostgreSQL 14 to supported versions
  docs/data/registry.json
Labels: quick task

#2618 :bug: Fix broken links
  docs/src/languages/php/frameworks.md
  docs/src/tutorials/third-party.md
Labels: quick task

#2617 ✏️ Fix example URL for non-Production environments
  contributing/content-style.md
Labels: quick task

#2621 📝 Clarify option to use persistent Redis
  docs/src/guides/drupal9/redis.md
Labels: quick task

#2610 📝 Rework pricing doc
  .platform/routes.yaml
  docs/layouts/shortcodes/guides/gatsby/headless-plansize.md
  docs/src/add-services/_index.md
  docs/src/administration/cli/_index.md
  docs/src/administration/pricing/_index.md
  docs/src/administration/pricing/sponsored.md
  docs/src/administration/web/_index.md
  docs/src/create-apps/app-reference.md
  docs/src/create-apps/multi-app.md
  docs/src/create-apps/troubleshoot-disks.md
  docs/src/create-apps/workers.md
  docs/src/development/troubleshoot.md
  docs/src/increase-observability/metrics/_index.md
  docs/src/overview/pricing/_index.md
Labels: docs rework

#2622 🔍️ Make .environment section more visible
  docs/src/development/variables/set-variables.md
Labels: website

#2623 🏗️ Move Gen 2 below Gen 3
  docs/src/dedicated-gen-2/_index.md
Labels: quick task, website

#2614 📝 Rework private repo doc
  docs/config/_default/params.yaml
  docs/src/development/private-repository.md
  docs/src/development/submodules.md
  docs/static/styles/user-customizations.css
Labels: docs rework

#2624 :memo: Rework configure environments page
  docs/src/administration/web/configure-environment.md
  docs/static/images/management-console/env-name.png
Labels: docs rework

#2639 Use platform-compatible app names in example code
  docs/src/add-services/varnish.md
Labels: build-fork

#2638 ✨ Allow notes inside shortcodes
  contributing/markup-format.md
  docs/layouts/partials/note.html
  docs/layouts/shortcodes/guides/deployment.html
  docs/layouts/shortcodes/guides/signup.md
  docs/layouts/shortcodes/note.md
  docs/themes/avocadocs/layouts/shortcodes/note.html
Labels: website

#2627 📝 Document automated backups
  .platform/routes.yaml
  docs/layouts/shortcodes/disk-downsize.md
  docs/src/administration/backup-and-restore.md
  docs/src/dedicated-gen-2/overview/backups.md
  docs/src/dedicated-gen-2/overview/grid.md
  docs/src/development/sanitize-db.md
  docs/src/domains/steps/_index.md
  docs/src/environments/backup.md
  docs/src/environments/default-environment.md
  docs/src/environments/restore.md
  docs/src/gettingstarted/developing/dev-environments/merge.md
  docs/src/gettingstarted/developing/dev-environments/next-steps.md
  docs/src/integrations/activity/reference.md
  docs/src/other/glossary.md
  docs/src/projects/region-migration.md
  docs/src/security/backups.md
  docs/src/security/data-retention.md
  docs/static/images/backup-cycles/advanced-retention.png
  docs/static/images/backup-cycles/first-cycle.png
  docs/static/images/backup-cycles/premium-retention.png
  docs/static/images/backup-cycles/replace-backup.png
  docs/static/images/backup-cycles/replace-cycle.png
  docs/static/images/backup-cycles/retain.png
Labels: upcoming version

#2626 🐛 Fix broken header links
  docs/layouts/shortcodes/guides/gatsby/headless-plansize.md
  docs/src/development/private-repository.md
Labels: quick task

#2641 🐛 Fix broken link
  docs/src/administration/web/configure-environment.md
Labels: quick task

#2629 📝 Specify Java runtimes are headless
  docs/src/languages/java/_index.md
Labels: quick task

#2642 🐛 Fix syntax for output variables
  .github/workflows/get-pr-info.yaml
Labels: quick task

#2643 💚 Fix get info workflow
  .github/workflows/get-pr-info.yaml
Labels: quick task

#2613 :memo: Rework Composer migration update
  docs/src/guides/wordpress/composer/migrate.md
  styles/Vocab/Platform/accept.txt
Labels: docs rework

#2644 ⏪️ Temporarily remove PostgreSQL 14
  docs/data/registry.json
Labels: quick task

#2630 📝 Update permission names and instructions
  docs/src/administration/organizations.md
Labels: build-fork

#2645 🐛 Fix broken links
  docs/src/development/local/lando.md
  docs/src/domains/steps/_index.md
Labels: quick task
