Repository platformsh/platformsh-docs, pull requests merged in 2022-01, with the labels that each got.

#2066 :bug: Remove extra buttons
  docs/src/gettingstarted/developing/local-development/download-code.md
Labels: Quick task

#2073 :bug: Fix description of disk property for apps
  docs/src/configuration/app/app-reference.md
Labels: Quick task

#2078 :bug: Fix region names for public IPs
  docs/data/regions.yaml
Labels: Quick task

#2081 :memo: Update supported Redis version
  docs/data/registry.json
Labels: Quick task

#2037 :memo: Improve SSH docs
  docs/src/configuration/services/_index.md
  docs/src/development/access-site.md
  docs/src/development/ssh/_index.md
  docs/src/development/ssh/ssh-keys.md
  docs/src/development/ssh/troubleshoot-ssh.md
  styles/Vocab/Platform/accept.txt
Labels: Docs Rework

#2019 :memo: Rework the MySQL overview to template and style
  contributing/markup-format.md
  docs/config/_default/config.yaml
  docs/data/remote-examples/language-examples/examples.yaml
  docs/layouts/partials/examples/relationship.html
  docs/layouts/partials/examples/servicedefn.html
  docs/layouts/shortcodes/deprecated-versions.md
  docs/layouts/shortcodes/endpoint-description.html
  docs/layouts/shortcodes/endpoint-description.md
  docs/package-lock.json
  docs/src/configuration/app/app-reference.md
  docs/src/configuration/services/elasticsearch.md
  docs/src/configuration/services/headless-chrome.md
  docs/src/configuration/services/influxdb.md
  docs/src/configuration/services/kafka.md
  docs/src/configuration/services/memcached.md
  docs/src/configuration/services/mongodb.md
  docs/src/configuration/services/mysql/_index.md
  docs/src/configuration/services/network-storage.md
  docs/src/configuration/services/postgresql.md
  docs/src/configuration/services/rabbitmq.md
  docs/src/configuration/services/redis.md
  docs/src/configuration/services/solr.md
  docs/src/configuration/services/varnish.md
  docs/src/guides/drupal9/elasticsearch.md
  docs/src/guides/drupal9/memcached.md
  docs/src/guides/drupal9/redis.md
  docs/src/guides/drupal9/solr.md
  docs/src/guides/micronaut/elasticsearch.md
  docs/src/guides/micronaut/jpa.md
  docs/src/guides/micronaut/micronaut-data.md
  docs/src/guides/micronaut/mongodb.md
  docs/src/guides/micronaut/redis.md
  docs/src/guides/quarkus/elasticsearch.md
  docs/src/guides/quarkus/jpa.md
  docs/src/guides/quarkus/mongodb.md
  docs/src/guides/quarkus/panache.md
  docs/src/guides/quarkus/redis.md
  docs/src/guides/spring/elasticsearch.md
  docs/src/guides/spring/jpa.md
  docs/src/guides/spring/mongodb.md
  docs/src/guides/spring/redis.md
  docs/src/languages/dotnet.md
  docs/src/languages/elixir.md
  docs/src/languages/go.md
  docs/src/languages/java/_index.md
  docs/src/languages/nodejs/_index.md
  docs/src/languages/php/_index.md
  docs/src/languages/python.md
  docs/src/languages/ruby.md
  docs/static/files/fetch/examples/relationships/headlesschrome
  docs/static/files/fetch/examples/relationships/oraclemysql
  docs/static/files/fetch/examples/relationships/vault
  docs/static/files/fetch/examples/relationships/vault-kms
  docs/templates/language-reference.md
  docs/templates/service-reference.md
  docs/themes/avocadocs/layouts/shortcodes/readFile.html
Labels: Docs Rework

#2042 :memo: Rework services overview
  docs/layouts/partials/examples/relationship.html
  docs/layouts/partials/examples/servicedefn.html
  docs/layouts/shortcodes/deprecated-versions.md
  docs/layouts/shortcodes/endpoint-description.md
  docs/src/configuration/services/_index.md
  docs/src/configuration/services/mysql/_index.md
  docs/src/configuration/services/postgresql.md
  docs/src/configuration/services/redis.md
  docs/src/development/access-site.md
  docs/templates/service-reference.md
  styles/Vocab/Platform/reject.txt
Labels: Docs Rework

#2090 :arrow_up: Upgrade dependencies
  docs/package-lock.json
  docs/package.json
  docs/static/files/fetch/examples/relationships/vault-kms
  docs/static/scripts/xss/package-lock.json
  docs/static/scripts/xss/package.json
  docs/static/scripts/xss/src/App.js
  docs/static/scripts/xss/webpack.dev.js
  docs/static/scripts/xss/webpack.prod.js
Labels: dependencies, Quick task

#2091 :bug: Avoid HTML escaping in shortcode
  contributing/markup-format.md
  docs/layouts/shortcodes/guides/data-migration.html
  docs/layouts/shortcodes/guides/data-migration.md
  docs/src/guides/drupal9/deploy/deploy.md
  docs/src/guides/micronaut/deploy/deploy.md
  docs/src/guides/quarkus/deploy/deploy.md
  docs/src/guides/spring/deploy/deploy.md
  docs/src/guides/typo3/deploy/deploy.md
  docs/src/guides/wordpress/deploy/deploy.md
  docs/src/guides/wordpress/vanilla/deploy.md
Labels: Quick task

#1907 Multidb pg 10 11 12
  docs/src/configuration/services/postgresql.md
Labels: Upcoming version

#2076 :memo: Rework routes documentation
  docs/src/configuration/routes/_index.md
  docs/static/images/cli/platform-routes-cli.png
Labels: Docs Rework

#2085 :memo: Clarify cron pausing during backups
  docs/src/configuration/app/app-reference.md
Labels: Quick task

#2099 :bug: Fix typo
  docs/src/configuration/app/app-reference.md
Labels: Quick task

#2108 :memo: Clarify when domains are challenged
  docs/src/configuration/routes/https.md
Labels: Quick task

#2102 :memo: Add note about /tmp disk usage
  docs/src/configuration/services/network-storage.md
Labels: Quick task
