Repository platformsh/platformsh-docs, pull requests merged in 2022-08, with the labels that each got.

#2475 📝 Restore fr-1 region
  docs/data/regions.yaml
Labels: quick task

#2484 📝 Add Java 17
  docs/data/registry.json
Labels: quick task

#2482 📝 Note backup differences for Dedicated envs
  docs/src/dedicated/overview/grid.md
Labels: quick task

#2476 🔥 Remove eZ Platform template
  docs/src/languages/php/frameworks.md
Labels: quick task

#2485 🚨 Improve search scraping
  search/docs/middlewares.py
  search/docs/settings.py
  search/poetry.lock
  search/pyproject.toml
Labels: website

#2487 🐛 Fix broken links
  docs/layouts/partials/tiered-features/body.html
  docs/src/add-services/redis.md
  docs/src/overview/pricing/_index.md
Labels: quick task

#2491 📝 Clarify upstream for subdomain
  docs/src/define-routes/_index.md
Labels: quick task

#2445 📝 Add basic Dedicated Generation 3 metrics docs
  docs/src/increase-observability/metrics/_index.md
  docs/src/increase-observability/metrics/dedicated-generation-3.md
  docs/static/images/metrics/all-dedicated-gen3.png
  docs/static/images/metrics/app-container-gen3.png
  docs/static/images/metrics/filtering-gen3.png
  docs/static/images/metrics/mysql-container-gen3.png
  docs/static/images/metrics/redis-container-gen3.png
  docs/static/images/metrics/schedule-worker-container-gen3.png
Labels: upcoming version

#2493 Update PHP extensions for 8.1 and memcached
  docs/src/languages/php/extensions.md
Labels: quick task

#2492 📝 Document org transfer
  docs/src/administration/organizations.md
  docs/src/administration/users.md
Labels: quick task

#2496 📝 Rename an activity property
  docs/src/integrations/activity/reference.md
Labels: quick task

#2489 💄 Keep tables inside content wrapper
  docs/config/_default/params.yaml
  docs/static/styles/user-customizations.css
  docs/themes/avocadocs/static/styles/customizations.css
Labels: website

#2497 📝 Add troubleshooting for missing commit
  docs/src/development/troubleshoot.md
Labels: quick task

#2494 📝 Note live backups available in Console
  docs/layouts/shortcodes/icon-paths/add.html
  docs/layouts/shortcodes/icon-paths/backup.html
  docs/src/administration/backup-and-restore.md
Labels: upcoming version

#2498 📝 Add clarity to deprecation
  docs/layouts/shortcodes/deprecated-versions.md
  docs/src/other/glossary.md
Labels: quick task

#2501 📝 Rework backup and restore doc
  docs/layouts/shortcodes/icon-paths/success.html
  docs/src/administration/backup-and-restore.md
  docs/src/administration/cli/api-tokens.md
Labels: docs rework

#2507 🐛 Fix time for paused crons
  docs/src/create-apps/app-reference.md
Labels: quick task

#2518 🐛 Fix broken links
  docs/src/guides/ibexa/deploy.md
  docs/src/guides/ibexa/fastly.md
Labels: quick task

#2519 📝 Deprecate old Elixir versions
  docs/data/registry.json
Labels: quick task

#2517 📝 Document limits to disk downsizing
  docs/layouts/shortcodes/disk-downsize.md
  docs/layouts/shortcodes/legacy-regions.md
  docs/src/add-services/_index.md
  docs/src/create-apps/app-reference.md
  docs/src/create-apps/troubleshoot-disks.md
Labels: quick task

#2520 📝 Remove env variables from activity scripts
  docs/src/integrations/activity/_index.md
  docs/src/integrations/activity/discord.md
  docs/src/integrations/activity/slack.md
  docs/src/integrations/activity/utility.md
Labels: quick task
