Repository platformsh/platformsh-docs, pull requests merged in 2022-12, with the labels that each got.

#2725 Add ioncube for php8.1 and others
  docs/src/languages/php/extensions.md
Labels: build-fork

#2728 📝 Update RabbitMQ versions
  docs/data/registry.json
Labels: quick task

#2727 📝 Clarify use of tunnel:single
  docs/src/add-services/_index.md
  docs/src/add-services/influxdb.md
  docs/src/add-services/solr.md
  docs/src/development/ssh/_index.md
  docs/src/guides/strapi/local-development/local-development-v4.md
Labels: quick task

#2731 📝 Update RabbitMQ versions for Gen 3
  docs/data/registry.json
Labels: quick task

#2736 🐛 Fix broken links
  .github/workflows/scheduled-check-links.yaml
  docs/src/create-apps/app-reference.md
  docs/src/development/local/untethered.md
  docs/src/development/variables/use-variables.md
  docs/src/projects/region-migration.md
Labels: quick task

#2737 👷 Use CLI directly for geting environment info
  .github/workflows/get-pr-info.yaml
  .platform/routes.yaml
Labels: quick task

#2734 Bring consistency in backups documentation
  .github/workflows/get-pr-info.yaml
  docs/src/environments/backup.md
Labels: quick task

#2738 🐛 Fix remaining codetabs syntax
  docs/src/increase-observability/logs/access-logs.md
  docs/src/increase-observability/logs/forward-logs.md
  docs/src/languages/php/_index.md
Labels: quick task

#2739 💚 Fix environment URL in GitHub comments
  .github/workflows/get-pr-info.yaml
Labels: quick task

#2726 :memo: Rework API tokens guide
  docs/src/administration/cli/api-tokens.md
  docs/static/images/management-console/api-tokens-name.png
  docs/static/images/management-console/api-tokens-new.png
  docs/static/images/management-console/api-tokens-view.png
  docs/static/images/management-console/copy-api-token.png
Labels: docs rework

#2741 :bug: Fix links pointing to API Tokens page headers
  docs/src/create-apps/source-operations.md
  docs/src/development/local/ddev.md
  docs/src/development/local/docksal.md
  docs/src/development/local/lando.md
  docs/src/environments/backup.md
Labels: quick task

#2742 💚 Fix linting of line length with tables
  docs/package-lock.json
  docs/package.json
Labels: quick task

#2747 📝 Note Oracle MySQL not available on Gen 3
  docs/src/add-services/mysql/_index.md
Labels: quick task

#2743 📝 Clarify MySQL permissions
  docs/src/add-services/mysql/_index.md
Labels: quick task

#2752 📝 Add missing closing parentheses
  docs/src/dedicated-gen-3/overview.md
Labels: quick task

#2755 :memo: Add Java 19
  docs/data/registry.json
Labels: quick task

#2756 :bug: Fix typo for SPF record
  docs/src/development/email.md
Labels: quick task

#2753 Remove pre-launch checklist page
  .platform/routes.yaml
  docs/src/domains/checklist.md
  docs/src/domains/troubleshoot.md
Labels: docs rework

#2745 :bug: Fix codetabs syntax
  contributing/markup-format.md
  docs/src/add-services/kafka.md
  docs/src/development/local/tethered.md
  docs/src/environments/change-parent.md
  docs/src/languages/dotnet.md
  docs/src/languages/elixir.md
  docs/src/languages/go.md
  docs/src/languages/java/_index.md
  docs/src/languages/lisp.md
  docs/src/languages/nodejs/_index.md
  docs/src/languages/php/_index.md
  docs/src/languages/python/_index.md
  docs/src/languages/ruby.md
Labels: quick task

#2760 Update configure-project.md
  docs/src/administration/web/configure-project.md
Labels: build-fork

#2761 :memo: Add Python 3.11
  docs/data/registry.json
Labels: quick task

#2759 📝 Update guidance for upstream issues
  contributing/markup-format.md
Labels: quick task

#2758 📝 Rename backup plan
  docs/src/environments/backup.md
  docs/src/security/backups.md
  docs/src/security/data-retention.md
Labels: quick task

#2764 📝 Hard deprecate Python 2.7
  docs/data/registry.json
  docs/src/languages/python/_index.md
Labels: quick task

#2765 📝 Revise subdomain protection
  docs/src/domains/steps/subdomains.md
Labels: docs rework
