Repository platformsh/platformsh-docs, pull requests merged in 2023-08, with the labels that each got.

#3302 revamp of multi-app and git submodules doc pages
  docs/layouts/shortcodes/multi-app-intro.md
  docs/src/add-services/network-storage.md
  docs/src/administration/cli/_index.md
  docs/src/bestpractices/oneormany.md
  docs/src/create-apps/_index.md
  docs/src/create-apps/app-reference.md
  docs/src/create-apps/hooks/_index.md
  docs/src/create-apps/multi-app.md
  docs/src/create-apps/multi-app/_index.md
  docs/src/create-apps/multi-app/project-structure.md
  docs/src/create-apps/multi-app/relationships.md
  docs/src/create-apps/multi-app/routes.md
  docs/src/dedicated-gen-2/architecture/options.md
  docs/src/define-routes/_index.md
  docs/src/development/submodules.md
  docs/src/environments/_index.md
  docs/src/get-started/monitor-and-troubleshoot/status.md
  docs/src/guides/gatsby/deploy/next-steps.md
  docs/src/guides/gatsby/headless/_index.md
  docs/src/guides/strapi/adding-frontends/_index.md
  docs/src/languages/java/migration.md
  docs/src/languages/nodejs/_index.md
  docs/static/images/config-diagrams/multiple-app.png
  docs/themes/psh-docs/layouts/shortcodes/guides/gatsby/headless-applicationsyaml.md
  docs/themes/psh-docs/layouts/shortcodes/guides/gatsby/headless-project.md
Labels: WIP, markdown/prose

#3316 Document Solr plugins
  docs/src/add-services/solr.md
Labels: quick task, markdown/prose

#3317 Update word-wrap version in /docs
  docs/package-lock.json
Labels: quick task, markdown/prose

#3319 Ruby revert default
  docs/src/languages/ruby.md
Labels: markdown/prose

#3320 Document how to get SSH info in Console
  docs/src/development/ssh/_index.md
Labels: quick task, markdown/prose

#3318 Recommend persistent Redis in Drupal guide
  docs/src/guides/drupal9/redis.md
  docs/themes/psh-docs/layouts/partials/examples/config_links.html
  docs/themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: quick task, markdown/prose

#3314 Create page on how to keep Git repo clean
  docs/src/bestpractices/clean-repository.md
  docs/themes/psh-docs/layouts/shortcodes/source-integration/enable-integration.html
Labels: enhancement, markdown/prose

#3321 Add guidance in Node.js version update procedure using nvm
  docs/src/languages/nodejs/node-version.md
Labels: quick task, markdown/prose

#3324 Update users.md
  docs/src/administration/users.md
Labels: markdown/prose

#3143 GA4
  docs/config/_default/params.yaml
  docs/static/scripts/xss/src/components/SuggestionsPrimary.js
  docs/themes/psh-docs/layouts/_default/baseof.html
  docs/themes/psh-docs/layouts/partials/head/head.html
  docs/themes/psh-docs/layouts/partials/header/actions.html
  docs/themes/psh-docs/layouts/partials/header/gtm_noscript.html
  docs/themes/psh-docs/layouts/partials/header/gtm_script.html
  docs/themes/psh-docs/layouts/partials/header/header.html
  docs/themes/psh-docs/layouts/partials/scripts/external.html
Labels: enhancement

#3331 Add .platform/services.yaml example to page on workers
  docs/src/create-apps/workers.md
Labels: quick task, markdown/prose

#3330 Add warning to proxy routes page
  docs/src/define-routes/proxy.md
Labels: quick task, markdown/prose

#2963 :memo: Add section on paused environments
  docs/src/environments/_index.md
Labels: enhancement, markdown/prose

#3338 Make recommendation to remove TXT record more explicit
  sites/platform/src/domains/steps/subdomains.md
Labels: quick task, markdown/prose

#3350 adds catch when calling ocktokit.request that may result in a 404
  sites/friday/utils/fetchTemplates.mjs
  sites/platform/utils/fetchTemplates.mjs
Labels: bug, markdown/prose

#3343 [Fix] Update path on get-pr-info
  .github/workflows/get-pr-info.yaml
Labels: markdown/prose

#3355 MariaDB: extend list of supported customization variables
  sites/platform/src/add-services/mysql/_index.md
Labels: build-fork, markdown/prose

#3363 Update python dependencies. Closes #52
  search/poetry.lock
Labels: markdown/prose

#3364 Document OpenSearch 1
  shared/data/registry.json
  sites/platform/src/add-services/opensearch.md
Labels: markdown/prose

#3372 Add clarification about geographic isolation on backups page
  sites/platform/src/environments/backup.md
Labels: quick task, markdown/prose

#3332 Hardcode service examples to enhance security
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/headless-chrome.md
  sites/platform/src/add-services/influxdb.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/add-services/vault.md
Labels: enhancement, markdown/prose

#3378 [Bug-fix] Vale fixes
  .vale.ini
  sites/platform/src/development/sanitize-db/mariadb.md
  sites/platform/src/domains/steps/custom-non-production-domains.md
Labels: bug, markdown/prose

#3380 Add progressive rollout note for paused env
  sites/platform/src/environments/_index.md
  themes/psh-docs/layouts/partials/progressive-rollout/banner.html
  themes/psh-docs/layouts/partials/progressive-rollout/body.md
Labels: quick task, markdown/prose

#3384 Add progressive rollout banner to custom non-prod domains
  sites/platform/src/domains/steps/custom-non-production-domains.md
Labels: quick task, markdown/prose

#3385 🐛 Fix vendor/name substitution in premium/add-on banner
  themes/psh-docs/layouts/shortcodes/premium-features/add-on.html
Labels: markdown/prose

#3391 postgresql: add pgvector extension
  sites/platform/src/add-services/postgresql.md
Labels: build-fork, markdown/prose

#3393 Remove OpenSearch 2.4 DG2 support
  shared/data/registry.json
Labels: quick task, markdown/prose

#3395 Update guide-buttons for vendor/name substitution
  themes/psh-docs/layouts/shortcodes/guide-buttons.html
Labels: markdown/prose

#3394 Fix post-vendorization display issue
  themes/psh-docs/layouts/shortcodes/guides/initialize.html
  themes/psh-docs/layouts/shortcodes/source-integration/enable-integration.html
Labels: quick task, markdown/prose
