Repository platformsh/platformsh-docs, pull requests merged in 2023-01, with the labels that each got.

#2763 🚚 Deprecate Hugo aliases
  .platform/routes.yaml
  CONTRIBUTING.md
  docs/src/add-services/mysql/mysql-replication.md
  docs/src/dedicated-gen-2/_index.md
  docs/src/dedicated-gen-2/architecture/_index.md
  docs/src/dedicated-gen-2/architecture/deploying.md
  docs/src/dedicated-gen-2/architecture/development.md
  docs/src/dedicated-gen-2/architecture/options.md
  docs/src/dedicated-gen-2/architecture/scalability.md
  docs/src/dedicated-gen-2/overview/_index.md
  docs/src/dedicated-gen-2/overview/backups.md
  docs/src/dedicated-gen-2/overview/grid.md
  docs/src/dedicated-gen-2/overview/monitoring.md
  docs/src/dedicated-gen-2/overview/onboarding.md
  docs/src/dedicated-gen-2/overview/security.md
  docs/src/development/deploy-button.md
  docs/src/development/regions.md
  docs/src/domains/cdn/cloudflare.md
  docs/src/domains/cdn/fastly.md
  docs/src/domains/steps/_index.md
  docs/src/environments/_index.md
  docs/src/environments/default-environment.md
  docs/src/increase-observability/logs/access-logs.md
  docs/src/increase-observability/metrics/_index.md
  docs/src/languages/nodejs/node-version.md
  docs/src/languages/php/composer-auth.md
  docs/src/other/glossary.md
  docs/src/overview/yaml/_index.md
  docs/src/projects/delete-project.md
  docs/src/projects/region-migration.md
Labels: quick task

#2773 🐛 Fix redirect to right page
  .platform/routes.yaml
  contributing/markup-format.md
Labels: quick task

#2776 :pencil2: Fix typo on introduction page
  docs/src/get-started/introduction.md
Labels: quick task

#2777 :memo: Add PostgreSQL 15
  docs/data/registry.json
Labels: quick task

#2774 Source operations page update
  docs/src/create-apps/source-operations.md
Labels: enhancement

#2780 :memo: Add Varnish 7.1
  docs/data/registry.json
Labels: quick task

#2779 💄 Make table content more accessible
  docs/config/_default/params.yaml
  docs/themes/psh-docs/layouts/partials/page-content.html
  docs/themes/psh-docs/layouts/partials/scripts/tailwind.html
  docs/themes/psh-docs/tailwind.config.js
Labels: website

#2781 🐛 Fix broken links
  .github/workflows/scheduled-check-links.yaml
  .platform/routes.yaml
  docs/src/add-services/mysql/_index.md
  docs/src/development/private-repository.md
  docs/src/development/sanitize-db.md
  docs/src/security/sca.md
Labels: quick task

#2793 📝 Update for Solr 9.1
  docs/data/registry.json
  docs/src/add-services/solr.md
Labels: quick task

#2797 💄 Update the theme
  .github/workflows/pr-check-links.yaml
  docs/.platform.app.yaml
  docs/layouts/partials/scripts/user-customizations.html
  docs/package-lock.json
  docs/package.json
  docs/themes/psh-docs/layouts/partials/head/css.html
  docs/themes/psh-docs/layouts/partials/page-content.html
  docs/themes/psh-docs/layouts/partials/scripts/external.html
  docs/themes/psh-docs/package.json
Labels: website

#2795 Fix log forwarding options
  docs/src/increase-observability/logs/forward-logs.md
Labels: build-fork

#2800 Update github.md
  docs/src/integrations/source/github.md
Labels: build-fork

#2762 :memo: Rework apex domains
  docs/src/domains/cdn/_index.md
  docs/src/domains/cdn/cloudflare.md
  docs/src/domains/cdn/fastly.md
  docs/src/domains/steps/_index.md
  docs/src/domains/steps/dns.md
Labels: docs rework

#2804 📝 Improve stacks
  docs/src/guides/django/_index.md
  docs/src/guides/django/deploy.md
  docs/src/guides/drupal9/_index.md
  docs/src/guides/hibernate/_index.md
  docs/src/guides/ibexa/_index.md
  docs/src/guides/jakarta/_index.md
  docs/src/guides/laravel/_index.md
  docs/src/guides/micronaut/_index.md
  docs/src/guides/nextjs/_index.md
  docs/src/guides/nextjs/deploy.md
  docs/src/guides/quarkus/_index.md
  docs/src/guides/spring/_index.md
  docs/src/guides/strapi/_index.md
  docs/src/guides/typo3/_index.md
Labels: quick task

#2802 :pencil2: Fix typo on flexible resources
  docs/src/create-apps/flexible-resources.md
Labels: quick task

#2788 :memo: Update supported and deprecated versions for PostgreSQL on DG3
  docs/data/registry.json
Labels: quick task

#2806 Note partial fix
  contributing/markup-format.md
  docs/layouts/shortcodes/guides/signup.md
  docs/themes/psh-docs/layouts/partials/note.html
Labels: website

#2807 🐛 Restore background to warning notes
  docs/themes/psh-docs/tailwind.config.js
Labels: quick task, website

#2813 📝 Clarify CLI upgrade path
  docs/layouts/shortcodes/cli-installation.html
  docs/src/administration/cli/_index.md
Labels: quick task

#2817 📝 Remove OpenSearch from DG3
  docs/data/registry.json
Labels: quick task

#2809 📝 Update instructions for CLI autocompletion
  docs/src/administration/cli/_index.md
Labels: quick task

#2810 :memo: Add htmltest setup to the README
  CONTRIBUTING.md
Labels: quick task

#2821 🔍️ Improve title tags
  docs/config/_default/config.yaml
  docs/themes/psh-docs/layouts/partials/head/head.html
  docs/themes/psh-docs/layouts/partials/head/twittercard.html
Labels: website

#2820 🐛 Avoid dupliction in DG3 service table
  docs/layouts/shortcodes/gen-3-services.html
Labels: quick task

#2818 🔥 Redirect index pages in get started section
  .platform/routes.yaml
Labels: quick task, website

#2819 🐛 Fix broken links
  .github/workflows/scheduled-check-links.yaml
  docs/src/increase-observability/integrate-observability/blackfire.md
Labels: quick task

#2822 Add last step in procedure on third-party TLS certificates
  docs/src/domains/cdn/managed-fastly.md
Labels: quick task

#2827 📝 Update heading to match text
  docs/src/environments/search-engine-visibility.md
Labels: quick task

#2816 🦺 Validate form submissions
  docs/index.js
  docs/layouts/partials/feedback/form.html
Labels: website

#2799 :memo: Clarify passwords with databases
  docs/layouts/shortcodes/databases-passwords.md
  docs/src/add-services/mysql/_index.md
  docs/src/add-services/postgresql.md
Labels: enhancement

#2830 📝 Clarify resources per environment
  docs/src/create-apps/app-reference.md
Labels: quick task

#2831 Update data-collection.md
  docs/src/security/data-collection.md
Labels: build-fork

#2826 📝 Small improvements for beginners
  docs/src/create-apps/app-reference.md
  docs/src/get-started/deploy/init.md
Labels: quick task

#2837 💚 Fix typo in workflow
  .github/workflows/build-from-fork.yaml
  .github/workflows/manage-environment.yaml
Labels: quick task

#2838 📝 Clarify source directory variable
  docs/src/development/variables/use-variables.md
Labels: quick task

#2839 Highlight Blackfire as recommended observability service
  docs/src/increase-observability/integrate-observability/_index.md
Labels: enhancement, quick task
