Repository platformsh/platformsh-docs, pull requests merged in 2023-10, with the labels that each got.

#3478 Fix broken link
  sites/platform/src/learn/overview/get-support.md
Labels: quick task, markdown/prose

#3479 Hide join the community section on Upsun
  sites/platform/src/_index.md
Labels: build-fork, markdown/prose

#3485 Fix redirect for resource configuration
  .platform/routes.yaml
Labels: quick task, markdown/prose

#3484 Align docs with actual internal policy
  sites/platform/src/environments/_index.md
Labels: quick task, markdown/prose

#3437 Upsun Express Guide v0.1
  sites/friday/config/_default/params.yaml
  sites/friday/src/get-started/express/_index.md
  sites/friday/src/get-started/express/add-database.md
  sites/friday/src/get-started/express/local.md
  sites/platform/config/_default/params.yaml
  themes/psh-docs/layouts/shortcodes/code-link.html
  themes/psh-docs/layouts/shortcodes/guides/requirements.md
  themes/psh-docs/layouts/shortcodes/guides/whitelabel/git_integration.md
  themes/psh-docs/layouts/shortcodes/vendor/url_doc.html
Labels: markdown/prose, upsun-mvp

#3482 Enhance/adds nextjs guide
  sites/friday/src/get-started/express/_index.md
  sites/friday/src/get-started/nextjs/_index.md
  sites/friday/src/get-started/nextjs/local.md
Labels: markdown/prose

#3487 Add coming soon message to Django and Strapi guides
  sites/friday/src/get-started/django/_index.md
  sites/friday/src/get-started/strapi/_index.md
Labels: quick task, markdown/prose

#3488 Add Golang 1.21 to registry
  shared/data/registry.json
Labels: quick task, markdown/prose

#3490 fix: update path on dead link
  sites/friday/src/get-started/laravel/deploy/blackfire.md
Labels: markdown/prose

#3483 Adds strapi guide
  sites/friday/src/get-started/strapi/_index.md
  sites/friday/src/get-started/strapi/local.md
Labels: markdown/prose

#3495 Update Go continuous profiling repo URL
  sites/friday/src/increase-observability/application-metrics/go.md
Labels: markdown/prose

#3496 Remove more of those go tracing -experimental
  sites/friday/src/increase-observability/application-metrics/go.md
Labels: markdown/prose

#3499 Update PHP access log snippet to mention php.access
  sites/platform/src/languages/php/fpm.md
Labels: markdown/prose

#3491 WIP: remove disk references for service definitions
  sites/friday/.yaml
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/influxdb.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/mysql/mysql-replication.md
  sites/platform/src/add-services/mysql/troubleshoot.md
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/guides/drupal9/redis.md
  themes/psh-docs/layouts/partials/examples/servicedefn.html
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: enhancement, markdown/prose

#3500 removing mention of .env file parsed
  sites/friday/src/get-started/express/_index.md
  sites/friday/src/get-started/express/add-database.md
  sites/friday/src/get-started/nextjs/_index.md
  sites/friday/src/get-started/strapi/_index.md
  themes/psh-docs/layouts/shortcodes/get-started/environment-note.md
Labels: markdown/prose

#3501 Fix 'you project' to 'your project'
  sites/friday/src/get-started/express/_index.md
  sites/friday/src/get-started/nextjs/_index.md
  sites/friday/src/get-started/strapi/_index.md
Labels: markdown/prose

#3494 Remove 10 CPU size from docs
  sites/friday/src/manage-resources/_index.md
Labels: enhancement, quick task, markdown/prose

#3502 First step of Node.js guides standardization
  sites/friday/src/get-started/express/_index.md
  sites/friday/src/get-started/nextjs/_index.md
  sites/friday/src/get-started/strapi/_index.md
Labels: markdown/prose

#3503 Apply doc styleguide to Flask guide
  sites/friday/src/get-started/flask/deploy/_index.md
  sites/friday/src/get-started/flask/deploy/configure.md
  sites/friday/src/get-started/flask/deploy/db-migrations.md
  sites/friday/src/get-started/flask/deploy/deploy.md
  sites/friday/src/get-started/flask/deploy/prepare.md
  sites/friday/src/get-started/flask/deploy/setup.md
  sites/friday/src/get-started/flask/deploy/tldr.md
  sites/friday/src/get-started/flask/local-development/_index.md
  sites/friday/src/get-started/flask/web-servers.md
Labels: enhancement, markdown/prose

#3507 Update routes.yaml to add missing /
  .platform/routes.yaml
Labels: markdown/prose

#3508 Fix Vale errors
  sites/friday/config/_default/params.yaml
  sites/platform/.yaml
  sites/platform/src/add-services/headless-chrome.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/domains/steps/_index.md
  sites/platform/src/glossary/_index.md
  sites/platform/src/languages/java/_index.md
  themes/psh-docs/layouts/shortcodes/vendor/psh_ref.html
Labels: enhancement

#3514 Update registry.json with Varnish 7.3
  shared/data/registry.json
Labels: markdown/prose

#3516 kafka: Vale issue
  contributing/styles/Vocab/Platform/accept.txt
  sites/platform/src/add-services/kafka.md
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: markdown/prose

#3518 Add info on env: vars and revert Vale changes
  sites/platform/src/add-services/kafka.md
  sites/platform/src/development/variables/_index.md
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: quick task, markdown/prose

#3504 Restore from a different environment
  sites/platform/src/environments/restore.md
Labels: markdown/prose

#3521 Java 18 & 19 available on DG3 and grid
  shared/data/registry.json
Labels: markdown/prose

#3506 Fix title
  sites/friday/src/get-started/flask/deploy/prepare.md
Labels: quick task, markdown/prose

#3476 Remove mention of legacy regions
  sites/platform/src/development/troubleshoot.md
Labels: quick task, markdown/prose

#3537 Add Redis 7.2 to registry
  shared/data/registry.json
Labels: quick task, markdown/prose

#3539 typo: java language page
  sites/platform/src/languages/java/_index.md
Labels: build-fork, markdown/prose

#3540 Update rabbitmq.md
  sites/platform/src/add-services/rabbitmq.md
Labels: markdown/prose

#3541 mongodb: update upgrade section
  sites/platform/src/add-services/mongodb.md
Labels: build-fork, markdown/prose

#3542 Add mongodump to accepted vocab
  contributing/styles/Vocab/Platform/accept.txt
Labels: quick task, markdown/prose

#3545 Adapt Paused Environment page after global roll out
  sites/platform/src/environments/_index.md
Labels: markdown/prose

#3552 Update registry.json (python, chrome-headless)
  shared/data/registry.json
Labels: markdown/prose

#3549 update permissions for webhook setup
  sites/platform/src/integrations/source/gitlab.md
Labels: build-fork, markdown/prose

#3543 Several SPF records
  sites/platform/src/development/email.md
Labels: build-fork, markdown/prose

#3510 Git 23
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/define-routes/_index.md
  sites/platform/src/development/variables/use-variables.md
  sites/platform/src/environments/_index.md
  sites/platform/src/environments/change-parent.md
  sites/platform/src/environments/deactivate-environment.md
  sites/platform/src/integrations/activity/_index.md
Labels: enhancement, markdown/prose
