Repository platformsh/platformsh-docs, pull requests merged in 2023-11, with the labels that each got.

#3558 Remove unnecessary closing parenthesis on App reference page
  sites/platform/src/create-apps/app-reference.md
Labels: markdown/prose

#3557 Fix varnish indentation
  sites/platform/src/add-services/varnish.md
Labels: markdown/prose

#3559 Updated templateRepo variable to render the correct Drupal template repository links.
  sites/platform/src/guides/drupal/deploy/_index.md
Labels: build-fork, markdown/prose

#3287 Document classification data via HTTP headers
  sites/platform/src/development/headers.md
Labels: enhancement, markdown/prose

#3566 Chore/3565 flask resources
  sites/friday/src/get-started/flask/deploy/configure.md
  sites/friday/src/get-started/flask/deploy/deploy.md
  sites/friday/src/get-started/flask/deploy/prepare.md
Labels: markdown/prose

#3567 Strapi: changing .environment replacement section by missing param
  sites/friday/src/get-started/strapi/_index.md
Labels: markdown/prose

#3568 Clarify network storage service naming restrictions
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: markdown/prose

#3564 Document default resources
  sites/friday/src/get-started/express/_index.md
  sites/friday/src/get-started/flask/deploy/configure.md
  sites/friday/src/get-started/flask/deploy/deploy.md
  sites/friday/src/get-started/flask/deploy/tldr.md
  sites/friday/src/get-started/laravel/deploy/_index.md
  sites/friday/src/get-started/laravel/deploy/deploy.md
  sites/friday/src/get-started/nextjs/_index.md
  sites/friday/src/get-started/strapi/_index.md
  sites/friday/src/manage-resources/_index.md
Labels: enhancement, markdown/prose

#3562 Update accept.txt file
  contributing/styles/Vocab/Platform/accept.txt
Labels: enhancement, quick task, markdown/prose

#3561 Flatten enable-integration shortcode
  sites/platform/src/integrations/source/bitbucket.md
  sites/platform/src/integrations/source/github.md
  sites/platform/src/integrations/source/gitlab.md
Labels: enhancement, WIP, markdown/prose

#3573 Fix Vale error on Bitbucket page
  sites/platform/src/integrations/source/bitbucket.md
Labels: markdown/prose

#3563 Add note about lack of Git LFS support
  sites/platform/src/learn/bestpractices/clean-repository.md
Labels: quick task, markdown/prose

#3556 [chore-3555] Removes section on cron jobs for laravel
  sites/platform/src/guides/laravel/deploy/scheduling.md
Labels: markdown/prose

#3583 Deprecate Elixir 1.12 & 1.13
  shared/data/registry.json
Labels: quick task, markdown/prose

#3584 Remove progressive rollout banner
  sites/platform/src/domains/steps/custom-domains-preview-environments.md
Labels: quick task, markdown/prose

#3585 remove archived java article
  sites/platform/src/languages/java/_index.md
Labels: markdown/prose

#3586 Fix typo in README
  README.md
Labels: markdown/prose

#3588 Remove Solr guide and link
  sites/platform/src/add-services/solr.md
  sites/platform/src/guides/drupal/solr.md
Labels: quick task, markdown/prose

#3591 Fix: remove irrelevant local dev section on Upsun doc
  sites/platform/src/development/local/_index.md
Labels: markdown/prose

#3594 rabbitmq: sequential upgrades need their own deployment
  sites/platform/src/add-services/rabbitmq.md
Labels: build-fork

#3595 Vendorize form partial for neg feedback path.
  themes/psh-docs/layouts/partials/feedback/form.html
Labels: markdown/prose

#3587 Add some Upsun docs for Symfony
  sites/friday/src/get-started/symfony/_index.md
  sites/friday/src/get-started/symfony/blackfire.md
  sites/friday/src/get-started/symfony/crons.md
  sites/friday/src/get-started/symfony/environment-variables.md
  sites/friday/src/get-started/symfony/faq.md
  sites/friday/src/get-started/symfony/get-started.md
  sites/friday/src/get-started/symfony/integration.md
  sites/friday/src/get-started/symfony/local.md
  sites/friday/src/get-started/symfony/workers.md
Labels: markdown/prose

#3604 add note about Memcached not being HA on DG2
  shared/data/registry.json
  sites/platform/src/add-services/memcached.md
Labels: build-fork

#3593 Explain Continuous Profiling concept and UI
  sites/friday/src/increase-observability/application-metrics/blackfire.md
  sites/friday/src/increase-observability/application-metrics/cont-prof.md
  sites/friday/src/increase-observability/application-metrics/go.md
  sites/friday/src/increase-observability/application-metrics/nodejs.md
  sites/friday/src/increase-observability/application-metrics/understanding.md
  sites/friday/static/images/observability/flame-graph-clicked.png
  sites/friday/static/images/observability/flame-graph-hover.png
  sites/friday/static/images/observability/flame-graph.png
  sites/friday/static/images/observability/sandwich-view.png
  sites/friday/static/images/observability/table-view.png
Labels: build-fork
