Repository platformsh/platformsh-docs, pull requests merged in 2023-02, with the labels that each got.

#2841 🔥 Remove outdate info for now
  docs/src/security/protective-block.md
Labels: quick task

#2845 Bump relay version
  docs/src/languages/php/redis.md
Labels: quick task, build-fork

#2847 Focus on Blackfire in observability section
  docs/src/increase-observability/integrate-observability/_index.md
  docs/src/increase-observability/integrate-observability/blackfire.md
  docs/src/increase-observability/integrate-observability/new-relic/_index.md
Labels: enhancement, quick task

#2843 :memo: Put SPF setup in foreground
  docs/src/development/email.md
Labels: quick task

#2835 📝 Rework source integration docs
  contributing/markup-format.md
  docs/layouts/shortcodes/source-integration/clone-commit.md
  docs/layouts/shortcodes/source-integration/enable-integration.html
  docs/layouts/shortcodes/source-integration/environment-status.md
  docs/layouts/shortcodes/source-integration/intro.md
  docs/layouts/shortcodes/source-integration/requirements.md
  docs/layouts/shortcodes/source-integration/source-of-truth.html
  docs/layouts/shortcodes/source-integration/url.md
  docs/layouts/shortcodes/source-integration/validate.md
  docs/src/integrations/overview.md
  docs/src/integrations/source/_index.md
  docs/src/integrations/source/bitbucket.md
  docs/src/integrations/source/github.md
  docs/src/integrations/source/gitlab.md
  docs/src/integrations/source/troubleshoot.md
Labels: docs rework

#2850 🔥 Remove outdated rules
  docs/src/security/waf.md
Labels: quick task

#2851 🐛 Fix location of network storage mount config
  docs/layouts/shortcodes/endpoint-description.md
Labels: quick task

#2842 Rework Authenticated Composer page
  docs/src/languages/php/composer-auth.md
Labels: docs rework

#2854 Language update
  docs/src/security/transparency/_index.md
Labels: build-fork

#2771 :memo: Rework Custom certificates
  docs/layouts/shortcodes/lets_encrypt_limitations.md
  docs/layouts/shortcodes/tls-introduction
  docs/src/define-routes/_index.md
  docs/src/define-routes/https.md
  docs/src/domains/cdn/_index.md
  docs/src/domains/cdn/cloudflare.md
  docs/src/domains/cdn/fastly.md
  docs/src/domains/cdn/managed-fastly.md
  docs/src/domains/steps/tls.md
  docs/src/domains/troubleshoot.md
  docs/src/other/glossary.md
Labels: docs rework

#2862 :bug: Fix codetab highlighting
  docs/src/domains/troubleshoot.md
Labels: quick task

#2863 📝 Clarify need to be GitHub admin
  docs/src/integrations/source/github.md
Labels: quick task

#2864 Add Go 1.20 to registry
  docs/data/registry.json
Labels: quick task

#2861 Remove Tools page and redirect to Get started
  .platform/routes.yaml
  docs/src/development/tools.md
Labels: docs rework

#2866 📝 Clarify scope of necessary admin permission
  docs/src/integrations/source/github.md
Labels: quick task

#2865 🐛 Fix example for custom PHP extension
  docs/src/languages/php/extensions.md
Labels: quick task

#2852 :memo: Distribute FAQ content to other parts of the docs
  docs/src/_index.md
  docs/src/administration/pricing/_index.md
  docs/src/administration/web/mfa.md
  docs/src/create-apps/app-reference.md
  docs/src/dedicated-gen-3/overview.md
  docs/src/development/faq.md
  docs/src/development/ssh/_index.md
  docs/src/environments/_index.md
  docs/src/other/glossary.md
  docs/src/overview/get-support.md
  docs/src/projects/delete-project.md
Labels: docs rework

#2872 📝 Increase findability of setting remote
  docs/src/tutorials/migrating.md
Labels: quick task

#2874 📝 Clarify role of templates
  docs/layouts/shortcodes/template-intro.md
  docs/src/guides/django/deploy.md
  docs/src/guides/nextjs/deploy.md
Labels: quick task

#2875 🐛 Fix index of replacement string
  docs/layouts/shortcodes/source-integration/enable-integration.html
Labels: quick task

#2876 🐛 Have example output match example input
  docs/src/define-routes/_index.md
Labels: quick task

#2869 :memo: Clarify how to enable Blackfire depending on plan
  docs/src/increase-observability/integrate-observability/blackfire.md
Labels: enhancement, quick task

#2877 Add overages pricing for Enterprise customers
  docs/src/administration/pricing/_index.md
Labels: build-fork

#2873 :memo: Rework Redis page
  docs/layouts/shortcodes/deprecated-versions.md
  docs/layouts/shortcodes/endpoint-description.md
  docs/src/add-services/redis.md
  docs/static/files/fetch/examples/java/redis
  docs/static/files/fetch/examples/nodejs/redis
  docs/static/files/fetch/examples/php/redis
  docs/static/files/fetch/examples/python/redis
Labels: docs rework

#2897 ✏️ Fix file name
  docs/src/create-apps/multi-app.md
Labels: quick task

#2891 📝 Rework RabbitMQ overview
  docs/src/add-services/rabbitmq.md
  docs/templates/service-reference.md
Labels: docs rework

#2888 :memo: Rework HTTPS page
  docs/layouts/shortcodes/lets_encrypt_limitations.md
  docs/layouts/shortcodes/tls-introduction
  docs/src/define-routes/_index.md
  docs/src/define-routes/cache.md
  docs/src/define-routes/https.md
  docs/src/define-routes/ssi.md
  docs/src/domains/cdn/_index.md
  docs/src/domains/steps/tls.md
  docs/src/languages/dotnet.md
Labels: docs rework

#2898 ⬆️ Update dependencies
  docs/package-lock.json
  docs/package.json
  docs/static/scripts/xss/package.json
  docs/themes/psh-docs/package.json
  search/.platform.app.yaml
  search/poetry.lock
  search/pyproject.toml
Labels: website

#2900 🐛 Fix errors in PHP extensions table
  docs/data/php_extensions.yaml
Labels: quick task

#2902 🐛Fix error in PHP extensions table
  docs/data/php_extensions.yaml
Labels: quick task

#2901 📝 Update Meilisearch version in ReadMe
  README.md
Labels: quick task

#2903 :memo: Add Xdebug as available on PHP 8.2
  docs/data/php_extensions.yaml
Labels: quick task

#2892 📝 Highlight need to use environment variable
  docs/layouts/shortcodes/relationship-ref-intro.md
  docs/layouts/shortcodes/service-values-change.md
  docs/src/add-services/_index.md
  docs/src/add-services/elasticsearch.md
  docs/src/add-services/headless-chrome.md
  docs/src/add-services/influxdb.md
  docs/src/add-services/kafka.md
  docs/src/add-services/memcached.md
  docs/src/add-services/mongodb.md
  docs/src/add-services/mysql/_index.md
  docs/src/add-services/opensearch.md
  docs/src/add-services/postgresql.md
  docs/src/add-services/rabbitmq.md
  docs/src/add-services/redis.md
  docs/src/add-services/solr.md
  docs/src/add-services/vault.md
  docs/templates/service-reference.md
Labels: quick task

#2905 📝 Show how to sanitize only once
  contributing/markup-format.md
  docs/layouts/shortcodes/sanitize-dbs/sanitize-manually.md
  docs/src/development/sanitize-db/mariadb.md
  docs/src/development/sanitize-db/postgresql.md
  styles/Vocab/Platform/accept.txt
Labels: quick task

#2904 📝 Clarify admin actions
  docs/src/administration/users.md
Labels: quick task

#2915 🚨 Process fixes
  .github/workflows/manage-environment.yaml
  docs/index.js
Labels: website

#2918 🐛 DDEV fixes
  docs/layouts/shortcodes/ddev/token.md
  docs/src/development/local/ddev.md
Labels: quick task

#2907 📝 Document scalability
  .platform/routes.yaml
  docs/src/dedicated-gen-2/architecture/scalability.md
  docs/src/environments/scalability.md
Labels: docs rework

#2926 📝 Add JavaScript as language name
  docs/data/registry.json
  docs/src/languages/nodejs/_index.md
Labels: quick task

#2929 Update node versions
  docs/src/languages/nodejs/node-version.md
Labels: build-fork

#2932 📝 Add clarity on responsibility for WAF and CDN
  docs/src/security/compliance-guidance.md
Labels: quick task

#2925 🎨 Style Python pages
  docs/src/languages/python/_index.md
  docs/src/languages/python/python-version.md
Labels: docs rework
