Repository platformsh/platformsh-docs, pull requests merged in 2023-09, with the labels that each got.

#3333 Document CLI support for runtime operations
  sites/platform/src/create-apps/runtime-operations.md
Labels: enhancement, markdown/prose

#3396 Add Node JS 20 support to registry
  shared/data/registry.json
Labels: quick task, markdown/prose

#3399 Postgres typo fix
  sites/platform/src/add-services/postgresql.md
Labels: markdown/prose

#3401 Add versioning shortcodes
  themes/psh-docs/layouts/shortcodes/version/only.html
  themes/psh-docs/layouts/shortcodes/version/specific.html
Labels: markdown/prose

#3406 Change banner title
  themes/psh-docs/layouts/shortcodes/premium-features/add-on.html
Labels: quick task, markdown/prose

#3408 Fix Edit button
  sites/friday/config/_default/params.yaml
  sites/platform/config/_default/params.yaml
  themes/psh-docs/layouts/partials/editpagebutton.html
Labels: enhancement, markdown/prose

#3414 Escape double quote from PR title
  .github/workflows/build-from-fork.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#3415 Premium banner for Elasticsearch
  sites/platform/src/add-services/elasticsearch.md
Labels: quick task

#3418 Revert PR3396
  shared/data/registry.json
Labels: quick task, markdown/prose

#3402 Match SO pricing terms
  sites/platform/src/create-apps/source-operations.md
  sites/platform/src/tutorials/dependency-updates.md
Labels: markdown/prose

#3421 Fix banners and keywords
  sites/platform/src/create-apps/source-operations.md
  sites/platform/src/integrations/source/_index.md
  sites/platform/src/integrations/source/bitbucket.md
  sites/platform/src/integrations/source/github.md
  sites/platform/src/integrations/source/gitlab.md
  sites/platform/src/integrations/source/troubleshoot.md
  sites/platform/src/tutorials/dependency-updates.md
Labels: enhancement, markdown/prose

#3422 fix: pgvector use vector extension name
  sites/platform/src/add-services/postgresql.md
Labels: markdown/prose

#3424 Add NodeJS 20 back to registry
  shared/data/registry.json
Labels: quick task, markdown/prose

#3423 Preview environments update
  sites/platform/.yaml
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/administration/pricing/_index.md
  sites/platform/src/administration/users.md
  sites/platform/src/administration/web/configure-environment.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/create-apps/hooks/vary-hooks-by-environment.md
  sites/platform/src/create-apps/source-operations.md
  sites/platform/src/dedicated-gen-2/architecture/development.md
  sites/platform/src/define-routes/_index.md
  sites/platform/src/development/email.md
  sites/platform/src/development/sanitize-db/_index.md
  sites/platform/src/development/sanitize-db/mariadb.md
  sites/platform/src/development/sanitize-db/postgresql-symfony.md
  sites/platform/src/development/sanitize-db/postgresql.md
  sites/platform/src/development/troubleshoot.md
  sites/platform/src/development/variables/set-variables.md
  sites/platform/src/domains/steps/_index.md
  sites/platform/src/domains/steps/custom-domains-preview-environments.md
  sites/platform/src/domains/steps/tls.md
  sites/platform/src/environments/_index.md
  sites/platform/src/environments/backup.md
  sites/platform/src/environments/http-access-control.md
  sites/platform/src/environments/search-engine-visibility.md
  sites/platform/src/get-started/add-data/branch.md
  sites/platform/src/get-started/add-data/merge.md
  sites/platform/src/guides/django/deploy/next-steps.md
  sites/platform/src/guides/gatsby/headless/drupal.md
  sites/platform/src/guides/symfony/environment-variables.md
  sites/platform/src/guides/symfony/faq.md
  sites/platform/src/integrations/activity/reference.md
  sites/platform/src/languages/nodejs/debug.md
  sites/platform/src/languages/python/_index.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/learn/overview/_index.md
  sites/platform/src/learn/overview/build-deploy.md
  sites/platform/src/other/glossary.md
  sites/platform/src/security/backups.md
  themes/psh-docs/layouts/shortcodes/guides/config-routes.md
  themes/psh-docs/layouts/shortcodes/guides/django/local-sanitize-example.md
  themes/psh-docs/layouts/shortcodes/guides/gatsby/headless-plansize.md
  themes/psh-docs/layouts/shortcodes/guides/initialize.html
  themes/psh-docs/layouts/shortcodes/guides/symfony/local-next-steps-end.md
  themes/psh-docs/layouts/shortcodes/sanitize-dbs/sanitize-intro.md
Labels: enhancement, markdown/prose

#3426 Revert "Preview environments update"
  sites/platform/.yaml
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/administration/pricing/_index.md
  sites/platform/src/administration/users.md
  sites/platform/src/administration/web/configure-environment.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/create-apps/hooks/vary-hooks-by-environment.md
  sites/platform/src/create-apps/source-operations.md
  sites/platform/src/dedicated-gen-2/architecture/development.md
  sites/platform/src/define-routes/_index.md
  sites/platform/src/development/email.md
  sites/platform/src/development/sanitize-db/_index.md
  sites/platform/src/development/sanitize-db/mariadb.md
  sites/platform/src/development/sanitize-db/postgresql-symfony.md
  sites/platform/src/development/sanitize-db/postgresql.md
  sites/platform/src/development/troubleshoot.md
  sites/platform/src/development/variables/set-variables.md
  sites/platform/src/domains/steps/_index.md
  sites/platform/src/domains/steps/custom-non-production-domains.md
  sites/platform/src/domains/steps/tls.md
  sites/platform/src/environments/_index.md
  sites/platform/src/environments/backup.md
  sites/platform/src/environments/http-access-control.md
  sites/platform/src/environments/search-engine-visibility.md
  sites/platform/src/get-started/add-data/branch.md
  sites/platform/src/get-started/add-data/merge.md
  sites/platform/src/guides/django/deploy/next-steps.md
  sites/platform/src/guides/gatsby/headless/drupal.md
  sites/platform/src/guides/symfony/environment-variables.md
  sites/platform/src/guides/symfony/faq.md
  sites/platform/src/integrations/activity/reference.md
  sites/platform/src/languages/nodejs/debug.md
  sites/platform/src/languages/python/_index.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/learn/overview/build-deploy.md
  sites/platform/src/other/glossary.md
  sites/platform/src/security/backups.md
  themes/psh-docs/layouts/shortcodes/guides/gatsby/headless-plansize.md
Labels: quick task, markdown/prose

#3429 removes extraneous `h` that was missed during vendorization
  sites/platform/src/guides/django/deploy/customize.md
  sites/platform/src/guides/wordpress/composer/_index.md
Labels: markdown/prose

#3425 Vendor: white-label context
  .platform/routes.yaml
  sites/friday/config/_default/config.yaml
  sites/friday/config/_default/params.yaml
  sites/friday/layouts/shortcodes/home.html
  sites/friday/static/images/favicon-32x32.png
  sites/friday/static/images/logo.svg
  sites/friday/static/images/logo_vertical.svg
  sites/platform/config/_default/params.yaml
  themes/psh-docs/layouts/partials/header/actions.html
  themes/psh-docs/layouts/partials/header/search.html
  themes/psh-docs/layouts/partials/page-content.html
  themes/psh-docs/layouts/shortcodes/home/links-github.html
  themes/psh-docs/static/css/vendor.css
Labels: markdown/prose

#3432 Missing white space in shortcodes/guides/deployment.md
  themes/psh-docs/layouts/shortcodes/guides/deployment.md
Labels: markdown/prose

#3433 Remove sections
  sites/friday/config/_default/config.yaml
  sites/friday/config/_default/params.yaml
  sites/platform/src/_index.md
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/administration/pricing/_index.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/create-apps/runtime-operations.md
  sites/platform/src/development/variables/use-variables.md
  sites/platform/src/domains/cdn/_index.md
  sites/platform/src/domains/cdn/fastly.md
  sites/platform/src/domains/steps/custom-non-production-domains.md
  sites/platform/src/environments/backup.md
  sites/platform/src/increase-observability/integrate-observability/blackfire.md
  sites/platform/src/increase-observability/metrics/_index.md
  sites/platform/src/languages/php/_index.md
  sites/platform/src/languages/php/extensions.md
  sites/platform/src/languages/php/swoole.md
  sites/platform/src/languages/python/_index.md
  sites/platform/src/learn/overview/philosophy.md
  sites/platform/src/learn/overview/structure.md
  sites/platform/src/other/glossary.md
  sites/platform/src/security/data-retention.md
  themes/psh-docs/layouts/shortcodes/frameworks.md
  themes/psh-docs/layouts/shortcodes/note.md
Labels: markdown/prose

#3392 Remove references to plans
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/headless-chrome.md
  sites/platform/src/add-services/influxdb.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/add-services/varnish.md
  sites/platform/src/add-services/vault.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/development/submodules.md
  sites/platform/src/domains/steps/_index.md
  sites/platform/src/domains/steps/custom-non-production-domains.md
  sites/platform/src/increase-observability/integrate-observability/blackfire.md
  sites/platform/src/increase-observability/integrate-observability/new-relic/_index.md
  sites/platform/src/increase-observability/logs/access-logs.md
  sites/platform/src/languages/dotnet.md
  sites/platform/src/languages/elixir.md
  sites/platform/src/languages/go.md
  sites/platform/src/languages/java/_index.md
  sites/platform/src/languages/lisp.md
  sites/platform/src/languages/nodejs/_index.md
  sites/platform/src/languages/php/_index.md
  sites/platform/src/languages/php/xdebug.md
  sites/platform/src/languages/python/_index.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/languages/rust.md
  sites/platform/src/learn/bestpractices/http-caching.md
  sites/platform/src/other/glossary.md
  themes/psh-docs/layouts/partials/page-content.html
  themes/psh-docs/layouts/shortcodes/image-versions.html
  themes/psh-docs/layouts/shortcodes/premium-features/tiered.html
Labels: WIP, markdown/prose

#3436 Fix: wordpress guide TOC header
  sites/platform/src/guides/wordpress/composer/migrate.md
Labels: markdown/prose

#3439 Fix typo in config-desc
  themes/psh-docs/layouts/shortcodes/guides/config-desc.md
Labels: markdown/prose

#3440 Fix: table of contents formatting (Ibexa)
  sites/platform/src/guides/ibexa/deploy.md
Labels: markdown/prose

#3430 Preview environments terminology update revival
  sites/platform/.yaml
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/administration/pricing/_index.md
  sites/platform/src/administration/users.md
  sites/platform/src/administration/web/configure-environment.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/create-apps/hooks/vary-hooks-by-environment.md
  sites/platform/src/create-apps/source-operations.md
  sites/platform/src/define-routes/_index.md
  sites/platform/src/development/email.md
  sites/platform/src/development/sanitize-db/_index.md
  sites/platform/src/development/sanitize-db/mariadb.md
  sites/platform/src/development/sanitize-db/postgresql-symfony.md
  sites/platform/src/development/sanitize-db/postgresql.md
  sites/platform/src/development/troubleshoot.md
  sites/platform/src/development/variables/set-variables.md
  sites/platform/src/domains/steps/_index.md
  sites/platform/src/domains/steps/custom-domains-preview-environments.md
  sites/platform/src/domains/steps/tls.md
  sites/platform/src/environments/_index.md
  sites/platform/src/environments/backup.md
  sites/platform/src/environments/http-access-control.md
  sites/platform/src/environments/search-engine-visibility.md
  sites/platform/src/get-started/add-data/branch.md
  sites/platform/src/get-started/add-data/merge.md
  sites/platform/src/guides/django/deploy/next-steps.md
  sites/platform/src/guides/gatsby/headless/drupal.md
  sites/platform/src/guides/symfony/environment-variables.md
  sites/platform/src/guides/symfony/faq.md
  sites/platform/src/increase-observability/metrics/_index.md
  sites/platform/src/increase-observability/metrics/dedicated.md
  sites/platform/src/integrations/activity/reference.md
  sites/platform/src/languages/nodejs/debug.md
  sites/platform/src/languages/python/_index.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/learn/overview/build-deploy.md
  sites/platform/src/other/glossary.md
  sites/platform/src/security/backups.md
  themes/psh-docs/layouts/shortcodes/guides/gatsby/headless-plansize.md
Labels: enhancement, markdown/prose

#3438 Better handle first-level sidebar item without subpages.
  .platform/routes.yaml
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/administration/web/configure-environment.md
  sites/platform/src/changelog/_index.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/dedicated-gen-2/overview/grid.md
  sites/platform/src/development/ssh/troubleshoot-ssh.md
  sites/platform/src/development/transfer-dedicated.md
  sites/platform/src/development/troubleshoot.md
  sites/platform/src/domains/cdn/cloudflare.md
  sites/platform/src/domains/cdn/managed-fastly.md
  sites/platform/src/domains/steps/_index.md
  sites/platform/src/domains/steps/custom-domains-preview-environments.md
  sites/platform/src/domains/steps/dns.md
  sites/platform/src/domains/troubleshoot.md
  sites/platform/src/environments/_index.md
  sites/platform/src/environments/backup.md
  sites/platform/src/environments/change-parent.md
  sites/platform/src/environments/deactivate-environment.md
  sites/platform/src/environments/http-access-control.md
  sites/platform/src/glossary/_index.md
  sites/platform/src/integrations/activity/reference.md
  sites/platform/src/other/_index.md
  themes/psh-docs/layouts/partials/sidebar/list.html
  themes/psh-docs/layouts/shortcodes/deprecated-versions.md
  themes/psh-docs/layouts/shortcodes/disk-space-mb.md
  themes/psh-docs/layouts/shortcodes/source-integration/environment-status.md
Labels: markdown/prose

#3444 Resubmit mvp link redirects.
  .platform/routes.yaml
Labels: markdown/prose

#3446 Add redirect for new custom domains for preview environments page URL
  .platform/routes.yaml
Labels: quick task, markdown/prose

#3387 Vendor: context for services
  shared/data/registry.json
  sites/friday/.yaml
  sites/friday/config/_default/params.yaml
  sites/platform/.yaml
  sites/platform/config/_default/params.yaml
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/headless-chrome.md
  sites/platform/src/add-services/influxdb.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/mysql/mysql-replication.md
  sites/platform/src/add-services/mysql/troubleshoot.md
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/add-services/varnish.md
  sites/platform/src/add-services/vault.md
  themes/psh-docs/layouts/_default/_markup/render-codeblock.html
  themes/psh-docs/layouts/partials/examples/config_links.html
  themes/psh-docs/layouts/partials/examples/latest.html
  themes/psh-docs/layouts/partials/examples/relationship.html
  themes/psh-docs/layouts/partials/examples/servicedefn.html
  themes/psh-docs/layouts/partials/snippet.html
  themes/psh-docs/layouts/shortcodes/codetabs.html
  themes/psh-docs/layouts/shortcodes/databases-passwords.md
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
  themes/psh-docs/layouts/shortcodes/relationship-ref-intro.md
  themes/psh-docs/layouts/shortcodes/service-values-change.md
  themes/psh-docs/layouts/shortcodes/snippet.html
  themes/psh-docs/layouts/shortcodes/v2connect2app.md
  themes/psh-docs/layouts/shortcodes/vendor/urlraw.html
  themes/psh-docs/layouts/shortcodes/version/specific.html
Labels: markdown/prose

#3447 Update Upsun docs favicon
  sites/friday/config/_default/params.yaml
  sites/friday/static/images/favicon-32x32.png
  sites/friday/static/images/favicon.ico
Labels: quick task, markdown/prose

#3450 Complete vendorization of routes section
  sites/platform/src/define-routes/_index.md
  sites/platform/src/define-routes/cache.md
  sites/platform/src/define-routes/https.md
  sites/platform/src/define-routes/proxy.md
  sites/platform/src/define-routes/redirects.md
  sites/platform/src/define-routes/ssi.md
Labels: enhancement, markdown/prose

#3456 Add Symfony question about database in the build hook
  sites/platform/src/guides/symfony/faq.md
Labels: markdown/prose

#3457 Complete vendorization of integrations section
  sites/friday/config/_default/params.yaml
  sites/platform/config/_default/params.yaml
  sites/platform/src/integrations/activity/_index.md
  sites/platform/src/integrations/activity/reference.md
  sites/platform/src/integrations/overview.md
  sites/platform/src/integrations/source/bitbucket.md
  themes/psh-docs/layouts/shortcodes/source-integration/enable-integration.html
  themes/psh-docs/layouts/shortcodes/vendor/alt-name.html
Labels: enhancement, markdown/prose

#3462 Clarify paused environments can be disabled
  sites/platform/.yaml
  sites/platform/src/environments/_index.md
Labels: quick task, markdown/prose

#3464 Update cryptography in /search
  search/pyproject.toml
Labels: quick task, markdown/prose

#3470 remove scalability doc page from upsun
  sites/friday/config/_default/config.yaml
Labels: markdown/prose

#3466 Vendorize Development section
  shared/data/regions.yaml
  sites/friday/.yaml
  sites/friday/config/_default/config.yaml
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/development/email.md
  sites/platform/src/development/file-transfer.md
  sites/platform/src/development/local/_index.md
  sites/platform/src/development/local/ddev.md
  sites/platform/src/development/local/docksal.md
  sites/platform/src/development/local/lando.md
  sites/platform/src/development/local/tethered.md
  sites/platform/src/development/private-repository.md
  sites/platform/src/development/sanitize-db/postgresql-symfony.md
  sites/platform/src/development/ssh/_index.md
  sites/platform/src/development/ssh/ssh-keys.md
  sites/platform/src/development/ssh/troubleshoot-ssh.md
  sites/platform/src/development/submodules.md
  sites/platform/src/development/troubleshoot.md
  sites/platform/src/development/variables/_index.md
  sites/platform/src/development/variables/set-variables.md
  sites/platform/src/development/variables/use-variables.md
  sites/platform/src/learn/tutorials/migrating.md
  themes/psh-docs/layouts/shortcodes/local-dev/local-dev-onboarding.sh
  themes/psh-docs/layouts/shortcodes/local-dev/next-steps-end.md
  themes/psh-docs/layouts/shortcodes/regions.html
  themes/psh-docs/layouts/shortcodes/sanitize-dbs/requirements.md
  themes/psh-docs/layouts/shortcodes/sanitize-dbs/sanitize-manually.md
Labels: WIP, markdown/prose

#3434 Document how to manage resources for MVP
  sites/friday/src/manage-resources/_index.md
  sites/friday/static/images/flexible-resources/apps-services-tree.png
  sites/friday/static/images/flexible-resources/check-container-profile.png
  sites/friday/static/images/flexible-resources/configure-flexible-resources.png
Labels: markdown/prose

#3472 Fix accidental mix-up between persistent and ephemeral Redis types
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: markdown/prose

#3475 Vendorize Learn section
  sites/friday/config/_default/params.yaml
  sites/platform/config/_default/params.yaml
  sites/platform/src/learn/bestpractices/oneormany.md
  sites/platform/src/learn/overview/_index.md
  sites/platform/src/learn/overview/build-deploy.md
  sites/platform/src/learn/overview/get-support.md
  sites/platform/src/learn/overview/philosophy.md
  sites/platform/src/learn/overview/structure.md
  sites/platform/src/learn/overview/yaml/what-is-yaml.md
  sites/platform/src/learn/tutorials/dependency-updates.md
  sites/platform/src/learn/tutorials/exporting.md
  sites/platform/src/learn/tutorials/migrating.md
  sites/platform/src/learn/tutorials/restrict-service-access.md
  themes/psh-docs/layouts/shortcodes/codetabs.html
  themes/psh-docs/layouts/shortcodes/vendor/prefix_cli.html
  themes/psh-docs/layouts/shortcodes/version/ifelse.html
Labels: enhancement, markdown/prose

#3468 Vendorize language pages
  sites/platform/src/languages/dotnet.md
  sites/platform/src/languages/elixir.md
  sites/platform/src/languages/go.md
  sites/platform/src/languages/java/_index.md
  sites/platform/src/languages/java/migration.md
  sites/platform/src/languages/java/tuning.md
  sites/platform/src/languages/lisp.md
  sites/platform/src/languages/nodejs/_index.md
  sites/platform/src/languages/nodejs/node-version.md
  sites/platform/src/languages/php/_index.md
  sites/platform/src/languages/php/extensions.md
  sites/platform/src/languages/php/fpm.md
  sites/platform/src/languages/php/redis.md
  sites/platform/src/languages/php/swoole.md
  sites/platform/src/languages/php/troubleshoot.md
  sites/platform/src/languages/php/tuning.md
  sites/platform/src/languages/php/xdebug.md
  sites/platform/src/languages/python/_index.md
  sites/platform/src/languages/python/dependencies.md
  sites/platform/src/languages/python/python-version.md
  sites/platform/src/languages/python/server.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/languages/rust.md
  themes/psh-docs/layouts/shortcodes/access-services.md
  themes/psh-docs/layouts/shortcodes/config-reader.md
  themes/psh-docs/layouts/shortcodes/language-specification.md
  themes/psh-docs/layouts/shortcodes/repolist.html
  themes/psh-docs/layouts/shortcodes/swoole.md
Labels: markdown/prose, upsun-mvp

#3460 Rework and improve the observability section for Upsun
  sites/friday/config/_default/config.yaml
  sites/friday/src/increase-observability/application-metrics/_index.md
  sites/friday/src/increase-observability/application-metrics/blackfire.md
  sites/friday/src/increase-observability/application-metrics/go.md
  sites/friday/src/increase-observability/application-metrics/nodejs.md
  sites/friday/src/increase-observability/metrics/http-metrics.md
  sites/friday/src/increase-observability/metrics/understand-metrics.md
  sites/platform/src/development/troubleshoot.md
  sites/platform/src/increase-observability/_index.md
  sites/platform/src/increase-observability/metrics/_index.md
  sites/platform/src/integrations/overview.md
  sites/platform/src/languages/php/troubleshoot.md
  sites/platform/src/languages/php/tuning.md
  sites/platform/src/learn/tutorials/migrating.md
Labels: build-fork, markdown/prose, upsun-mvp

#3454 Adds a Flask Guide, attempt 2
  sites/friday/src/get-started/flask/_index.md
  sites/friday/src/get-started/flask/deploy/_index.md
  sites/friday/src/get-started/flask/deploy/configure.md
  sites/friday/src/get-started/flask/deploy/db-migrations.md
  sites/friday/src/get-started/flask/deploy/deploy.md
  sites/friday/src/get-started/flask/deploy/prepare.md
  sites/friday/src/get-started/flask/deploy/setup.md
  sites/friday/src/get-started/flask/deploy/tldr.md
  sites/friday/src/get-started/flask/local-development/_index.md
  sites/friday/src/get-started/flask/web-servers.md
  themes/psh-docs/layouts/shortcodes/guides/requirements.md
Labels: markdown/prose, upsun-mvp

#3351 White-label migration guide
  README.md
  sites/friday/config/_default/config.yaml
  sites/friday/src/learn/tutorials/migrating/_index.md
  sites/friday/src/learn/tutorials/migrating/from-psh.md
  sites/platform/src/learn/tutorials/exporting.md
  sites/platform/src/projects/region-migration.md
  themes/psh-docs/layouts/shortcodes/source-integration/validate.md
Labels: enhancement, WIP, markdown/prose, upsun-mvp
