Repository platformsh/platformsh-docs, pull requests merged in 2023-05, with the labels that each got.

#3118 [Enhancement] Use build cache
  docs/.platform.app.yaml
  docs/build_docs.sh
  docs/deploy.sh
  search/.platform.app.yaml
  search/build.sh
Labels: enhancement

#3126 Update SSL certificate error message
  docs/src/domains/troubleshoot.md
Labels: quick task

#3129 :memo: Add New Relic as available for PHP 8.2
  docs/data/php_extensions.yaml
Labels: quick task

#3077 php/xdebug: notice limitations on custom commands
  docs/src/languages/php/xdebug.md
Labels: quick task, build-fork

#3125 Hotfix: adds the psh cli env var for the fail workflow step
  .github/workflows/get-pr-info.yaml
Labels: bug

#3134 Update redirects.md to indicate that query-string based redirect are unsupported.
  docs/src/define-routes/redirects.md
Labels: build-fork

#3135 Add Zendesk Search validation
  docs/themes/psh-docs/layouts/partials/head/head.html
Labels: build-fork

#3141 Absolute URLs in sitemap
  docs/config/_default/config.yaml
  docs/data/templates.yaml
  docs/static/files/fetch/examples/relationships/vault-kms
Labels: enhancement

#3133 :memo: Add note about versions to service and language pages
  docs/layouts/shortcodes/major-minor-versions-note.md
  docs/src/add-services/_index.md
  docs/src/add-services/elasticsearch.md
  docs/src/add-services/headless-chrome.md
  docs/src/add-services/influxdb.md
  docs/src/add-services/kafka.md
  docs/src/add-services/memcached.md
  docs/src/add-services/mongodb.md
  docs/src/add-services/mysql/_index.md
  docs/src/add-services/network-storage.md
  docs/src/add-services/postgresql.md
  docs/src/add-services/rabbitmq.md
  docs/src/add-services/redis.md
  docs/src/add-services/solr.md
  docs/src/add-services/varnish.md
  docs/src/add-services/vault.md
  docs/src/languages/dotnet.md
  docs/src/languages/elixir.md
  docs/src/languages/go.md
  docs/src/languages/java/_index.md
  docs/src/languages/lisp.md
  docs/src/languages/nodejs/_index.md
  docs/src/languages/php/_index.md
  docs/src/languages/python/_index.md
  docs/src/languages/ruby.md
  docs/src/languages/rust.md
Labels: enhancement

#3153 :memo: Update certificate renewal section
  docs/src/define-routes/https.md
Labels: enhancement

#3154 :memo: Remove sv restart command
  docs/src/languages/php/tuning.md
Labels: quick task

#3139 Use opensearch 2 as default for docs
  docs/src/add-services/opensearch.md
Labels: build-fork

#3170 Update check-labels.yaml
  .github/workflows/check-labels.yaml
Labels: build-fork

#3173 changes token back to WORKFLOW_TOKEN
  .github/workflows/check-labels.yaml
Labels: markdown/prose

#3166 :memo: Add section about automated testing
  docs/src/create-apps/app-reference.md
Labels: enhancement

#3167 :memo: Update Opensearch latest version available
  docs/data/registry.json
  docs/src/add-services/opensearch.md
Labels: quick task

#3179 Revert SSH/redeploy instructions.
  docs/src/administration/users.md
Labels: markdown/prose

#3180 [Chore] debug
  .github/workflows/dbgtkn.yaml
Labels: markdown/prose

#3081 Note how to connect to RabbitMQ UI on DG2 clusters
  docs/src/add-services/rabbitmq.md
Labels: build-fork, markdown/prose

#3043 :memo: Document Fastly Next-Gen WAF
  docs/src/security/_index.md
  docs/src/security/compliance-guidance.md
  docs/src/security/web-application-firewall/_index.md
  docs/src/security/web-application-firewall/fastly-waf.md
  docs/src/security/web-application-firewall/waf.md
Labels: enhancement

#3182 RabbitMQ deprecated fix
  docs/src/add-services/rabbitmq.md
Labels: quick task, bug, markdown/prose

#3150 :memo: Update custom non-production domains page
  docs/src/domains/steps/custom-non-production-domains.md
Labels: enhancement

#3158 :memo: Add section on Strict_transport_security and HSTS requirements
  docs/src/create-apps/web/custom-headers.md
Labels: enhancement

#3156 :memo: Update backup and restore information
  docs/src/environments/backup.md
  docs/src/environments/restore.md
Labels: enhancement

#3172 :memo: Update source integration pages
  docs/layouts/shortcodes/source-integration/enable-integration.html
  docs/layouts/shortcodes/source-integration/validate.md
Labels: enhancement

#3181 Add missing start command to Redis examples
  docs/src/add-services/redis.md
  docs/src/create-apps/app-reference.md
Labels: quick task

#3188 📝 Add keywords for the trust center
  docs/src/security/_index.md
Labels: quick task, markdown/prose

#3189 Erratum source integrations
  docs/layouts/shortcodes/source-integration/enable-integration.html
  docs/layouts/shortcodes/source-integration/validate.md
Labels: enhancement

#3195 📝 Update regions.md
  docs/src/development/regions.md
Labels: markdown/prose

#2968 Document runtime operations
  docs/layouts/shortcodes/guides/gatsby/headless-gatsby.md
  docs/src/create-apps/runtime-operations.md
  docs/src/create-apps/source-operations.md
Labels: markdown/prose
