Repository platformsh/platformsh-docs, pull requests merged in 2023-03, with the labels that each got.

#2933 📝 Rework local tethered development
  docs/layouts/shortcodes/guides/django/local-assumptions.md
  docs/layouts/shortcodes/guides/django/local-sanitize-example.md
  docs/layouts/shortcodes/guides/local-requirements.md
  docs/layouts/shortcodes/local-dev/next-steps-end.md
  docs/layouts/shortcodes/local-dev/next-steps-start.md
  docs/layouts/shortcodes/tethered-dev/steps-end.md
  docs/layouts/shortcodes/tethered-dev/steps-start.md
  docs/snippets/local-dev-onboarding.sh
  docs/src/development/local/tethered.md
  docs/src/guides/django/local/ddev.md
  docs/src/guides/django/local/tethered.md
Labels: docs rework

#2936 📝 Add link to support ticket
  docs/src/create-apps/flexible-resources.md
Labels: quick task

#2938 ✨ Add beta flag banner
  contributing/markup-format.md
  docs/layouts/shortcodes/premium-features/add-on.html
  docs/src/environments/scalability.md
  docs/src/guides/django/deploy/_index.md
  docs/src/increase-observability/integrate-observability/blackfire.md
  docs/src/increase-observability/metrics/_index.md
  docs/themes/psh-docs/layouts/partials/beta-flag/banner.html
  docs/themes/psh-docs/layouts/partials/beta-flag/body.md
  docs/themes/psh-docs/layouts/partials/observability-suite/banner.html
  docs/themes/psh-docs/layouts/partials/observability-suite/body.html
  docs/themes/psh-docs/layouts/partials/observability-suite/body.md
  docs/themes/psh-docs/layouts/partials/page-content.html
  docs/themes/psh-docs/layouts/partials/premium-features/banner.html
  docs/themes/psh-docs/layouts/shortcodes/partial.html
Labels: website

#2946 :memo: Add command to restart PHP processes in app container
  docs/src/development/troubleshoot.md
  docs/src/languages/php/troubleshoot.md
Labels: enhancement, quick task

#2934 💄 Fix print styles
  docs/layouts/shortcodes/tranparency-reports/download.html
  docs/static/styles/print.css
  docs/static/styles/print/transparency-reports.css
  docs/themes/psh-docs/layouts/_default/baseof.html
  docs/themes/psh-docs/layouts/partials/editpagebutton.html
  docs/themes/psh-docs/layouts/partials/head/css.html
  docs/themes/psh-docs/layouts/partials/header/header.html
  docs/themes/psh-docs/layouts/partials/page-content.html
  docs/themes/psh-docs/layouts/partials/sidebar/sidebar.html
Labels: website

#2939 Fixing the number of requests on the Overages prices
  docs/src/administration/pricing/_index.md
Labels: build-fork

#2948 :memo: Add introduction and link to Trust Center
  docs/src/security/_index.md
Labels: enhancement, quick task

#2956 Include type and name attributes for static sites
  docs/src/create-apps/web/static.md
Labels: quick task

#2949 Fix getenv() typo on link
  docs/src/development/variables/use-variables.md
Labels: quick task

#2954 :bug: Fix broken example configuration
  docs/layouts/partials/examples/config_links.html
Labels: quick task

#2935 Blackfire page
  docs/src/increase-observability/integrate-observability/blackfire.md
Labels: docs rework

#2958 📝 Add region geographical location
  docs/src/development/regions.md
Labels: enhancement

#2824 📝 Updated user management
  docs/src/administration/organizations.md
  docs/src/administration/pricing/_index.md
  docs/src/administration/users.md
  docs/src/create-apps/troubleshoot-disks.md
  docs/src/domains/steps/_index.md
  docs/src/integrations/notifications.md
  docs/src/projects/delete-project.md
Labels: docs rework

#2960 update limits
  docs/src/security/pen-test.md
Labels: quick task, build-fork

#2970 fix number of included requests
  docs/src/administration/pricing/_index.md
Labels: build-fork

#2844 Move appropriate content from DG2 to DG3 section
  .platform/routes.yaml
  docs/layouts/shortcodes/multi-app-intro.md
  docs/src/administration/pricing/_index.md
  docs/src/create-apps/multi-app.md
  docs/src/dedicated-gen-2/architecture/_index.md
  docs/src/dedicated-gen-2/architecture/options.md
  docs/src/dedicated-gen-2/overview/grid.md
  docs/src/dedicated-gen-2/overview/monitoring.md
  docs/src/dedicated-gen-2/overview/onboarding.md
  docs/src/dedicated-gen-2/overview/security.md
  docs/src/dedicated-gen-2/overview/updates-upgrades.md
  docs/src/dedicated-gen-3/_index.md
  docs/src/dedicated-gen-3/monitoring.md
  docs/src/dedicated-gen-3/options.md
  docs/src/dedicated-gen-3/overview.md
  docs/src/dedicated-gen-3/security.md
  docs/src/development/variables/use-variables.md
  docs/src/environments/backup.md
  docs/src/increase-observability/metrics/_index.md
  docs/src/other/glossary.md
  docs/src/overview/structure.md
  docs/static/images/dedicated/incident-monitoring-graph.svg
  docs/static/images/dedicated/urgent-ticket-flow.svg
  package-lock.json
Labels: enhancement

#2961 :memo: Remove Drupal 8 references
  docs/src/development/deploy-button.md
  docs/src/guides/drupal9/deploy/_index.md
  docs/src/guides/drupal9/multi-site.md
  docs/src/tutorials/third-party.md
Labels: enhancement

#2975 Update static site index
  docs/src/create-apps/web/static.md
Labels: quick task

#2980 Update DoP button repo variable
  docs/layouts/shortcodes/guides/starting-point.md
Labels: quick task

#2978 📝 Fix style
  docs/src/security/data-deletion.md
Labels: quick task

#2981 Update users.md
  docs/src/administration/users.md
Labels: build-fork

#2974 :memo: Add 2022 transparency report
  docs/data/templates.yaml
  docs/layouts/shortcodes/tranparency-reports/tables/2022/abuse.html
  docs/layouts/shortcodes/tranparency-reports/tables/2022/eu-requests.html
  docs/layouts/shortcodes/tranparency-reports/tables/2022/noneu-requests.html
  docs/layouts/shortcodes/tranparency-reports/tables/2022/usa-requests.html
  docs/src/security/transparency/2022_report.md
  docs/static/files/reports/transparency-abuse/2022_platformsh_transparency_report.pdf
  package-lock.json
  package.json
Labels: s&c

#2985 Update Poetry default configuration.
  docs/src/languages/python/dependencies.md
Labels: quick task, python

#2984 :memo: Add Elixir 1.14 to registry
  docs/data/registry.json
Labels: quick task

#2989 :bug: Add missing number in table
  docs/layouts/shortcodes/tranparency-reports/tables/2022/abuse.html
Labels: quick task

#2941 :memo: Document custom domains on non-production environments
  docs/src/domains/steps/custom-non-production-domains.md
  docs/src/domains/steps/tls.md
  docs/static/images/custom-domains/custom-domains-non-prod.png
  docs/themes/psh-docs/layouts/partials/beta-flag/body.md
Labels: enhancement

#2995 :bug: Remove extra platform instance in command
  docs/src/increase-observability/logs/forward-logs.md
Labels: enhancement, quick task

#3005 Blackfire org activation
  docs/src/increase-observability/integrate-observability/blackfire.md
Labels: enhancement, quick task

#3001 🐛 Fix variables
  docs/src/create-apps/source-operations.md
  docs/src/development/regions.md
Labels: quick task

#2986 :memo: Add information about PHP-CLI default settings
  docs/src/languages/php/_index.md
Labels: quick task

#3002 :memo: Add information about Vault KMS usage
  docs/src/add-services/vault.md
Labels: quick task

#3004 :memo: Update the registry with correct endpoint name
  docs/data/registry.json
Labels: quick task

#3007 :memo: Make DG2 note more obvious
  docs/src/domains/steps/custom-non-production-domains.md
Labels: quick task

#2996 Update custom-non-production-domains.md
  docs/src/domains/steps/custom-non-production-domains.md
Labels: enhancement, build-fork

#3003 :memo: Add redirects for broken backlinks
  .platform/routes.yaml
Labels: website

#3016 Generalized banners
  docs/data/banners.yaml
  docs/layouts/shortcodes/premium-features/add-on.html
  docs/src/administration/sso.md
  docs/src/create-apps/source-operations.md
  docs/src/domains/cdn/managed-fastly.md
  docs/src/domains/steps/custom-non-production-domains.md
  docs/src/guides/django/deploy/_index.md
  docs/src/increase-observability/logs/forward-logs.md
  docs/src/security/waf.md
  docs/themes/psh-docs/layouts/partials/banners/banner.html
  docs/themes/psh-docs/layouts/partials/page-content.html
Labels: website

#2944 :memo: Add page on automated dependency updates
  docs/src/create-apps/source-operations.md
  docs/src/guides/wordpress/composer/migrate.md
  docs/src/tutorials/dependency-updates.md
Labels: enhancement

#3029 :sparkles: Add search-related keywords
  contributing/markup-format.md
Labels: quick task

#3020 Add examples of OpenID Connect providers
  docs/src/administration/sso.md
Labels: enhancement, build-fork

#3021 :bug: Add slash to 2 redirects
  .platform/routes.yaml
Labels: quick task

#3027 Add pentests to accepted terms
  styles/Vocab/Platform/accept.txt
Labels: quick task

#3012 :memo: Add page on CDN log forwarding
  docs/src/increase-observability/logs/forward-fastly-logs.md
  docs/src/increase-observability/logs/forward-logs.md
Labels: enhancement

#3028 :memo: Document centralized user permissions
  docs/src/administration/users.md
Labels: enhancement

#3031 Replace `mix run` by `mix phx.server`
  docs/src/languages/elixir.md
Labels: quick task, build-fork

#3025 Update users.md
  docs/src/administration/users.md
Labels: build-fork

#3032 Add tips about Gemfile ruby constraint
  docs/src/languages/ruby.md
Labels: build-fork

#3033 :clipboard: Correct Bitbucket name
  docs/layouts/shortcodes/source-integration/requirements.md
Labels: build-fork

#2987 Enable sectionBefore: grouping Stacks and services
  docs/src/add-services/elasticsearch.md
  docs/src/add-services/headless-chrome.md
  docs/src/add-services/influxdb.md
  docs/src/add-services/kafka.md
  docs/src/add-services/memcached.md
  docs/src/add-services/mongodb.md
  docs/src/add-services/mysql/_index.md
  docs/src/add-services/network-storage.md
  docs/src/add-services/opensearch.md
  docs/src/add-services/postgresql.md
  docs/src/add-services/redis.md
  docs/src/add-services/solr.md
  docs/src/add-services/varnish.md
  docs/src/add-services/vault.md
  docs/src/guides/django/_index.md
  docs/src/guides/drupal9/_index.md
  docs/src/guides/gatsby/_index.md
  docs/src/guides/hibernate/_index.md
  docs/src/guides/ibexa/_index.md
  docs/src/guides/jakarta/_index.md
  docs/src/guides/laravel/_index.md
  docs/src/guides/micronaut/_index.md
  docs/src/guides/nextjs/_index.md
  docs/src/guides/quarkus/_index.md
  docs/src/guides/spring/_index.md
  docs/src/guides/strapi/_index.md
  docs/src/guides/symfony/_index.md
  docs/src/guides/typo3/_index.md
  docs/src/guides/wordpress/_index.md
  docs/themes/psh-docs/layouts/partials/sidebar/list.html
Labels: enhancement, WIP, docs rework

#3040 Update dependency-updates.md
  docs/src/tutorials/dependency-updates.md
Labels: build-fork
