Repository platformsh/platformsh-docs, pull requests merged in 2023-12, with the labels that each got.

#3610 Mention multi-instance metrics filtering
  sites/friday/src/increase-observability/metrics/understand-metrics.md
  sites/friday/static/images/observability/filtering-upsun.png
  sites/platform/src/increase-observability/metrics/grid.md
Labels: build-fork

#3617 Revert "Display log forwarding to upsun (#3612)"
  sites/friday/config/_default/config.yaml
  sites/platform/src/increase-observability/logs/forward-logs.md
  themes/psh-docs/layouts/partials/page-content.html
Labels: build-fork

#3574 Add port option to HTTP log fowarding URL
  sites/platform/src/increase-observability/logs/forward-logs.md
Labels: markdown/prose

#3575 Git 24 push options
  sites/platform/src/environments/_index.md
Labels: markdown/prose

#3576 Relationships b/w backups and env deletion.
  sites/platform/src/security/data-retention.md
Labels: markdown/prose

#3577 Add clarification to 'include' in yaml usage.
  sites/platform/src/learn/overview/yaml/platform-yaml-tags.md
Labels: markdown/prose

#3608 Make backup schedule more explicit
  sites/platform/src/environments/backup.md
Labels: quick task

#3619 [FIX] Guides template description
  themes/psh-docs/layouts/shortcodes/guides/starting-point.md
Labels: quick task, markdown/prose

#3590 Document simplified relationships
  shared/data/registry.json
  sites/friday/.yaml
  sites/friday/src/get-started/express/add-database.md
  sites/friday/src/get-started/laravel/deploy/configure.md
  sites/friday/src/get-started/symfony/environment-variables.md
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/headless-chrome.md
  sites/platform/src/add-services/influxdb.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/mysql/mysql-replication.md
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/add-services/varnish.md
  sites/platform/src/create-apps/_index.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/create-apps/multi-app/project-structure.md
  sites/platform/src/create-apps/multi-app/relationships.md
  sites/platform/src/create-apps/upgrading.md
  sites/platform/src/create-apps/workers.md
  sites/platform/src/guides/drupal/redis.md
  sites/platform/src/languages/elixir.md
  sites/platform/src/languages/java/migration.md
  sites/platform/src/languages/lisp.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/learn/bestpractices/oneormany.md
  sites/platform/src/learn/tutorials/restrict-service-access.md
  themes/psh-docs/layouts/partials/examples/relationship.html
  themes/psh-docs/layouts/partials/examples/servicedefn.html
  themes/psh-docs/layouts/partials/snippet.html
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
  themes/psh-docs/layouts/shortcodes/v2connect2app.md
Labels: enhancement, markdown/prose

#3607 Update doc on mounts
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/environments/_index.md
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: enhancement

#3622 Fix PostgreSQL and MongoDB downgrade warning block
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/postgresql.md
Labels: build-fork

#3579 Update doc on resources
  .platform/routes.yaml
  sites/friday/src/manage-resources/_index.md
  sites/friday/src/manage-resources/adjust-resources.md
  sites/friday/src/manage-resources/resource-billing.md
  sites/friday/src/manage-resources/resource-init.md
Labels: enhancement, markdown/prose, Upsun

#3621 Rss rendering - fix company name subs.
  themes/psh-docs/layouts/_default/rss.xml
Labels: quick task

#3618 CDNs in 2024 use mTLS
  sites/platform/src/domains/cdn/_index.md
Labels: enhancement, build-fork

#3627 Update resource docs with GUI changes
  sites/friday/src/manage-resources/adjust-resources.md
  sites/friday/static/images/flexible-resources/configure-button-project-card.png
Labels: enhancement

#3631 Update framework guides with new resources behaviour
  sites/friday/src/get-started/express/_index.md
  sites/friday/src/get-started/flask/deploy/deploy.md
  sites/friday/src/get-started/laravel/deploy/deploy.md
  sites/friday/src/get-started/nextjs/_index.md
  sites/friday/src/get-started/strapi/_index.md
Labels: enhancement

#3632 Add PostgreSQL 16 support and deprecate 11
  shared/data/registry.json
Labels: quick task

#3633 Fix error on Websocket route config and add context
  sites/platform/src/define-routes/_index.md
Labels: quick task

#3638 Render title passed to dataLayer.
  sites/platform/.yaml
  sites/platform/config/_default/params.yaml
  sites/platform/local_docs.sh
  sites/platform/static/scripts/xss/src/components/SuggestionsPrimary.js
  themes/psh-docs/layouts/_default/baseof.html
Labels: enhancement

#3640 Add amqp support for PHP 8.3
  shared/data/php_extensions.yaml
Labels: quick task

#3641 Rewrite local mounts parts
  shared/data/registry.json
  sites/friday/config/_default/config.yaml
  sites/friday/src/add-services/network-storage.md
  sites/friday/src/create-apps/workers.md
  sites/friday/src/get-started/laravel/deploy/configure.md
  sites/friday/src/learn/tutorials/migrating/from-psh.md
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/create-apps/_index.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/create-apps/hooks/_index.md
  sites/platform/src/create-apps/multi-app/project-structure.md
  sites/platform/src/create-apps/troubleshoot-mounts.md
  sites/platform/src/create-apps/workers.md
  sites/platform/src/development/file-transfer.md
  sites/platform/src/development/variables/use-variables.md
Labels: enhancement, markdown/prose

#3656 Update MariaDB support in registry
  shared/data/registry.json
Labels: quick task, markdown/prose

#3660 Remove last `disk` key and update resources section in Express guide
  sites/friday/src/add-services/network-storage.md
  sites/friday/src/get-started/express/add-database.md
Labels: enhancement, markdown/prose

#3659 Bug/debug search prod
  .platform/applications.yaml
  search/post_deploy.sh
  sites/friday/marker.sh
  sites/platform/marker.sh
Labels: markdown/prose

#3654 Reapply "Display log forwarding to upsun (#3612)"
  sites/friday/config/_default/config.yaml
  sites/platform/src/increase-observability/logs/forward-logs.md
  themes/psh-docs/layouts/partials/page-content.html
Labels: enhancement, build-fork, markdown/prose

#3661 Hotfix/search
  .platform/applications.yaml
  search/.platform.app.yaml
  search/post_deploy.sh
Labels: markdown/prose

#3658 Link to Cloudflare mTLS community guide
  sites/platform/src/domains/cdn/cloudflare.md
Labels: markdown/prose

#3662 Remove info about disabling paused environments
  sites/platform/src/environments/_index.md
Labels: quick task, markdown/prose

#3645 Chore/3644 keyword config app page
  sites/platform/src/create-apps/_index.md
  themes/psh-docs/layouts/partials/meilindex/page.html
Labels: enhancement, markdown/prose

#3663 Address simplified relationship availability with note
  sites/platform/src/create-apps/app-reference.md
Labels: markdown/prose
