Repository platformsh/platformsh-docs, pull requests merged in 2023-07, with the labels that each got.

#3252 Update accept.txt
  styles/Vocab/Platform/accept.txt
Labels: quick task, markdown/prose

#3199 WIP: Rewrite with more general/appropriate terminology
  docs/src/bestpractices/oneormany.md
Labels: build-fork, markdown/prose

#3258 adds support.blackfire.io to list of ignore URLs in linkchecker
  .github/workflows/scheduled-check-links.yaml
Labels: gh-workflows, markdown/prose

#3251 Remove broken link
  docs/src/development/ssh/ssh-keys.md
Labels: quick task

#3190 Deploy keys and machine users
  docs/src/development/submodules.md
Labels: enhancement, build-fork

#3204 📝 Move deployment philosophy documentation to general build & deploy overview
  docs/src/dedicated-gen-2/architecture/deploying.md
  docs/src/overview/build-deploy.md
Labels: enhancement, build-fork

#3208 Fix WordPress Composer procedure
  docs/src/guides/wordpress/composer/migrate.md
Labels: enhancement

#3220 Explain the effect of removing a database entry for Postgresql and Mariadb
  docs/src/add-services/mysql/_index.md
  docs/src/add-services/postgresql.md
Labels: enhancement, build-fork

#3226 Remove instructions about adding security reports
  CONTRIBUTING.md
Labels: quick task

#3232 Add clarity to subdomains section
  docs/src/domains/steps/subdomains.md
Labels: quick task

#3236 Add link to WP community post
  docs/src/guides/wordpress/composer/_index.md
Labels: quick task

#3234 Document CPU limit for PHP-FPM workers
  docs/src/languages/php/fpm.md
Labels: enhancement

#3256 Add Nodeping-related CDN configuration
  docs/src/dedicated-gen-3/monitoring.md
  docs/src/domains/cdn/_index.md
Labels: enhancement, markdown/prose

#3259 Update Certificate troubleshooting
  docs/src/domains/troubleshoot.md
Labels: quick task, markdown/prose

#3260 Add note about AUTO and activity logs
  docs/src/add-services/_index.md
Labels: markdown/prose

#3261 Clarify number of automated backups per schedule
  docs/src/environments/backup.md
Labels: quick task, markdown/prose

#3267 new(php): gnupg extension availble to 8.2 on grid
  docs/data/php_extensions.yaml
Labels: quick task, build-fork

#3268 Update flexible-resources.md
  docs/src/create-apps/flexible-resources.md
Labels: markdown/prose

#3263 Add Blackfire log forwarding
  docs/src/increase-observability/logs/forward-logs.md
Labels: quick task

#3273 Restore XS size for flexible resources
  docs/src/create-apps/flexible-resources.md
Labels: quick task, markdown/prose

#3275 Remove wrong default values on flexible resources page
  docs/src/create-apps/flexible-resources.md
Labels: quick task, markdown/prose

#3286 Fix broken link
  docs/src/languages/java/frameworks.md
Labels: quick task, markdown/prose

#3290 Remove platformify recommendations
  docs/src/guides/laravel/deploy/configure.md
Labels: markdown/prose

#3291 Add NodePing to accept.txt
  styles/Vocab/Platform/accept.txt
Labels: quick task, markdown/prose

#3293 Fix Vale errors
  docs/src/bestpractices/oneormany.md
  docs/src/domains/cdn/_index.md
Labels: quick task

#3297 Fix WP typo
  docs/src/guides/wordpress/composer/_index.md
Labels: quick task

#3279 Add DG2 support to OpenJDK page
  docs/data/registry.json
Labels: quick task, markdown/prose

#3262 Add section about missing default environment URL
  docs/src/administration/web/configure-environment.md
  docs/static/images/management-console/env-url.png
Labels: enhancement, markdown/prose

#3266 Add Rabbitmq 3.12 support on Grid/DG3
  docs/data/registry.json
Labels: quick task, markdown/prose

#3270 Add Laravel and Symfony cron examples
  docs/src/create-apps/app-reference.md
Labels: quick task, markdown/prose

#3277 Update websocket configuration examples
  docs/src/define-routes/_index.md
Labels: enhancement, quick task, markdown/prose

#3276 Fix typo in build-from-fork workflow
  .github/workflows/build-from-fork.yaml
Labels: quick task, markdown/prose

#3269 Add version notes to Drupal docs
  docs/src/guides/drupal9/_index.md
  docs/src/guides/drupal9/deploy/_index.md
  docs/src/guides/drupal9/deploy/configure.md
  docs/src/guides/drupal9/deploy/customize.md
  docs/src/guides/drupal9/deploy/deploy.md
  docs/src/guides/drupal9/deploy/next-steps.md
  docs/src/guides/drupal9/multi-site.md
  docs/src/guides/drupal9/simplesaml.md
Labels: quick task, markdown/prose

#3295 Add note about Lando plugin deprecation
  docs/layouts/shortcodes/local-dev/lando-plugin-note.md
  docs/src/development/local/lando.md
Labels: quick task, markdown/prose

#3301 Add Solr 9.2 and MariaDB 11 to registry
  docs/data/registry.json
Labels: quick task, markdown/prose

#3300 Remove Elasticsearch row from DG3 table for now
  docs/layouts/shortcodes/gen-3-services.html
Labels: quick task, markdown/prose

#3304 Add info about access to Blackfire env using PSH login for Obs Suite
  docs/src/increase-observability/integrate-observability/blackfire.md
Labels: quick task, markdown/prose

#3303 Add information on how to run scripts
  docs/src/development/troubleshoot.md
Labels: quick task, markdown/prose

#3228 Document Elasticsearch Enterprise
  docs/data/registry.json
  docs/layouts/shortcodes/endpoint-description.md
  docs/src/add-services/elasticsearch.md
Labels: enhancement, markdown/prose

#3308 Update redis.md
  docs/src/add-services/redis.md
Labels: markdown/prose

#3265 Add Go config reader
  docs/src/guides/hibernate/deploy.md
  docs/src/guides/jakarta/deploy.md
  docs/src/languages/elixir.md
  docs/src/languages/go.md
  docs/src/languages/java/_index.md
  docs/src/languages/nodejs/_index.md
  docs/src/languages/php/_index.md
Labels: quick task, build-fork, markdown/prose

#3145 :memo: Rework Dedicated Gen 3 section
  docs/layouts/shortcodes/multi-app-intro.md
  docs/layouts/shortcodes/project-isolation.md
  docs/src/dedicated-gen-2/architecture/_index.md
  docs/src/dedicated-gen-2/architecture/options.md
  docs/src/dedicated-gen-2/overview/_index.md
  docs/src/dedicated-gen-2/overview/monitoring.md
  docs/src/dedicated-gen-2/overview/security.md
  docs/src/dedicated-gen-3/_index.md
  docs/src/dedicated-gen-3/monitoring.md
  docs/src/dedicated-gen-3/multiple-az.md
  docs/src/dedicated-gen-3/options.md
  docs/src/dedicated-gen-3/security.md
  docs/src/increase-observability/metrics/dedicated-generation-3.md
  docs/src/other/glossary.md
  docs/src/overview/structure.md
  docs/static/images/dedicated/incident-mntg.svg
  docs/static/images/dedicated/incident-monitoring-graph.svg
  docs/static/images/dedicated/incident-monitoring.svg
Labels: docs rework, markdown/prose

#3307 Add sourceguardian to php 8.2 list
  docs/data/php_extensions.yaml
Labels: build-fork, markdown/prose

#3310 Fix version number
  docs/src/add-services/elasticsearch.md
Labels: quick task, markdown/prose

#3311 Enable oauth module on php 8.2
  docs/data/php_extensions.yaml
Labels: build-fork, markdown/prose
