Repository platformsh/platformsh-docs, pull requests merged in 2023-06, with the labels that each got.

#3200 Fix Django guide
  docs/src/guides/django/deploy/configure.md
Labels: quick task, markdown/prose

#3207 Amend registry to fix display of Opensearch version
  docs/data/registry.json
Labels: quick task

#3203 Update WAF page
  docs/src/security/web-application-firewall/waf.md
Labels: quick task

#3205 Add note on email limitation
  docs/src/development/email.md
Labels: quick task

#3197 Document timezones on one page
  docs/src/create-apps/timezone.md
Labels: enhancement

#3192 Improve section on .htaccess files
  docs/src/define-routes/_index.md
Labels: quick task

#3194 Make Node.js page intro clearer
  docs/src/languages/nodejs/node-version.md
Labels: enhancement

#3086 Updating Grid, DG2 and DG3 versions for runtimes and services
  docs/data/registry.json
Labels: enhancement, build-fork

#3193 Add info on burst for Grid & DG3
  docs/src/increase-observability/metrics/_index.md
Labels: quick task

#3201 Remove $ in commands
  docs/data/templates.yaml
  docs/layouts/shortcodes/cli-installation.html
  docs/layouts/shortcodes/guides/data-migration.md
  docs/layouts/shortcodes/source-integration/validate.md
  docs/src/add-services/_index.md
  docs/src/administration/cli/_index.md
  docs/src/administration/cli/api-tokens.md
  docs/src/create-apps/multi-app.md
  docs/src/create-apps/runtime-operations.md
  docs/src/create-apps/troubleshoot-mounts.md
  docs/src/create-apps/workers.md
  docs/src/define-routes/_index.md
  docs/src/development/file-transfer.md
  docs/src/development/local/tethered.md
  docs/src/development/ssh/_index.md
  docs/src/development/ssh/troubleshoot-ssh.md
  docs/src/development/troubleshoot.md
  docs/src/development/variables/_index.md
  docs/src/development/variables/use-variables.md
  docs/src/guides/django/deploy/_index.md
  docs/src/guides/drupal9/deploy/next-steps.md
  docs/src/guides/drupal9/elasticsearch.md
  docs/src/guides/drupal9/solr.md
  docs/src/guides/gatsby/headless/drupal.md
  docs/src/guides/gatsby/headless/strapi.md
  docs/src/guides/typo3/deploy/customize.md
  docs/src/guides/wordpress/composer/_index.md
  docs/src/guides/wordpress/composer/migrate.md
  docs/src/guides/wordpress/deploy/next-steps.md
  docs/src/increase-observability/metrics/dedicated.md
  docs/src/integrations/activity/_index.md
  docs/src/integrations/activity/webhooks.md
  docs/src/integrations/notifications.md
  docs/src/integrations/overview.md
  docs/src/integrations/source/troubleshoot.md
  docs/src/languages/php/fpm.md
  docs/static/files/fetch/examples/relationships/vault-kms
Labels: enhancement

#3216 Remove typo
  docs/src/integrations/overview.md
Labels: quick task

#3221 Remove sponsored sites page in favor of new form.
  .platform/routes.yaml
  docs/src/administration/pricing/_index.md
  docs/src/administration/pricing/sponsored.md
Labels: markdown/prose

#3223 Upgrade Hugo to 0.113.0.
  .github/workflows/pr-check-links.yaml
  README.md
  docs/.platform.app.yaml
  docs/src/languages/php/_index.md
Labels: markdown/prose

#3218 Refactor/3169 local builds
  .gitignore
  README.md
  docs/layouts/shortcodes/relationship.html
  docs/themes/psh-docs/layouts/partials/codetabs/tabs.html
  docs/themes/psh-docs/layouts/shortcodes/readFile.html
  docs/utils/common.mjs
  docs/utils/fetch-examples.mjs
  docs/utils/fetchTemplates.mjs
Labels: markdown/prose

#3227 Remove dot-prefix from applications.yaml
  docs/src/create-apps/multi-app.md
Labels: build-fork, markdown/prose

#3045 :sparkles: Add http forwarding section
  docs/src/increase-observability/logs/forward-logs.md
Labels: enhancement, build-fork

#3230 Refactor scheduled link checker
  .github/workflows/scheduled-check-links.yaml
Labels: gh-workflows, markdown/prose

#3238 [Workflow] set a scan URL if triggered by schedule event
  .github/workflows/scheduled-check-links.yaml
Labels: gh-workflows, markdown/prose

#3244 Remove compliance guidance page
  docs/src/security/compliance-guidance.md
Labels: quick task, markdown/prose

#3250 Ad kafka 3.4 to supported version
  docs/data/registry.json
Labels: build-fork

#3214 Remove all mentions of EU and US legacy regions
  docs/data/regions.yaml
  docs/src/add-services/_index.md
  docs/src/add-services/headless-chrome.md
  docs/src/add-services/kafka.md
  docs/src/add-services/memcached.md
  docs/src/add-services/mysql/_index.md
  docs/src/add-services/network-storage.md
  docs/src/add-services/opensearch.md
  docs/src/add-services/postgresql.md
  docs/src/add-services/rabbitmq.md
  docs/src/add-services/redis.md
  docs/src/add-services/solr.md
  docs/src/add-services/varnish.md
  docs/src/add-services/vault.md
  docs/src/create-apps/app-reference.md
  docs/src/create-apps/hooks/hooks-comparison.md
  docs/src/development/regions.md
  docs/src/environments/backup.md
  docs/src/environments/restore.md
  docs/src/increase-observability/logs/access-logs.md
  docs/src/increase-observability/metrics/_index.md
  docs/src/languages/dotnet.md
  docs/src/languages/elixir.md
  docs/src/languages/go.md
  docs/src/languages/java/_index.md
  docs/src/languages/lisp.md
  docs/src/languages/nodejs/_index.md
  docs/src/languages/php/_index.md
  docs/src/languages/python/_index.md
  docs/src/languages/ruby.md
  docs/src/projects/region-migration.md
Labels: enhancement
