Repository platformsh/platformsh-docs, pull requests merged in 2024-10, with the labels that each got.

#4213 updates the anchor link redirect for live backups to the correct location
  .platform/routes.yaml
Labels: markdown/prose

#4215 Update routes.yaml
  .platform/routes.yaml
Labels: markdown/prose

#4136 Rust continuous profiling support
  sites/upsun/src/increase-observability/application-metrics/rust.md
Labels: enhancement, markdown/prose

#4137 Ruby continuous profiling support
  sites/upsun/src/increase-observability/application-metrics/ruby.md
Labels: markdown/prose, upcoming-blackfire

#4220 Include Blackfire in under 3 minutes video
  sites/platform/src/increase-observability/integrate-observability/blackfire.md
  sites/upsun/config/_default/config.yaml
  sites/upsun/src/increase-observability/application-metrics/blackfire.md
  sites/upsun/src/increase-observability/application-metrics/understanding.md
Labels: markdown/prose

#4216 Improve explanations around the new/old outgoing IPs
  sites/platform/src/development/regions.md
  sites/upsun/src/development/regions.md
Labels: markdown/prose, good-first-issue

#4229 Update requested GTM/heap changes.
  sites/upsun/config/_default/params.yaml
  themes/psh-docs/layouts/partials/scripts/external.html
Labels: markdown/prose

#4238 node22 supported
  shared/data/registry.json
Labels: markdown/prose

#4237 feat: added dunning process section
  sites/platform/.yaml
  sites/platform/src/administration/pricing/_index.md
  sites/upsun/src/administration/pricing.md
Labels: markdown/prose

#4242 Update clickhouse.md
  sites/upsun/src/add-services/clickhouse.md
Labels: markdown/prose

#4244 Workflow updates
  .github/actions/get-pr-info/action.yaml
  .github/workflows/comment-on-pr.yaml
  .github/workflows/e2e.yaml
  .github/workflows/pr-url-and-dependent.yaml
  .github/workflows/redirections.yaml
  CONTRIBUTING.md
Labels: markdown/prose
