Repository platformsh/platformsh-docs, pull requests merged in 2024-04, with the labels that each got.

#3903 [Next.js] Getting started guide
  sites/upsun/src/get-started/stacks/nextjs.md
Labels: markdown/prose

#3905 [Strapi] Getting started guide
  sites/upsun/src/get-started/stacks/strapi.md
  sites/upsun/src/get-started/stacks/strapi/_index.md
  sites/upsun/src/get-started/stacks/strapi/add-database.md
  sites/upsun/src/languages/nodejs/_index.md
Labels: markdown/prose

#3816 [Django + Flask] Getting Started Frameworks section for Upsun
  sites/upsun/config/_default/params.yaml
  sites/upsun/src/get-started/stacks/django.md
  sites/upsun/src/get-started/stacks/flask.md
Labels: WIP, docs rework, markdown/prose

#3915 Fix composable image xdebug configuration.
  sites/platform/src/languages/php/_index.md
  sites/upsun/src/languages/php/_index.md
Labels: markdown/prose

#3917 Pre-GA fixes
  .vale.ini
  contributing/styles/config/vocabularies/Platform/accept.txt
  sites/platform/src/create-apps/app-reference/_index.md
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/platform/src/create-apps/hooks/_index.md
  sites/platform/src/languages/php/_index.md
  sites/upsun/src/administration/billing/monitor-billing.md
  sites/upsun/src/create-apps/app-reference/_index.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/get-started/here/_index.md
  sites/upsun/src/get-started/here/configure/_index.md
  sites/upsun/src/get-started/here/configure/nodejs.md
  sites/upsun/src/get-started/here/configure/php.md
  sites/upsun/src/get-started/here/configure/python.md
  sites/upsun/src/get-started/here/create-project.md
  sites/upsun/src/get-started/here/make-changes.md
  sites/upsun/src/get-started/here/setup.md
  sites/upsun/src/get-started/here/support.md
  sites/upsun/src/get-started/here/third-party.md
  sites/upsun/src/get-started/stacks/_index.md
  sites/upsun/src/get-started/stacks/express/_index.md
  sites/upsun/src/get-started/stacks/express/add-database.md
  sites/upsun/src/get-started/stacks/flask.md
  sites/upsun/src/get-started/stacks/laravel/_index.md
  sites/upsun/src/get-started/stacks/nextjs.md
  sites/upsun/src/get-started/stacks/strapi/_index.md
  sites/upsun/src/get-started/stacks/strapi/add-database.md
  sites/upsun/src/get-started/stacks/symfony/_index.md
  sites/upsun/src/get-started/stacks/wordpress.md
  sites/upsun/src/languages/php/_index.md
  sites/upsun/src/languages/php/extensions.md
  sites/upsun/src/learn/overview/yaml/yaml-structure.md
  sites/upsun/src/manage-resources/resource-init.md
Labels: markdown/prose

#3919 Fix community links
  sites/upsun/src/learn/overview/get-support.md
Labels: markdown/prose

#3920 Updates troubleshoot.md
  sites/platform/src/languages/php/troubleshoot.md
Labels: markdown/prose

#3922 Update composable-image.md
  sites/platform/src/create-apps/app-reference/composable-image.md
Labels: quick task, markdown/prose

#3923 Update composable-image-upsun.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: quick task, markdown/prose

#3921 Improve consistency in GS guides
  sites/upsun/src/get-started/stacks/django.md
  sites/upsun/src/get-started/stacks/express/_index.md
  sites/upsun/src/get-started/stacks/flask.md
  sites/upsun/src/get-started/stacks/laravel/_index.md
  sites/upsun/src/get-started/stacks/laravel/blackfire.md
  sites/upsun/src/get-started/stacks/laravel/crons.md
  sites/upsun/src/get-started/stacks/laravel/environment-variables.md
  sites/upsun/src/get-started/stacks/laravel/get-started.md
  sites/upsun/src/get-started/stacks/nextjs.md
  sites/upsun/src/get-started/stacks/strapi/_index.md
  sites/upsun/src/get-started/stacks/symfony/_index.md
  sites/upsun/src/get-started/stacks/symfony/blackfire.md
  sites/upsun/src/get-started/stacks/symfony/crons.md
  sites/upsun/src/get-started/stacks/symfony/environment-variables.md
  sites/upsun/src/get-started/stacks/symfony/faq.md
  sites/upsun/src/get-started/stacks/symfony/get-started.md
  sites/upsun/src/get-started/stacks/symfony/integration.md
  sites/upsun/src/get-started/stacks/symfony/local.md
  sites/upsun/src/get-started/stacks/symfony/symfony-cli-tips.md
  sites/upsun/src/get-started/stacks/symfony/workers.md
  sites/upsun/src/get-started/stacks/wordpress.md
Labels: enhancement, markdown/prose, Upsun

#3924 Update A records doc to link to correct IPs
  sites/platform/src/domains/steps/dns.md
  sites/upsun/src/domains/steps/dns.md
Labels: quick task, markdown/prose

#3932 Update clickhouse.md
  sites/upsun/src/add-services/clickhouse.md
Labels: quick task, markdown/prose, Upsun

#3936 Update ClickHouse page to advertise latest 24.3 version
  sites/upsun/src/add-services/clickhouse.md
Labels: quick task, markdown/prose, Upsun

#3929 Document container profiles on PSH
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/manage-resources/resource-init.md
Labels: enhancement, markdown/prose

#3945 Removes vendor name from composable image beta notification
  themes/psh-docs/layouts/shortcodes/composable/disclaimer.md
Labels: markdown/prose

#3949 Replicate PR#3857 to include Upsun.
  sites/platform/src/integrations/source/bitbucket.md
  sites/platform/src/integrations/source/github.md
  sites/platform/src/integrations/source/gitlab.md
  sites/upsun/src/integrations/source/bitbucket.md
  sites/upsun/src/integrations/source/github.md
  sites/upsun/src/integrations/source/gitlab.md
  themes/psh-docs/layouts/shortcodes/source-integration/enable-integration.html
Labels: markdown/prose

#3950 [Resubmit] Git 26 integration updates
  sites/platform/src/integrations/source/bitbucket.md
  sites/platform/src/integrations/source/github.md
  sites/platform/src/integrations/source/gitlab.md
  sites/upsun/src/integrations/source/bitbucket.md
  sites/upsun/src/integrations/source/github.md
  sites/upsun/src/integrations/source/gitlab.md
  themes/psh-docs/layouts/shortcodes/source-integration/sync-fetch-prune.md
Labels: markdown/prose

#3951 Update Ruby versions
  shared/data/registry.json
  sites/platform/src/languages/ruby.md
  sites/upsun/src/languages/ruby.md
Labels: markdown/prose

#3952 Add redeploy one-liner.
  sites/platform/src/development/troubleshoot.md
  sites/upsun/src/development/troubleshoot.md
Labels: markdown/prose

#3953 Add clarification to the environments definition.
  sites/platform/src/environments/_index.md
  sites/upsun/src/environments/_index.md
Labels: markdown/prose

#3955 Fix ascii characters in head/title render.
  themes/psh-docs/layouts/partials/head/head.html
Labels: markdown/prose

#3956 Add enterprise 7.0 for MongoDB.
  shared/data/registry.json
Labels: markdown/prose

#3958 Recommend progressive upgrades.
  sites/platform/src/add-services/_index.md
  sites/upsun/src/add-services/_index.md
Labels: markdown/prose

#3959 Update Tideways reference that is now archived
  sites/platform/src/increase-observability/integrate-observability/tideways.md
Labels: markdown/prose

#3960 Add an SMTP note to Symfony guides.
  sites/platform/src/guides/symfony/crons.md
  sites/upsun/src/get-started/stacks/symfony/crons.md
Labels: markdown/prose

#3961 Update sanitize db snippets as per feedback
  sites/platform/src/development/sanitize-db/mariadb.md
  sites/upsun/src/development/sanitize-db/mariadb.md
  themes/psh-docs/layouts/shortcodes/sanitize-dbs/sanitize-manually.md
Labels: markdown/prose

#3962 Include additional note about P.sh default preview env app sizes.
  sites/platform/src/environments/_index.md
Labels: markdown/prose

#3972 Add link to generate SSH keys.
  sites/platform/src/development/ssh/troubleshoot-ssh.md
  sites/upsun/src/development/ssh/troubleshoot-ssh.md
Labels: markdown/prose

#3973 Warn of Pimcore PaaS account deletion.
  sites/platform/src/learn/overview/get-support.md
  sites/upsun/src/learn/overview/get-support.md
Labels: markdown/prose

#3975 Add a note for the WAF.
  sites/platform/src/security/web-application-firewall/waf.md
Labels: markdown/prose

#3976 Warn py web servers needs to be added as a dependency.
  themes/psh-docs/layouts/shortcodes/python-sockets.md
Labels: markdown/prose

#3978 Replace or add CLI redis cmd.
  sites/platform/src/add-services/redis.md
  sites/platform/src/guides/drupal/redis.md
  sites/platform/src/guides/wordpress/redis.md
  sites/upsun/src/add-services/redis.md
Labels: markdown/prose

#3965 Add a suggested content feature.
  sites/upsun/src/create-apps/source-operations.md
  themes/psh-docs/layouts/partials/page-content.html
  themes/psh-docs/static/css/vendor.css
Labels: markdown/prose

#3968 Duplicate tests + update contribution docs
  .github/workflows/build-from-fork.yaml
  .github/workflows/get-pr-info.yaml
  .github/workflows/linting.yaml
  .github/workflows/manage-environment.yaml
  .github/workflows/pr-check-links.yaml
  .gitignore
  README.md
  contributing/styles/config/vocabularies/Platform/accept.txt
  package.json
  sites/platform/src/add-services/opensearch.md
  sites/upsun/layouts/shortcodes/home/table.html
  sites/upsun/src/add-services/influxdb.md
  sites/upsun/src/add-services/network-storage.md
  sites/upsun/src/administration/web/mfa.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/create-apps/timezone.md
  sites/upsun/src/create-apps/web/static.md
  sites/upsun/src/create-apps/workers.md
  sites/upsun/src/development/regions.md
  sites/upsun/src/development/ssh/troubleshoot-ssh.md
  sites/upsun/src/domains/steps/custom-domains-preview-environments.md
  sites/upsun/src/environments/_index.md
  sites/upsun/src/environments/backup.md
  sites/upsun/src/get-started/here/configure/php.md
  sites/upsun/src/get-started/here/configure/python.md
  sites/upsun/src/get-started/here/make-changes.md
  sites/upsun/src/get-started/stacks/express/_index.md
  sites/upsun/src/get-started/stacks/express/add-database.md
  sites/upsun/src/get-started/stacks/flask.md
  sites/upsun/src/get-started/stacks/laravel/_index.md
  sites/upsun/src/get-started/stacks/laravel/crons.md
  sites/upsun/src/get-started/stacks/laravel/get-started.md
  sites/upsun/src/get-started/stacks/laravel/laravel-horizon.md
  sites/upsun/src/get-started/stacks/nextjs.md
  sites/upsun/src/get-started/stacks/strapi/_index.md
  sites/upsun/src/get-started/stacks/symfony/workers.md
  sites/upsun/src/get-started/stacks/wordpress.md
  sites/upsun/src/glossary/_index.md
  sites/upsun/src/increase-observability/application-metrics/cont-prof.md
  sites/upsun/src/increase-observability/application-metrics/go.md
  sites/upsun/src/increase-observability/application-metrics/nodejs.md
  sites/upsun/src/increase-observability/application-metrics/php.md
  sites/upsun/src/increase-observability/application-metrics/python.md
  sites/upsun/src/increase-observability/application-metrics/understanding.md
  sites/upsun/src/increase-observability/metrics/http-metrics.md
  sites/upsun/src/increase-observability/metrics/understand-metrics.md
  sites/upsun/src/integrations/activity/reference.md
  sites/upsun/src/languages/lisp.md
  sites/upsun/src/languages/php/_index.md
  sites/upsun/src/languages/php/extensions.md
  sites/upsun/src/learn/overview/yaml/yaml-structure.md
  sites/upsun/src/learn/tutorials/migrating/from-psh.md
  sites/upsun/src/manage-resources/adjust-resources.md
  sites/upsun/src/manage-resources/resource-init.md
  tests.sh
  themes/psh-docs/layouts/shortcodes/access-services.md
Labels: markdown/prose

#3981 Add tested minimal Next Upsun config.
  sites/upsun/src/get-started/stacks/nextjs.md
Labels: markdown/prose

#3983 Remove remaining runtime, build, dependencies keys for composable image.
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#3984 Fix simple/explicit relationships for Upsun.
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/add-services/_index.md
  sites/upsun/src/add-services/kafka.md
  sites/upsun/src/add-services/mysql/_index.md
  sites/upsun/src/add-services/solr.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/create-apps/workers.md
Labels: markdown/prose

#3986 missing spaces between 'Upsun/Platform' and 'and'
  sites/platform/src/increase-observability/logs/forward-logs.md
  sites/upsun/src/increase-observability/logs/forward-logs.md
Labels: markdown/prose

#3988 Update PHP extensions
  shared/data/php_extensions.yaml
Labels: enhancement, markdown/prose

#3985 Remove mention to the Continuous Profiling sandwich view
  sites/upsun/src/increase-observability/application-metrics/cont-prof.md
  sites/upsun/static/images/observability/sandwich-view.png
Labels: markdown/prose

#3995 corrects issue with Heap ID not being selected correctly
  themes/psh-docs/layouts/partials/scripts/external.html
Labels: markdown/prose

#3939 Document Gotenberg
  contributing/styles/config/vocabularies/Platform/accept.txt
  sites/platform/src/add-services/gotenberg.md
  sites/upsun/src/add-services/gotenberg.md
  themes/psh-docs/layouts/shortcodes/access-services.md
Labels: enhancement, markdown/prose, Upsun

#3974 Update RabbitMQ supported versions.
  shared/data/registry.json
Labels: markdown/prose

#3997 Add missing colon to composable image snippets
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
Labels: enhancement, quick task, markdown/prose, Upsun

#3928 Document no-code option
  sites/upsun/src/environments/backup.md
  sites/upsun/src/manage-resources/resource-init.md
Labels: enhancement, markdown/prose, Upsun

#3993 Add redirects for broken links from Google search
  .platform/routes.yaml
Labels: quick task, markdown/prose, Upsun

#3999 Remove local dev shortcodes
  sites/platform/src/development/local/tethered.md
  sites/platform/src/guides/django/local/ddev.md
  sites/platform/src/guides/django/local/tethered.md
  sites/upsun/src/development/local/tethered.md
  themes/psh-docs/layouts/shortcodes/local-dev/local-dev-onboarding.sh
  themes/psh-docs/layouts/shortcodes/local-dev/next-steps-end.md
  themes/psh-docs/layouts/shortcodes/local-dev/next-steps-start.md
  themes/psh-docs/layouts/shortcodes/snippets/guides/django/ddev/local-pip.sh
  themes/psh-docs/layouts/shortcodes/snippets/guides/django/ddev/local-pipenv.sh
  themes/psh-docs/layouts/shortcodes/snippets/guides/django/ddev/local-poetry.sh
  themes/psh-docs/layouts/shortcodes/snippets/guides/django/tethered/local-pip.sh
  themes/psh-docs/layouts/shortcodes/snippets/guides/django/tethered/local-pipenv.sh
  themes/psh-docs/layouts/shortcodes/snippets/guides/django/tethered/local-poetry.sh
Labels: enhancement, WIP, markdown/prose, Platform.sh, Upsun

#4001 Introduce mTLS terminology instead of TLS certificates where appropriate
  sites/platform/src/define-routes/https.md
  sites/platform/src/domains/cdn/_index.md
  sites/platform/src/domains/cdn/managed-fastly.md
  sites/platform/src/domains/steps/tls.md
  sites/platform/src/guides/ibexa/fastly.md
  sites/upsun/src/define-routes/https.md
  sites/upsun/src/domains/cdn/_index.md
  sites/upsun/src/domains/steps/tls.md
Labels: enhancement, markdown/prose

#4002 Update Network Storage page
  sites/platform/src/add-services/network-storage.md
  sites/upsun/src/add-services/network-storage.md
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: enhancement, markdown/prose

#4000 Remove section about templates on Ruby page
  sites/platform/src/languages/ruby.md
Labels: quick task, markdown/prose
