Repository platformsh/platformsh-docs, pull requests merged in 2024-09, with the labels that each got.

#4168 Upsun cta fix
  sites/platform/config/_default/params.yaml
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
Labels: markdown/prose

#4175 Style updates to CTA.
  sites/upsun/config/_default/params.yaml
  themes/psh-docs/assets/css/main.css
  themes/psh-docs/layouts/partials/page-content.html
  themes/psh-docs/static/css/vendor.css
Labels: markdown/prose, on-deck

#4170 Fix trial branding
  sites/platform/config/_default/params.yaml
  themes/psh-docs/layouts/partials/page-content.html
Labels: build-fork, markdown/prose, on-deck

#4143 Mention HTTPS DNS record
  sites/platform/src/domains/cdn/cloudflare.md
  sites/platform/src/domains/steps/dns.md
  sites/upsun/src/domains/cdn/cloudflare.md
  sites/upsun/src/domains/steps/dns.md
Labels: build-fork, markdown/prose, on-deck

#4181 Render shortcodes out of devcenter index.
  themes/psh-docs/layouts/_default/list.devcenter.json
  themes/psh-docs/layouts/partials/utils/fragments.html
Labels: markdown/prose

#4182 fix: extensions indent on composable
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: build-fork, markdown/prose

#4198 changes instances of 'Slack' to 'Discord'
  sites/platform/src/_index.md
  sites/platform/src/learn/overview/get-support.md
Labels: markdown/prose

#4191 golang: add 1.23 to supported versions
  shared/data/registry.json
Labels: build-fork, markdown/prose

#4200 Update add-on-subscription.md
  sites/upsun/src/administration/billing/add-on-subscription.md
Labels: markdown/prose

#4207 Pauses examples.docs.platform.sh pulls
  sites/platform/.yaml
  sites/platform/package-lock.json
  sites/platform/package.json
  sites/platform/src/guides/django/deploy/configure.md
  sites/platform/src/guides/drupal/deploy/configure.md
  sites/platform/src/guides/drupal/deploy/customize.md
  sites/platform/src/guides/typo3/deploy/configure.md
  sites/platform/src/guides/typo3/deploy/customize.md
  sites/platform/src/guides/wordpress/deploy/configure.md
  sites/platform/src/guides/wordpress/deploy/customize.md
  sites/platform/src/guides/wordpress/vanilla/configure.md
  sites/platform/src/guides/wordpress/vanilla/customize.md
  sites/upsun/.yaml
  sites/upsun/package-lock.json
  sites/upsun/package.json
Labels: do not merge, markdown/prose

#4204 Swapped 5 and 6 around
  sites/platform/src/environments/default-environment.md
  sites/upsun/src/environments/default-environment.md
Labels: markdown/prose, on-deck

#4206 updated code snippet
  sites/platform/src/languages/python/dependencies.md
  sites/upsun/src/languages/python/dependencies.md
Labels: markdown/prose, on-deck

#4205 4149 run a runtime operation from the console
  sites/platform/src/create-apps/runtime-operations.md
  sites/upsun/src/create-apps/runtime-operations.md
Labels: markdown/prose, on-deck

#4208 postgresql: add info about local pg_dump with tunnel
  sites/platform/src/add-services/postgresql.md
  sites/upsun/src/add-services/postgresql.md
Labels: build-fork, markdown/prose, on-deck

#4199 Add changes for Azure Outgoing IPs
  sites/platform/src/development/regions.md
  sites/upsun/src/development/regions.md
Labels: markdown/prose, on-deck

#4203 Made changes to user docs
  sites/upsun/src/administration/mfa.md
  sites/upsun/src/administration/users.md
  themes/psh-docs/layouts/partials/user-mgt-sellable/body.md
Labels: markdown/prose, on-deck
