Repository platformsh/platformsh-docs, pull requests merged in 2024-05, with the labels that each got.

#4006 Fix order in app reference section on PSH
  sites/platform/src/create-apps/app-reference/composable-image.md
Labels: quick task, markdown/prose

#4007 Add note about branching when using a source integration
  sites/platform/src/glossary/_index.md
  sites/upsun/src/glossary/_index.md
Labels: enhancement, markdown/prose

#4008 Rework redirects page to include more info on cache finetuning
  sites/platform/src/define-routes/redirects.md
  sites/upsun/src/define-routes/redirects.md
Labels: enhancement, markdown/prose

#4010 Retrieve managed Fastly CDN API token
  sites/platform/src/domains/cdn/managed-fastly.md
Labels: enhancement, markdown/prose

#4005 Update cmd to commands in cron configuration examples
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/platform/src/guides/symfony/crons.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/get-started/stacks/laravel/crons.md
  sites/upsun/src/get-started/stacks/symfony/crons.md
Labels: enhancement, WIP, markdown/prose

#3992 Slight updates on the clickhouse service page
  sites/upsun/src/add-services/clickhouse.md
Labels: markdown/prose

#4012 Update runtime tables for composable image.
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#4017 [CLI-BOT] Update on doc pages for CLI commands
  sites/platform/src/administration/cli/reference.md
  sites/upsun/src/administration/cli/reference.md
Labels: markdown/prose, report, automated pr

#4024 Fix indentation in composable image snippets
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: enhancement, markdown/prose, Platform.sh, Upsun

#4029 Add Pimcore and Shopware to Frameworks
  sites/platform/src/guides/pimcore.md
  sites/platform/src/guides/shopware.md
  sites/upsun/.yaml
  sites/upsun/src/get-started/stacks/pimcore.md
  sites/upsun/src/get-started/stacks/shopware.md
  themes/psh-docs/layouts/partials/sidebar/list.html
  themes/psh-docs/layouts/partials/white-labels/badge.html
Labels: enhancement, markdown/prose

#4033 Erratum: Rename SYMFONY_APP_DIR to PLATFORM_APP_DIR
  sites/platform/src/guides/symfony/integration.md
  sites/upsun/src/get-started/stacks/symfony/integration.md
Labels: quick task, markdown/prose, Platform.sh, Upsun

#4032 Add warning about `nix` commands
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: enhancement, markdown/prose

#4026 Add link to Languages page from Frameworks page
  sites/upsun/src/get-started/stacks/_index.md
Labels: enhancement, markdown/prose, Upsun

#4015 Add a comprehensive composable img example on Configure app index page
  sites/platform/src/create-apps/_index.md
  sites/upsun/src/create-apps/_index.md
Labels: enhancement, markdown/prose

#4025 MariaDB upgrades
  sites/platform/src/add-services/mysql/_index.md
  sites/upsun/src/add-services/mysql/_index.md
Labels: enhancement, markdown/prose, Platform.sh, Upsun

#4023 Fix display issues in PSH guides
  themes/psh-docs/layouts/shortcodes/guides/data-migration.md
  themes/psh-docs/layouts/shortcodes/guides/deployment.md
  themes/psh-docs/layouts/shortcodes/guides/initialize.html
Labels: enhancement, markdown/prose

#4016 Qualify note about disk downsizing and backups
  themes/psh-docs/layouts/shortcodes/disk-downsize.md
Labels: quick task, markdown/prose

#4039 adds "sleepy crons" keywords to app reference pages
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
Labels: markdown/prose

#4035 Remove Working on it message
  themes/psh-docs/layouts/shortcodes/image-versions.html
Labels: enhancement, markdown/prose

#4037 Remove mentions of legacy regions
  contributing/templates/language-reference.md
  contributing/templates/service-reference.md
  sites/platform/src/development/regions.md
  sites/upsun/src/projects/region-migration.md
  themes/psh-docs/layouts/shortcodes/legacy-regions.md
Labels: enhancement, markdown/prose, Platform.sh, Upsun

#4043 s/GitHub/Bitbucket typo
  sites/platform/src/integrations/source/github.md
  sites/platform/src/integrations/source/gitlab.md
  sites/upsun/src/integrations/source/github.md
  sites/upsun/src/integrations/source/gitlab.md
Labels: markdown/prose

#4047 Erratum: web/uploads mount should be a storage mount
  sites/upsun/src/learn/tutorials/migrating/from-psh.md
Labels: quick task, markdown/prose, Upsun
