Repository platformsh/platformsh-docs, pull requests merged in 2024-07, with the labels that each got.

#4092 NGWAF - Replace Managed by Basic configurable
  sites/platform/src/security/web-application-firewall/fastly-waf.md
Labels: build-fork, markdown/prose

#4086 [CLI-BOT] Update on doc pages for CLI commands
  sites/platform/src/administration/cli/reference.md
  sites/upsun/src/administration/cli/reference.md
Labels: markdown/prose, report, automated pr

#4074 Document MFA over SSH and API
  contributing/styles/config/vocabularies/Platform/accept.txt
  sites/platform/src/administration/security/_index.md
  sites/platform/src/administration/security/mfa.md
  sites/platform/src/administration/security/sso.md
  sites/platform/src/administration/web/mfa.md
  sites/platform/src/development/ssh/_index.md
  sites/platform/src/development/ssh/troubleshoot-ssh.md
  sites/platform/src/guides/ibexa/deploy.md
  sites/platform/src/learn/overview/get-support.md
  sites/upsun/src/administration/billing/add-on-subscription.md
  sites/upsun/src/administration/mfa.md
  sites/upsun/src/administration/users.md
  sites/upsun/src/administration/web/mfa.md
  sites/upsun/src/development/ssh/_index.md
  sites/upsun/src/development/ssh/troubleshoot-ssh.md
Labels: enhancement, markdown/prose, Platform.sh, Upsun

#4085 Adds e2e testing
  .github/workflows/e2e.yaml
  .gitignore
  cypress.config.js
  cypress/e2e/search.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/opensearchsresults.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  sites/platform/package-lock.json
  sites/platform/package.json
  sites/platform/static/scripts/xss/src/containers/Search.js
Labels: markdown/prose

#4102 Adds e2e testing
  .github/workflows/e2e.yaml
Labels: markdown/prose

#4105 Add names to e2e test to make required
  .github/workflows/e2e.yaml
Labels: markdown/prose

#4106 Site name in job title
  .github/workflows/e2e.yaml
Labels: markdown/prose

#4107 Use a gating conditional job for E2E tests
  .github/workflows/e2e.yaml
Labels: markdown/prose

#4104 Bump ws from 8.8.1 to 8.17.1 in /sites/platform
  sites/platform/package-lock.json
Labels: markdown/prose

#4108 Add keyword for better search
  sites/platform/src/learn/tutorials/migrating.md
Labels: markdown/prose

#4111 adds wait to e2e tests, reconfigures e2e workflow
  .github/workflows/e2e.yaml
  cypress/e2e/search.cy.js
Labels: markdown/prose

#4115 github tokens need to be set to "No expiration"
  sites/platform/src/integrations/source/github.md
Labels: build-fork, markdown/prose

#4116 Remove wrong start-php-app argument
  sites/platform/src/languages/php/_index.md
  sites/upsun/src/languages/php/_index.md
Labels: markdown/prose, on-deck

#4117 Remove references to services.yaml in Upsun docs
  sites/upsun/src/add-services/_index.md
  sites/upsun/src/administration/cli/reference.md
Labels: markdown/prose, on-deck

#4121 Token link in Upsun console
  .platform/routes.yaml
Labels: markdown/prose

#4120 opensearch: remove lang-python also from elasticsearch
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/opensearch.md
  sites/upsun/src/add-services/elasticsearch.md
  sites/upsun/src/add-services/opensearch.md
Labels: build-fork, markdown/prose, on-deck

#4119 Restrict runs of e2e testing
  .github/workflows/e2e.yaml
Labels: markdown/prose, on-deck

#4122 User security settings for P.sh
  sites/platform/src/administration/security/mfa.md
Labels: markdown/prose

#4131 Fix vendor name in network-storage.md
  sites/platform/src/add-services/network-storage.md
  sites/upsun/src/add-services/network-storage.md
Labels: markdown/prose
