Repository platformsh/platformsh-docs, pull requests merged in 2024-03, with the labels that each got.

#3806 [CLI-BOT] Update on doc pages for CLI commands
  sites/friday/src/administration/cli/reference.md
  sites/platform/src/administration/cli/reference.md
Labels: markdown/prose, report, automated pr

#3818 Specify that cache is always disabled on proxy routes
  sites/platform/src/define-routes/proxy.md
Labels: markdown/prose

#3820 removes drupal9, adds drupal10 to shared/data/remote-examples/templat…
  shared/data/remote-examples/templates/routes.yaml
Labels: markdown/prose

#3821 Fix error when building docs locally
  sites/friday/config/_default/config.yaml
  sites/platform/config/_default/config.yaml
Labels: quick task, markdown/prose

#3823 Continuous profiling color-coded node dimensions
  sites/friday/src/increase-observability/application-metrics/cont-prof.md
  sites/friday/static/images/observability/cont-prof-color-code.png
  sites/friday/static/images/observability/flame-graph-clicked.png
  sites/friday/static/images/observability/flame-graph-hover.png
  sites/friday/static/images/observability/flame-graph.png
  sites/friday/static/images/observability/sandwich-view.png
  sites/friday/static/images/observability/table-view.png
Labels: markdown/prose

#3833 Remove mention of DDEV integration in Upsun docs
  sites/friday/src/development/local/ddev.md
Labels: enhancement, markdown/prose

#3817 Delete account from Upsun Console
  sites/friday/src/learn/overview/get-support.md
  sites/platform/src/learn/overview/get-support.md
Labels: enhancement, markdown/prose

#3831 Fix typo in link
  sites/friday/src/get-started/here/configure/php.md
Labels: quick task, markdown/prose

#3834 Add Kafka 3.7 to registry
  shared/data/registry.json
Labels: quick task, markdown/prose

#3838 Add Shopware to accepted terms
  contributing/styles/config/vocabularies/Platform/accept.txt
Labels: quick task, markdown/prose

#3835 Remove term flagged by Vale
  sites/platform/src/define-routes/redirects.md
Labels: markdown/prose

#3843 remove duplicate source level
  sites/friday/src/create-apps/source-operations.md
Labels: markdown/prose

#3828 Add trial details.
  sites/friday/src/get-started/here/setup.md
  sites/friday/src/glossary/_index.md
  sites/friday/src/security/data-retention.md
Labels: enhancement, markdown/prose

#3855 Update overages prices on the pricing page
  sites/platform/src/administration/pricing/_index.md
Labels: markdown/prose

#3853 Fix back buttons
  sites/platform/src/guides/django/deploy/configure.md
  sites/platform/src/guides/django/deploy/customize.md
  sites/platform/src/guides/django/deploy/deploy.md
  sites/platform/src/guides/drupal/deploy/configure.md
  sites/platform/src/guides/drupal/deploy/customize.md
  sites/platform/src/guides/drupal/deploy/deploy.md
  sites/platform/src/guides/gatsby/deploy/configure.md
  sites/platform/src/guides/gatsby/deploy/deploy.md
  sites/platform/src/guides/laravel/deploy/blackfire.md
  sites/platform/src/guides/laravel/deploy/bridge.md
  sites/platform/src/guides/laravel/deploy/configure.md
  sites/platform/src/guides/laravel/deploy/octane.md
  sites/platform/src/guides/laravel/deploy/scheduling.md
  sites/platform/src/guides/micronaut/deploy/configure.md
  sites/platform/src/guides/micronaut/deploy/customize.md
  sites/platform/src/guides/micronaut/deploy/deploy.md
  sites/platform/src/guides/quarkus/deploy/configure.md
  sites/platform/src/guides/quarkus/deploy/customize.md
  sites/platform/src/guides/quarkus/deploy/deploy.md
  sites/platform/src/guides/spring/deploy/configure.md
  sites/platform/src/guides/spring/deploy/customize.md
  sites/platform/src/guides/spring/deploy/deploy.md
  sites/platform/src/guides/strapi/deploy/configure.md
  sites/platform/src/guides/strapi/deploy/deploy.md
  sites/platform/src/guides/symfony/blackfire.md
  sites/platform/src/guides/symfony/crons.md
  sites/platform/src/guides/symfony/environment-variables.md
  sites/platform/src/guides/symfony/get-started.md
  sites/platform/src/guides/symfony/integration.md
  sites/platform/src/guides/symfony/local.md
  sites/platform/src/guides/symfony/workers.md
  sites/platform/src/guides/typo3/deploy/configure.md
  sites/platform/src/guides/typo3/deploy/customize.md
  sites/platform/src/guides/typo3/deploy/deploy.md
  sites/platform/src/guides/wordpress/deploy/configure.md
  sites/platform/src/guides/wordpress/deploy/customize.md
  sites/platform/src/guides/wordpress/deploy/deploy.md
  sites/platform/src/guides/wordpress/vanilla/customize.md
  sites/platform/src/guides/wordpress/vanilla/deploy.md
Labels: markdown/prose

#3832 Update PHP extensions for Grid/DG3
  shared/data/php_extensions.yaml
Labels: enhancement, markdown/prose

#3856 Clarify automated backups aren't available for dev plans
  sites/platform/src/environments/backup.md
Labels: enhancement, markdown/prose

#3864 Removes json_pp from docs
  sites/platform/src/guides/drupal/redis.md
  sites/platform/src/guides/micronaut/mongodb.md
Labels: enhancement, markdown/prose, Platform.sh

#3875 Fix broken link
  sites/friday/src/get-started/here/configure/nodejs.md
Labels: quick task, markdown/prose

#3827 Add a reference to container_profile key.
  sites/friday/src/create-apps/app-reference.md
Labels: enhancement, markdown/prose

#3884 Update varnish supported versions
  shared/data/registry.json
Labels: markdown/prose

#3862 Add resources-init option to source integration pages
  sites/friday/src/integrations/source/bitbucket.md
  sites/friday/src/integrations/source/github.md
  sites/friday/src/integrations/source/gitlab.md
Labels: enhancement, markdown/prose

#3849 review of the activity script types + integration events
  sites/friday/src/integrations/activity/_index.md
  sites/friday/src/integrations/activity/reference.md
  sites/platform/src/integrations/activity/_index.md
  sites/platform/src/integrations/activity/reference.md
Labels: markdown/prose

#3737 Update Manage resources section
  sites/friday/src/get-started/here/set-resources.md
  sites/friday/src/manage-resources/adjust-resources.md
  sites/friday/src/manage-resources/resource-init.md
Labels: enhancement, markdown/prose

#3840 Update trial buttons + CTA banners.
  sites/friday/config/_default/params.yaml
  sites/platform/config/_default/params.yaml
Labels: markdown/prose, ready-for-staging

#3876 Remove 64 character Let's Encrypt limitation
  themes/psh-docs/layouts/shortcodes/lets_encrypt_limitations.md
Labels: quick task, markdown/prose, ready-for-staging

#3868 Revert "Revert instance mounts and temporary alias doc" for Git 26
  sites/friday/src/create-apps/app-reference.md
  sites/friday/src/create-apps/workers.md
Labels: upcoming version, markdown/prose, ready-for-staging

#3812 Document billing
  sites/friday/src/administration/billing/_index.md
  sites/friday/src/administration/billing/billing-admin.md
  sites/friday/src/administration/billing/monitor-billing.md
  sites/friday/src/manage-resources/adjust-resources.md
  sites/friday/src/manage-resources/resource-billing.md
  sites/friday/src/manage-resources/resource-init.md
  sites/friday/static/images/billing/billing-alert-button.png
  sites/friday/static/images/billing/invoices-tab.png
  sites/friday/static/images/billing/organization-billing.png
  sites/friday/static/images/billing/project-billing.png
Labels: enhancement, upcoming version, WIP, markdown/prose, ga-final-review

#3782 Document configurable build resources
  sites/friday/src/manage-resources/adjust-resources.md
  sites/friday/src/manage-resources/build-resources.md
  sites/friday/src/manage-resources/resource-billing.md
  sites/friday/src/manage-resources/resource-init.md
  sites/platform/src/create-apps/hooks/_index.md
  sites/platform/src/create-apps/multi-app/_index.md
  sites/platform/src/create-apps/timezone.md
  sites/platform/src/create-apps/troubleshoot-disks.md
  sites/platform/src/create-apps/troubleshoot-mounts.md
  sites/platform/src/create-apps/upgrading.md
  sites/platform/src/create-apps/web/_index.md
  sites/platform/src/create-apps/workers.md
Labels: enhancement, WIP, markdown/prose, ga-final-review

#3892 Document greener region discount (updated)
  sites/upsun/src/development/regions.md
Labels: markdown/prose

#3893 [CLI-BOT] Update on doc pages for CLI commands
  sites/friday/src/administration/cli/reference.md
  sites/platform/src/administration/cli/reference.md
Labels: markdown/prose, report, automated pr

#3894 Upsun: framework section landing page
  sites/upsun/layouts/shortcodes/frameworks-landing.md
  sites/upsun/src/_index.md
  sites/upsun/src/get-started/stacks/_index.md
Labels: markdown/prose

#3901 Update Redis persistent disk config
  sites/platform/src/guides/drupal/redis.md
Labels: build-fork, markdown/prose

#3902 Document how to enable Redis module
  sites/platform/src/guides/drupal/redis.md
Labels: build-fork, markdown/prose

#3897 [Upsun] Update GS link + wrongly inherited content.
  sites/upsun/config/_default/config.yaml
  sites/upsun/src/learn/overview/yaml/yaml-structure.md
Labels: markdown/prose

#3891 [WordPress] review Anouck
  sites/upsun/layouts/shortcodes/frameworks-landing.md
  sites/upsun/src/get-started/stacks/wordpress.md
Labels: markdown/prose

#3906 [Platform.sh] Update to use new demos link
  sites/platform/src/get-started/introduction.md
Labels: quick task, markdown/prose

#3895 Add PHP and Python continuous profiling documentation
  sites/upsun/src/increase-observability/application-metrics/go.md
  sites/upsun/src/increase-observability/application-metrics/nodejs.md
  sites/upsun/src/increase-observability/application-metrics/php.md
  sites/upsun/src/increase-observability/application-metrics/python.md
Labels: markdown/prose

#3890 [Upsun] Custom backup schedules
  sites/upsun/src/environments/backup.md
  sites/upsun/src/security/backups.md
  sites/upsun/src/security/data-retention.md
Labels: build-fork, markdown/prose

#3908 [Upsun] Update tier availability body for Teams
  themes/psh-docs/layouts/partials/user-mgt-sellable/body.md
Labels: markdown/prose

#3899 [Laravel] Resubmit: Adding the "Getting started" guide for Laravel
  sites/upsun/config/_default/params.yaml
  sites/upsun/src/get-started/stacks/laravel.md
  sites/upsun/src/get-started/stacks/laravel/_index.md
  sites/upsun/src/get-started/stacks/laravel/blackfire.md
  sites/upsun/src/get-started/stacks/laravel/crons.md
  sites/upsun/src/get-started/stacks/laravel/environment-variables.md
  sites/upsun/src/get-started/stacks/laravel/faq.md
  sites/upsun/src/get-started/stacks/laravel/get-started.md
  sites/upsun/src/get-started/stacks/laravel/laravel-horizon.md
  sites/upsun/src/get-started/stacks/laravel/laravel-telescope.md
  sites/upsun/src/get-started/stacks/laravel/setup-redis.md
  sites/upsun/src/get-started/stacks/symfony/_index.md
  sites/upsun/src/languages/php/_index.md
  sites/upsun/static/images/guides/laravel/horizon-dashboard.png
  sites/upsun/static/images/guides/laravel/horizon-resources.png
  sites/upsun/static/images/guides/laravel/telescope-dashboard.png
Labels: markdown/prose
