Repository platformsh/platformsh-docs, pull requests merged in 2024-06, with the labels that each got.

#4049 Remove link to private video
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: quick task, markdown/prose, Platform.sh, Upsun

#4050 [CLI-BOT] Update on doc pages for CLI commands
  sites/platform/src/administration/cli/reference.md
  sites/upsun/src/administration/cli/reference.md
Labels: markdown/prose, report, automated pr

#4048 Describe new Slack app process.
  sites/platform/src/integrations/notifications.md
  sites/upsun/src/integrations/notifications.md
  themes/psh-docs/static/images/slack/slack-app-scopes.png
Labels: WIP, markdown/prose

#4042 Update billing alerts
  sites/upsun/src/administration/billing/monitor-billing.md
  sites/upsun/src/administration/organizations.md
  sites/upsun/src/administration/pricing.md
Labels: enhancement, markdown/prose, Upsun

#4052 Bump mysql2 from 3.9.7 to 3.9.8 Upsun side
  sites/upsun/package-lock.json
  sites/upsun/package.json
Labels: markdown/prose

#4041 Update "Deploy Ibexa DXP on Platform.sh"
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/guides/ibexa/deploy.md
Labels: build-fork, markdown/prose

#4058 Update _index.md
  sites/platform/src/languages/php/_index.md
Labels: enhancement, build-fork, markdown/prose

#4056 Add Upsun reference to Delete your account procedure
  sites/platform/src/learn/overview/get-support.md
Labels: quick task, markdown/prose

#4062 Updates logic for search input element ID
  sites/platform/static/scripts/xss/src/containers/Search.js
  sites/upsun/static/scripts/xss/src/containers/Search.js
Labels: markdown/prose

#4065 Clarify potential override of authentication method
  sites/platform/src/environments/http-access-control.md
  sites/upsun/src/environments/http-access-control.md
Labels: enhancement, markdown/prose, Platform.sh, Upsun

#4064 Cookies
  sites/platform/src/define-routes/cache.md
  sites/upsun/src/define-routes/cache.md
Labels: enhancement, Platform.sh, Upsun

#4066 Fix broken links in YAML section
  sites/platform/src/learn/overview/yaml/yaml-structure.md
  sites/upsun/src/learn/overview/yaml/yaml-structure.md
Labels: quick task, markdown/prose, Platform.sh, Upsun

#4072 add clickhouse and gotenberg
  sites/upsun/src/manage-resources/adjust-resources.md
Labels: enhancement, build-fork, markdown/prose

#4076 Replacing YOUR_ID_HERE text for both commands with the appropriate YOUR_TOKEN_HERE text for the FASTLY_KEY variable
  sites/platform/src/guides/ibexa/fastly.md
Labels: build-fork, markdown/prose

#4082 Update vertical scaling and backup restoration
  sites/upsun/src/manage-resources/adjust-resources.md
  sites/upsun/src/manage-resources/resource-init.md
Labels: enhancement, markdown/prose, Upsun

#4083 Revert "Update vertical scaling and backup restoration"
  sites/upsun/src/manage-resources/adjust-resources.md
  sites/upsun/src/manage-resources/resource-init.md
Labels: markdown/prose

#4079 Document how to subscribe to add-ons
  sites/upsun/src/administration/billing/add-on-subscription.md
  sites/upsun/src/administration/users.md
  sites/upsun/src/increase-observability/application-metrics/cont-prof.md
  sites/upsun/src/increase-observability/application-metrics/go.md
  sites/upsun/src/increase-observability/application-metrics/nodejs.md
  sites/upsun/src/increase-observability/application-metrics/php.md
  sites/upsun/src/increase-observability/application-metrics/python.md
  themes/psh-docs/layouts/partials/continuous-profiling-sellable/body.md
Labels: enhancement, markdown/prose

#4075 Add sourceguardian to list of extensions for PHP 8.3
  shared/data/php_extensions.yaml
Labels: quick task, markdown/prose

#4077 Update README.md
  README.md
Labels: quick task, markdown/prose
