Repository platformsh/platformsh-docs, pull requests merged in 2024-02, with the labels that each got.

#3690 Chore/prepare for migration pt1
  .github/workflows/build-from-fork.yaml
  .github/workflows/get-pr-info.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#3711 Add CLI commands to Teams doc
  sites/friday/src/administration/teams.md
  sites/platform/src/administration/teams.md
  themes/psh-docs/layouts/partials/user-mgt-sellable/body.md
Labels: enhancement, markdown/prose

#3717 Document Bun for Nodejs 20+
  sites/platform/src/languages/nodejs/_index.md
  themes/psh-docs/layouts/partials/bun/body.md
Labels: enhancement, markdown/prose

#3719 Strapi guide: remove the need to customize .environment file
  sites/friday/src/get-started/strapi/_index.md
Labels: markdown/prose

#3718 Update PHP extensions for DG2
  shared/data/php_extensions.yaml
  sites/platform/src/languages/php/extensions.md
Labels: enhancement, markdown/prose

#3630 :memo: Precise New Relic configuration for PHP
  sites/platform/src/increase-observability/integrate-observability/new-relic/php.md
Labels: build-fork, markdown/prose

#3723 Revert "Document Clickhouse - Upsun"
  sites/friday/src/add-services/clickhouse.md
Labels: markdown/prose

#3725 Remove shortcode in links
  sites/platform/src/development/file-transfer.md
Labels: quick task, markdown/prose

#3709 Create a page on project isolation
  sites/friday/config/_default/config.yaml
  sites/friday/src/security/project-isolation.md
  sites/platform/src/development/file-transfer.md
  sites/platform/src/security/project-isolation.md
Labels: enhancement, markdown/prose

#3728 Update PHP 5 extension list
  shared/data/php_extensions.yaml
Labels: enhancement, markdown/prose

#3731 Rework content to prevent Vale errors
  sites/platform/src/increase-observability/integrate-observability/new-relic/php.md
Labels: quick task, markdown/prose

#3730 Update accept.txt
  contributing/styles/Vocab/Platform/accept.txt
Labels: quick task, markdown/prose

#3732 Update accept.txt
  contributing/styles/Vocab/Platform/accept.txt
Labels: quick task, markdown/prose

#3726 Add resource update activity type
  sites/friday/config/_default/config.yaml
  sites/friday/src/integrations/activity/reference.md
Labels: quick task

#3734 Upsun migrate security
  sites/friday/config/_default/config.yaml
  sites/friday/src/security/_index.md
  sites/friday/src/security/backups.md
  sites/friday/src/security/data-retention.md
  sites/platform/src/security/backups.md
  sites/platform/src/security/data-retention.md
Labels: markdown/prose

#3736 Fix issues in the activity script documentation
  sites/platform/src/integrations/activity/_index.md
Labels: markdown/prose

#3741 Add Golang 1.22 support
  shared/data/registry.json
Labels: quick task, markdown/prose

#3739 Vendor: projects
  sites/friday/config/_default/config.yaml
  sites/friday/src/projects/_index.md
  sites/friday/src/projects/change-project-timezone.md
  sites/friday/src/projects/delete-project.md
  sites/friday/src/projects/region-migration.md
Labels: markdown/prose

#3733 generating P.sh CLI command doc page
  .github/actions/set-up-upsun-cli/action.yaml
  .github/workflows/generate-cli-commands-page.yaml
  shared/pages/commands.md
  shared/scripts/gen-cli-docs.sh
  sites/friday/config/_default/config.yaml
  sites/friday/src/administration/cli/reference.md
  sites/platform/src/administration/cli/reference.md
Labels: markdown/prose

#3745 adding schedule for the CLI command generator to every day at 00:15
  .github/workflows/generate-cli-commands-page.yaml
Labels: markdown/prose

#3750 Fix cli workflow schedul
  shared/scripts/gen-cli-docs.sh
Labels: markdown/prose

#3751 Direct users to Sales instead of Support to enable log forwarding
  sites/platform/src/increase-observability/logs/forward-logs.md
Labels: quick task, markdown/prose

#3752 adding vale off/on
  shared/scripts/gen-cli-docs.sh
Labels: markdown/prose

#3753 Update Upsun Beta CTA
  sites/friday/config/_default/params.yaml
  sites/platform/config/_default/params.yaml
Labels: markdown/prose

#3735 Add warning about maxmemory to Redis page
  sites/platform/src/add-services/redis.md
Labels: enhancement, markdown/prose

#3754 Fix Vale errors on CLI generated pages.
  .github/workflows/linting.yaml
  contributing/styles/config/vocabularies/Platform/accept.txt
  contributing/styles/config/vocabularies/Platform/reject.txt
  shared/scripts/gen-cli-docs.sh
  sites/friday/src/administration/cli/reference.md
  sites/platform/src/administration/cli/reference.md
Labels: markdown/prose

#3681 Git 25 resources
  sites/friday/src/manage-resources/resource-init.md
Labels: enhancement, markdown/prose

#3696 Update docs on mounts
  sites/friday/src/add-services/network-storage.md
  sites/platform/src/create-apps/app-reference.md
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
Labels: enhancement, markdown/prose

#3759 Update deploy hook description
  sites/platform/src/create-apps/hooks/hooks-comparison.md
Labels: markdown/prose

#3758 Update tcp defaults and table
  sites/platform/src/create-apps/app-reference.md
Labels: markdown/prose

#3763 Add instance mounts and temporary alias
  sites/friday/src/create-apps/workers.md
  sites/platform/src/create-apps/app-reference.md
Labels: enhancement, markdown/prose

#3764 Revert "missing P.sh guide on Upsun side"
  sites/friday/config/_default/config.yaml
Labels: markdown/prose

#3765 Fix config-desc
  themes/psh-docs/layouts/shortcodes/guides/config-desc.md
Labels: markdown/prose

#3766 Wrong file follow-up
  themes/psh-docs/layouts/shortcodes/guides/config-desc.md
Labels: markdown/prose

#3777 Remove capital letters for resource init strategies via push options
  sites/friday/src/environments/_index.md
Labels: quick task, markdown/prose

#3780 New docs issue template
  .github/ISSUE_TEMPLATE/new_feature.yml
Labels: markdown/prose

#3785 Update Upsun docs GTM key
  sites/friday/config/_default/params.yaml
Labels: quick task, markdown/prose

#3767 Vendor: separate observability
  sites/friday/config/_default/config.yaml
  sites/friday/src/increase-observability/_index.md
  sites/friday/src/increase-observability/logs/_index.md
  sites/friday/src/increase-observability/logs/access-logs.md
  sites/friday/src/increase-observability/logs/forward-logs.md
  sites/friday/src/increase-observability/metrics/_index.md
Labels: markdown/prose

#3768 Vendor: separate feedback.
  sites/friday/config/_default/config.yaml
  sites/friday/src/feedback/_index.md
  sites/friday/src/feedback/report.html
Labels: markdown/prose

#3769 Vendor: separate changelog
  sites/friday/config/_default/config.yaml
  sites/friday/src/changelog/_index.md
Labels: markdown/prose

#3788 Revert instance mounts and temporary alias doc
  sites/friday/src/create-apps/app-reference.md
  sites/friday/src/create-apps/workers.md
Labels: quick task, markdown/prose

#3791 Add Solr 9.4 to registry.json
  shared/data/registry.json
Labels: quick task, markdown/prose

#3793 [CLI-BOT] Update on doc pages for CLI commands
  sites/friday/src/administration/cli/reference.md
  sites/platform/src/administration/cli/reference.md
Labels: markdown/prose, report, automated pr

#3798 Adds Kafka 3.6 support
  shared/data/registry.json
Labels: markdown/prose

#3747 Rework structure of Redirects page
  sites/platform/src/define-routes/redirects.md
Labels: enhancement, WIP, markdown/prose

#3794 Remove DG3 dedicated cluster staging
  sites/platform/src/dedicated-gen-3/_index.md
Labels: markdown/prose

#3789 Update understand-metrics.md
  sites/friday/src/increase-observability/metrics/understand-metrics.md
Labels: markdown/prose

#3799 Update screenshot in the Upsun metrics page
  sites/friday/src/increase-observability/metrics/understand-metrics.md
  sites/friday/static/images/observability/metrics/mysql-container.png
  sites/friday/static/images/observability/metrics/redis-container.png
  sites/friday/static/images/observability/metrics/service-container-minimized.png
Labels: markdown/prose

#3801 Revert "Document ClickHouse"
  sites/friday/src/add-services/clickhouse.md
Labels: markdown/prose

#3805 Add Rabbit MQ 3.13 to registry
  shared/data/registry.json
Labels: quick task, markdown/prose

#3804 Remove note from ES and MongoDB pages
  sites/friday/src/add-services/elasticsearch.md
  sites/friday/src/add-services/mongodb.md
Labels: quick task, markdown/prose

#3800 Clarify potential consequences of service type change
  sites/platform/src/add-services/mysql/_index.md
Labels: quick task, markdown/prose

#3811 Slightly tidier JQ on regions page
  sites/platform/src/development/regions.md
Labels: markdown/prose

#3815 Update IPs for US region
  shared/data/regions.yaml
Labels: quick task, markdown/prose
