Repository platformsh/platformsh-docs, pull requests merged in 2024-11, with the labels that each got.

#4232 Updates contracted redirects
  .platform/routes.yaml
Labels: markdown/prose

#4245 quotes workflow name since the name includes a comma
  .github/workflows/comment-on-pr.yaml
Labels: markdown/prose

#4235 Update links
  sites/upsun/src/get-started/here/configure/_index.md
Labels: markdown/prose

#4227 4225 emphasise that the composable image is a beta version on create apps page comprehensive example
  sites/platform/src/create-apps/_index.md
  sites/upsun/src/create-apps/_index.md
Labels: markdown/prose

#4141 Document configuring build resources on Upsun
  sites/upsun/src/manage-resources/build-resources.md
Labels: enhancement, markdown/prose, good-first-issue

#4210 Discord reference follow-up
  sites/platform/src/_index.md
Labels: markdown/prose, good-first-issue

#4217 Typo in python language page
  sites/upsun/src/languages/python/_index.md
Labels: build-fork, markdown/prose, good-first-issue

#4250 Update rust.md
  sites/upsun/src/languages/rust.md
Labels: build-fork, markdown/prose

#4259 feat: Updated build deploy docs
  sites/platform/src/learn/overview/build-deploy.md
  sites/upsun/src/learn/overview/build-deploy.md
Labels: markdown/prose

#4261 feat: removed 'prevent service information'
  sites/platform/src/learn/overview/build-deploy.md
  sites/upsun/src/learn/overview/build-deploy.md
Labels: markdown/prose

#4263 Apply 4177 diff to new branch to get around token perms
  .github/workflows/pr-check-links.yaml
  .platform/applications.yaml
  CONTRIBUTING.md
  build_local.sh
  sites/platform/package-lock.json
  sites/platform/package.json
  sites/upsun/package-lock.json
  sites/upsun/package.json
  tests.sh
  themes/psh-docs/assets/css/main.css
  themes/psh-docs/assets/css/print/transparency-reports.css
  themes/psh-docs/assets/css/syntax-highlighting.css
  themes/psh-docs/assets/css/vendor.css
  themes/psh-docs/layouts/partials/head/css.html
  themes/psh-docs/postcss.config.js
  themes/psh-docs/tailwind.config.js
Labels: markdown/prose

#4265 Fix checks
  .github/pull_request_template.md
  contributing/styles/config/vocabularies/Platform/accept.txt
  contributing/styles/config/vocabularies/Platform/reject.txt
Labels: markdown/prose

#4267 Fix vale errors.
  contributing/styles/config/vocabularies/Platform/accept.txt
  sites/platform/src/dedicated-environments/dedicated-gen-2/overview.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/overview.md
Labels: markdown/prose

#4273 shorten title for SEO max chars
  sites/upsun/config/_default/config.yaml
Labels: markdown/prose

#4272 feat: added instance to define a mount table
  sites/upsun/.yaml
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#4270 :adhesive_bandage: corrections to dedicated infra docs
  sites/platform/src/dedicated-environments/dedicated-gen-2/development.md
  sites/platform/src/dedicated-environments/dedicated-gen-2/environment-differences.md
  sites/platform/src/dedicated-environments/dedicated-gen-2/overview.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/development.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/overview.md
  sites/platform/src/dedicated-environments/overview.md
  sites/platform/src/environments/scalability.md
Labels: build-fork, markdown/prose

#4269 feat: made suggested changes
  sites/platform/src/dedicated-environments/dedicated-gen-3/development.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/overview.md
  sites/platform/src/increase-observability/metrics/grid.md
Labels: markdown/prose

#4277 PHP 8.4 support
  shared/data/php_extensions.yaml
  shared/data/registry.json
  sites/platform/src/languages/php/extensions.md
Labels: markdown/prose, good-first-issue
