Repository platformsh/platformsh-docs, pull requests merged in 2024-08, with the labels that each got.

#4055 Document Git 27 changes
  sites/platform/src/add-services/_index.md
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/development/variables/use-variables.md
  sites/upsun/src/development/variables/use-variables.md
  themes/psh-docs/layouts/shortcodes/source-integration/source-of-truth.html
  themes/psh-docs/layouts/shortcodes/source-integration/sync-fetch-prune.md
Labels: enhancement, markdown/prose, Platform.sh, Upsun, ready-for-staging, on-deck

#4084 Update vertical scaling
  sites/upsun/src/environments/backup.md
  sites/upsun/src/environments/restore.md
  sites/upsun/src/manage-resources/adjust-resources.md
  sites/upsun/src/manage-resources/resource-init.md
Labels: enhancement, generalization, markdown/prose, on-deck

#4127 Fix the tab info in settings for "Pause environment"
  sites/upsun/src/environments/_index.md
Labels: markdown/prose, on-deck

#4132 Include force push permissions for environment type level
  sites/upsun/src/administration/users.md
Labels: markdown/prose, on-deck

#4135 Cache-control header suggestion for location rules
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/platform/src/create-apps/web/static.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/create-apps/web/static.md
Labels: build-fork, markdown/prose, on-deck

#4138 Fix malformed shell script example in set-variables.md
  sites/platform/src/development/variables/set-variables.md
  sites/upsun/src/development/variables/set-variables.md
Labels: markdown/prose, on-deck

#4139 Add the --no-resources option to avoid restoring resources from the backup
  sites/upsun/src/manage-resources/resource-init.md
Labels: build-fork, markdown/prose

#4140 [New image] MariaDB 11.4
  shared/data/registry.json
Labels: markdown/prose

#4146 New support ticket link in console
  sites/platform/src/learn/overview/get-support.md
  sites/upsun/src/learn/overview/get-support.md
Labels: markdown/prose

#4144 Update crons.md
  sites/upsun/src/get-started/stacks/laravel/crons.md
Labels: build-fork, markdown/prose

#4157 mongodb: 4.2 is deprecated since 30 Apr 2023
  shared/data/registry.json
Labels: build-fork, markdown/prose, on-deck

#4156 change PR template to let external users to know that they need to update
  .github/pull_request_template.md
Labels: markdown/prose, on-deck

#4151 php83: add event and remove tideways extensions
  shared/data/php_extensions.yaml
Labels: build-fork, markdown/prose, on-deck

#4153 Update Hide from search engines for prod env with a custom domain
  sites/platform/src/environments/search-engine-visibility.md
  sites/upsun/src/environments/search-engine-visibility.md
Labels: build-fork, markdown/prose, on-deck

#4148 Mention unstable Common Name (CN) in TLS certs
  sites/platform/src/define-routes/https.md
  sites/upsun/src/define-routes/https.md
Labels: build-fork, markdown/prose, on-deck

#4158 Add MariaDB 10.11 to DG2 supported
  shared/data/registry.json
Labels: markdown/prose

#4160 Adds support for data output for devcenter search
  sites/platform/config/_default/config.yaml
  sites/upsun/config/_default/config.yaml
  themes/psh-docs/layouts/_default/list.devcenter.json
  themes/psh-docs/layouts/partials/utils/excludeSearch.html
  themes/psh-docs/layouts/partials/utils/fragments.html
Labels: markdown/prose

#4165 Update references to trial length
  sites/upsun/src/glossary/_index.md
Labels: build-fork, markdown/prose

#4166 Feature/first project incentive changes
  sites/upsun/config/_default/params.yaml
  sites/upsun/src/glossary/_index.md
  themes/psh-docs/layouts/partials/page-content.html
Labels: build-fork, markdown/prose
