Repository platformsh/platformsh-docs, pull requests merged in 2024-01, with the labels that each got.

#3669 Add Ruby 3.3 support
  shared/data/registry.json
Labels: markdown/prose

#3671 Update CLI installation information
  sites/platform/src/administration/cli/_index.md
Labels: build-fork, markdown/prose

#3667 Add interbase and event to php8.2
  shared/data/php_extensions.yaml
Labels: markdown/prose

#3673 missing mariadb yaml level in relationships snippet
  sites/platform/src/create-apps/app-reference.md
Labels: markdown/prose

#3680 pins vale version to 2.30.0 in reviewdog prose workflow
  .github/workflows/linting.yaml
Labels: markdown/prose

#3664 Revert "Document simplified relationships (#3590)"
  shared/data/registry.json
  sites/friday/.yaml
  sites/friday/src/create-apps/workers.md
  sites/friday/src/get-started/express/add-database.md
  sites/friday/src/get-started/laravel/deploy/configure.md
  sites/friday/src/get-started/symfony/environment-variables.md
  sites/platform/src/add-services/_index.md
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/headless-chrome.md
  sites/platform/src/add-services/influxdb.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/mysql/mysql-replication.md
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/add-services/varnish.md
  sites/platform/src/create-apps/_index.md
  sites/platform/src/create-apps/app-reference.md
  sites/platform/src/create-apps/hooks/_index.md
  sites/platform/src/create-apps/multi-app/project-structure.md
  sites/platform/src/create-apps/multi-app/relationships.md
  sites/platform/src/create-apps/upgrading.md
  sites/platform/src/create-apps/workers.md
  sites/platform/src/guides/drupal/redis.md
  sites/platform/src/languages/elixir.md
  sites/platform/src/languages/java/migration.md
  sites/platform/src/languages/lisp.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/learn/bestpractices/oneormany.md
  sites/platform/src/learn/tutorials/restrict-service-access.md
  themes/psh-docs/layouts/partials/examples/relationship.html
  themes/psh-docs/layouts/partials/examples/servicedefn.html
  themes/psh-docs/layouts/partials/snippet.html
  themes/psh-docs/layouts/shortcodes/endpoint-description.md
  themes/psh-docs/layouts/shortcodes/v2connect2app.md
Labels: build-fork, markdown/prose

#3684 removes hard-coded instances of the project id, option 2
  .github/workflows/build-from-fork.yaml
  .github/workflows/get-pr-info.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#3686 specifies branch to use for github action
  .github/workflows/build-from-fork.yaml
  .github/workflows/get-pr-info.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#3687 updates which secret is being used.
  .github/workflows/build-from-fork.yaml
  .github/workflows/get-pr-info.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#3688 Update Upsun Beta access information
  sites/friday/config/_default/params.yaml
  sites/platform/config/_default/params.yaml
Labels: enhancement, markdown/prose

#3691 Update NS service name in registry
  shared/data/registry.json
Labels: markdown/prose

#3694 updates GTMID for upsun to the new container ID for it
  sites/friday/config/_default/params.yaml
Labels: markdown/prose

#3695 Add link to the Django blog post in the Django get started guide
  sites/friday/src/get-started/django/_index.md
Labels: markdown/prose

#3689 Vendorization fixes
  sites/friday/src/create-apps/workers.md
  sites/friday/src/get-started/flask/deploy/tldr.md
  sites/friday/src/get-started/laravel/deploy/configure.md
  sites/platform/src/create-apps/workers.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/learn/tutorials/restrict-service-access.md
Labels: enhancement, markdown/prose

#3699 Improve consistency on support ticket mentions
  sites/platform/src/administration/organizations.md
  sites/platform/src/administration/pricing/_index.md
  sites/platform/src/administration/sso.md
  sites/platform/src/create-apps/troubleshoot-disks.md
  sites/platform/src/dedicated-gen-2/architecture/options.md
  sites/platform/src/dedicated-gen-2/overview/_index.md
  sites/platform/src/dedicated-gen-2/overview/backups.md
  sites/platform/src/dedicated-gen-2/overview/grid.md
  sites/platform/src/development/email.md
  sites/platform/src/development/ssh/_index.md
  sites/platform/src/development/ssh/troubleshoot-ssh.md
  sites/platform/src/development/troubleshoot.md
  sites/platform/src/domains/cdn/managed-fastly.md
  sites/platform/src/increase-observability/integrate-observability/new-relic/_index.md
  sites/platform/src/learn/overview/philosophy.md
  sites/platform/src/security/data-retention.md
  themes/psh-docs/layouts/shortcodes/onboarding-table.html
Labels: quick task, markdown/prose

#3702 [hotfix] adds drupal 10 to app.yaml
  .platform/applications.yaml
  shared/data/remote-examples/templates/app.yaml
Labels: bug, markdown/prose

#3701 Add ch-1 region to regions.yaml
  shared/data/regions.yaml
Labels: quick task, markdown/prose

#3634 Update SFTP info
  sites/platform/.yaml
  sites/platform/src/dedicated-gen-2/architecture/options.md
  sites/platform/src/dedicated-gen-3/options.md
  sites/platform/src/development/file-transfer.md
Labels: enhancement

#3707 Fix headings so links work as expected
  sites/platform/src/dedicated-gen-2/architecture/options.md
  sites/platform/src/dedicated-gen-3/options.md
Labels: enhancement, quick task, markdown/prose

#3708 Bug/search issues
  .platform/services.yaml
  search/main.py
Labels: markdown/prose

#3710 removes size property from search container
  search/.platform.app.yaml
Labels: markdown/prose

#3714 Fix redirect for Resources section
  .platform/routes.yaml
Labels: quick task, markdown/prose
