Repository platformsh/platformsh-docs, pull requests merged in 2025-06, with the labels that each got.

#4621 feat: added new sections
  sites/upsun/.yaml
  sites/upsun/src/administration/billing/add-on-subscription.md
  sites/upsun/src/learn/overview/get-support.md
Labels: markdown/prose

#4641 Json version of outbound ips
  .platform/applications.yaml
Labels: markdown/prose

#4647 Sigh more dependency updates
  sites/platform/package-lock.json
  sites/platform/package.json
  sites/platform/static/scripts/xss/package.json
  sites/upsun/package-lock.json
Labels: markdown/prose

#4477 feat: revamped error section
  sites/upsun/src/development/troubleshoot.md
Labels: markdown/prose, newsletter

#4657 feat: added note about route limits
  sites/platform/src/define-routes/redirects.md
  sites/upsun/src/define-routes/redirects.md
Labels: markdown/prose

#4655 feat: added note about SSO for machine users
  sites/platform/src/administration/cli/api-tokens.md
Labels: markdown/prose

#4659 fixes broken link to fastly docs, closes #4634
  sites/platform/src/security/web-application-firewall/fastly-waf.md
Labels: markdown/prose

#4672 adds scheduled workflow for updating the regions locations source file
  .github/workflows/update-regions-locations.yaml
  linkcheckerrc
Labels: markdown/prose

#4673 Update Dedicated Gen 2 supported/deprecated versions for all relevant services
  shared/data/registry.json
Labels: build-fork, markdown/prose

#4676 corrects mongo shell utility name from 'mongo' to 'mongosh'.
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/administration/cli/reference.md
  sites/upsun/src/add-services/mongodb.md
  sites/upsun/src/administration/cli/reference.md
Labels: markdown/prose

#4679 Refinements on regions workflow
  .github/workflows/update-regions-locations.yaml
Labels: markdown/prose

#4666 4661 4662 broken links
  linkcheckerrc
  sites/platform/src/security/web-application-firewall/fastly-waf.md
Labels: markdown/prose

#4685 fixes regex for dzone.com in linkchecker config
  linkcheckerrc
Labels: markdown/prose

#4610 Wordpress multisite
  .platform/applications.yaml
  sites/upsun/src/get-started/stacks/wordpress/bedrock.md
  sites/upsun/src/get-started/stacks/wordpress/composer.md
  sites/upsun/src/get-started/stacks/wordpress/multisite.md
  sites/upsun/src/get-started/stacks/wordpress/vanilla.md
Labels: markdown/prose

#4707 refactor python parse.quote to make sure it encodes slashes
  .github/workflows/check-openapi-spec-update.yaml
Labels: markdown/prose

#4716 adds creating of api/styles in additon to api in psh docs
  .platform/applications.yaml
Labels: markdown/prose

#4723 Dependabot roll-up
  .github/actions/redirection-verification/package-lock.json
  .github/actions/redirection-verification/package.json
  package-lock.json
  search/poetry.lock
  sites/platform/package-lock.json
  sites/platform/static/scripts/xss/package.json
Labels: markdown/prose

#4725 Update preview environment definition in glossary
  sites/platform/src/glossary/_index.md
  sites/upsun/src/glossary/_index.md
Labels: markdown/prose

#4726 Add paused as a environment status
  sites/platform/src/environments/_index.md
  sites/upsun/src/environments/_index.md
Labels: markdown/prose
