Repository platformsh/platformsh-docs, pull requests merged in 2025-01, with the labels that each got.

#4317 docs: add pdo_firebird from 8.2 to 8.4
  shared/data/php_extensions.yaml
Labels: build-fork, markdown/prose

#4329 updates link to Landofile
  themes/psh-docs/layouts/shortcodes/guides/lando.md
Labels: markdown/prose

#4318 golang: add note about automatic toolchain switching
  sites/platform/src/languages/go.md
  sites/upsun/src/languages/go.md
Labels: build-fork, markdown/prose

#4330 updates disk size from 256 --> 512 in kafka examples per ralt/etienne
  sites/platform/src/add-services/kafka.md
Labels: markdown/prose

#4334 feat: corrected region names in table
  sites/upsun/.yaml
  sites/upsun/src/development/regions.md
  themes/psh-docs/layouts/shortcodes/regions.html
Labels: markdown/prose

#4321 corrects jq syntax for displaying carbon intensity of regions
  sites/platform/src/development/regions.md
  sites/upsun/src/development/regions.md
Labels: markdown/prose

#4303 Upsun - remove git init from strapi guide
  sites/upsun/src/get-started/stacks/strapi/_index.md
Labels: markdown/prose

#4300 fix: wrong example on `prefix`
  sites/platform/src/define-routes/redirects.md
Labels: build-fork, markdown/prose

#4319 ALLOWED_HOSTS instructions incorrect
  sites/upsun/src/get-started/stacks/django.md
Labels: build-fork, markdown/prose

#4301 make the apex domain error more visually important
  sites/platform/src/domains/steps/subdomains.md
Labels: build-fork, markdown/prose

#4326 Update redis.md
  sites/upsun/src/add-services/redis.md
Labels: build-fork, markdown/prose

#4333 MFA term consistency
  sites/platform/src/administration/security/mfa.md
  sites/upsun/src/administration/mfa.md
Labels: markdown/prose

#4336 Remove project.domain.* activity references
  sites/platform/src/integrations/activity/reference.md
  sites/upsun/src/integrations/activity/reference.md
Labels: build-fork, markdown/prose

#4337 Fix sidebar behavior - top-level bundles.
  themes/psh-docs/layouts/partials/header/gtm_script.html
  themes/psh-docs/layouts/partials/sidebar/list.html
Labels: markdown/prose

#4338 Llms preformatting
  sites/upsun/ABOUT.md
  sites/upsun/layouts/shortcodes/community-buttons.html
  sites/upsun/layouts/shortcodes/home.html
  sites/upsun/src/add-services/rabbitmq.md
  sites/upsun/src/administration/organizations.md
  sites/upsun/src/get-started/here/configure/nodejs.md
  sites/upsun/src/get-started/here/configure/php.md
  sites/upsun/src/get-started/here/configure/python.md
  themes/psh-docs/assets/css/main.css
  themes/psh-docs/layouts/partials/codetabs/tabs.html
  themes/psh-docs/layouts/partials/note.html
  themes/psh-docs/layouts/shortcodes/codetabs.html
  themes/psh-docs/layouts/shortcodes/note.md
Labels: markdown/prose

#4255 Generation of the llms.txt for AI usage
  sites/upsun/ABOUT.md
  sites/upsun/config/_default/config.yaml
  themes/psh-docs/layouts/_default/home.llms-full.txt
  themes/psh-docs/layouts/_default/home.llms.txt
  themes/psh-docs/layouts/partials/llms/list.html
  themes/psh-docs/layouts/partials/llms/section.html
Labels: enhancement, markdown/prose

#4339 adjusts resources to allocate more ram to search
  search/.platform.app.yaml
Labels: markdown/prose

#4340 Adds guides for WordPress Vanilla and WordPress Bedrock
  sites/upsun/src/get-started/stacks/wordpress/_index.md
  sites/upsun/src/get-started/stacks/wordpress/bedrock.md
  sites/upsun/src/get-started/stacks/wordpress/composer.md
  sites/upsun/src/get-started/stacks/wordpress/vanilla.md
Labels: markdown/prose

#4350 feat: added rabbit 4.0 to dedicated docs
  sites/platform/src/dedicated-environments/dedicated-gen-3/overview.md
Labels: markdown/prose

#4358 adds missing gotenberg service to container profiles reference
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
Labels: markdown/prose
