Repository platformsh/platformsh-docs, pull requests merged in 2025-07, with the labels that each got.

#4735 Load pendo conditionally based on user id availability
  themes/psh-docs/layouts/_default/baseof.html
Labels: build-fork, markdown/prose

#4729 feat: updated dunning process
  sites/platform/src/administration/pricing/_index.md
  sites/upsun/src/administration/pricing.md
Labels: WIP

#4744 Composable image topic: Fix link markdown
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#4455 Remove the lisp image and references to it
  shared/data/registry.json
  sites/platform/.yaml
  sites/platform/config/_default/params.yaml
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/platform/src/development/templates.md
  sites/platform/src/languages/lisp.md
  sites/platform/static/files/fetch/appyaml/magento2ce
  sites/upsun/.yaml
  sites/upsun/config/_default/params.yaml
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/languages/lisp.md
  sites/upsun/src/manage-resources/adjust-resources.md
  sites/upsun/src/manage-resources/resource-init.md
Labels: build-fork, markdown/prose

#4719 feat: removed DG3 mentions
  sites/platform/src/add-services/elasticsearch.md
  sites/platform/src/add-services/headless-chrome.md
  sites/platform/src/add-services/influxdb.md
  sites/platform/src/add-services/kafka.md
  sites/platform/src/add-services/memcached.md
  sites/platform/src/add-services/mongodb.md
  sites/platform/src/add-services/mysql/_index.md
  sites/platform/src/add-services/network-storage.md
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/add-services/postgresql.md
  sites/platform/src/add-services/rabbitmq.md
  sites/platform/src/add-services/redis.md
  sites/platform/src/add-services/solr.md
  sites/platform/src/add-services/valkey.md
  sites/platform/src/add-services/varnish.md
  sites/platform/src/add-services/vault.md
  sites/platform/src/administration/pricing/_index.md
  sites/platform/src/dedicated-environments/backups-restores.md
  sites/platform/src/dedicated-environments/dedicated-gen-2/development.md
  sites/platform/src/dedicated-environments/dedicated-gen-2/environment-differences.md
  sites/platform/src/dedicated-environments/dedicated-gen-2/overview.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/_index.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/dedicated-generation-3.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/development.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/metrics.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/overview.md
  sites/platform/src/dedicated-environments/overview.md
  sites/platform/src/development/file-transfer.md
  sites/platform/src/development/variables/use-variables.md
  sites/platform/src/environments/backup.md
  sites/platform/src/glossary/_index.md
  sites/platform/src/increase-observability/metrics/_index.md
  sites/platform/src/languages/dotnet.md
  sites/platform/src/languages/elixir.md
  sites/platform/src/languages/go.md
  sites/platform/src/languages/java/_index.md
  sites/platform/src/languages/nodejs/_index.md
  sites/platform/src/languages/php/_index.md
  sites/platform/src/languages/ruby.md
  sites/platform/src/languages/rust.md
  sites/platform/src/learn/overview/structure.md
Labels: markdown/prose

#4383 Update region-migration.md
  sites/platform/src/projects/region-migration.md
Labels: build-fork, markdown/prose

#4384 Update adjust-resources.md
  sites/upsun/src/manage-resources/adjust-resources.md
Labels: markdown/prose

#4461 We should live in the current decade Always.
  sites/upsun/src/add-services/_index.md
  sites/upsun/src/administration/cli/reference.md
  sites/upsun/src/create-apps/hooks/hooks-comparison.md
  sites/upsun/src/create-apps/multi-app/project-structure.md
  sites/upsun/src/development/variables/_index.md
  sites/upsun/src/domains/troubleshoot.md
  sites/upsun/src/environments/restore.md
  sites/upsun/src/get-started/here/configure/_index.md
  sites/upsun/src/get-started/here/configure/nodejs.md
  sites/upsun/src/get-started/stacks/drupal.md
  sites/upsun/src/get-started/stacks/express/add-database.md
  sites/upsun/src/get-started/stacks/laravel/faq.md
  sites/upsun/src/get-started/stacks/magento.md
  sites/upsun/src/get-started/stacks/symfony/faq.md
  sites/upsun/src/get-started/stacks/wordpress/bedrock.md
  sites/upsun/src/get-started/stacks/wordpress/composer.md
  sites/upsun/src/get-started/stacks/wordpress/vanilla.md
  sites/upsun/src/integrations/activity/_index.md
  sites/upsun/src/integrations/activity/reference.md
  sites/upsun/src/integrations/overview.md
  sites/upsun/src/languages/python/_index.md
  sites/upsun/src/languages/python/dependencies.md
  sites/upsun/src/learn/tutorials/restrict-service-access.md
Labels: build-fork, markdown/prose

#4755 feat: updated content style guide
  contributing/content-style.md
Labels: markdown/prose

#4757 feat: added tag back in
  sites/platform/src/create-apps/_index.md
  sites/platform/src/create-apps/app-reference/_index.md
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/_index.md
  sites/upsun/src/create-apps/app-reference/_index.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#4766 Set DG3 files to list: local
  sites/platform/src/dedicated-environments/dedicated-gen-3/development.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/metrics.md
  sites/platform/src/dedicated-environments/dedicated-gen-3/overview.md
Labels: markdown/prose

#4768 Updated OpenSearch Latest Version
  shared/data/registry.json
  sites/platform/src/add-services/opensearch.md
  sites/upsun/src/add-services/opensearch.md
Labels: markdown/prose

#4741 feat: Adjusted composable image page
  sites/platform/src/create-apps/_index.md
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/_index.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#4799 Remove java on dependencies block is not supported
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
Labels: build-fork, markdown/prose

#4781 feat: removed all mentions of standard
  sites/upsun/src/administration/billing/add-on-subscription.md
  sites/upsun/src/administration/mfa.md
  sites/upsun/src/administration/users.md
  themes/psh-docs/layouts/partials/user-mgt-sellable/body.md
Labels: markdown/prose

#4800 Add MariaDB 11.8 to the supported list.
  shared/data/registry.json
Labels: markdown/prose

#4759 feat: added imap for 8.4
  shared/data/php_extensions.yaml
Labels: do not merge, markdown/prose

#4785 Update the Mariadb/mysql upgrade path
  sites/platform/src/add-services/mysql/_index.md
  sites/upsun/src/add-services/mysql/_index.md
Labels: markdown/prose
