Repository platformsh/platformsh-docs, pull requests merged in 2025-02, with the labels that each got.

#4370 corrects workflow name that comment workflow is dependent on
  .github/workflows/comment-on-pr.yaml
Labels: markdown/prose

#4377 Updates get-pr-info workflow
  .github/actions/get-pr-info/action.yaml
Labels: markdown/prose

#4375 P.sh: missing disk parameter for redis-persistent service
  sites/platform/src/add-services/redis.md
  sites/platform/src/guides/drupal/redis.md
Labels: markdown/prose

#4378 adds example config files in statically since the dynamic retrieval was disabled in previous PR
  sites/platform/static/files/fetch/.gitignore
  sites/platform/static/files/fetch/appyaml/akeneo
  sites/platform/static/files/fetch/appyaml/drupal10
  sites/platform/static/files/fetch/appyaml/drupal7
  sites/platform/static/files/fetch/appyaml/drupal8
  sites/platform/static/files/fetch/appyaml/drupal8-multisite
  sites/platform/static/files/fetch/appyaml/drupal9
  sites/platform/static/files/fetch/appyaml/gatsby
  sites/platform/static/files/fetch/appyaml/golang
  sites/platform/static/files/fetch/appyaml/laravel
  sites/platform/static/files/fetch/appyaml/magento2ce
  sites/platform/static/files/fetch/appyaml/micronaut
  sites/platform/static/files/fetch/appyaml/nodejs
  sites/platform/static/files/fetch/appyaml/php
  sites/platform/static/files/fetch/appyaml/pip/django4
  sites/platform/static/files/fetch/appyaml/pipenv/django4
  sites/platform/static/files/fetch/appyaml/poetry/django4
  sites/platform/static/files/fetch/appyaml/pyramid
  sites/platform/static/files/fetch/appyaml/python3
  sites/platform/static/files/fetch/appyaml/quarkus
  sites/platform/static/files/fetch/appyaml/spring-boot-maven-mysql
  sites/platform/static/files/fetch/appyaml/spring-mvc-maven-mongodb
  sites/platform/static/files/fetch/appyaml/strapi4
  sites/platform/static/files/fetch/appyaml/symfony-base/platformsh-symfony-template
  sites/platform/static/files/fetch/appyaml/symfony-demo/platformsh-symfony-template
  sites/platform/static/files/fetch/appyaml/symfony-docker-compose/platformsh-symfony-template
  sites/platform/static/files/fetch/appyaml/typo3
  sites/platform/static/files/fetch/appyaml/wordpress-composer
  sites/platform/static/files/fetch/appyaml/wordpress-vanilla
  sites/platform/static/files/fetch/multiappyaml/gatsby-drupal
  sites/platform/static/files/fetch/multiappyaml/gatsby-strapi
  sites/platform/static/files/fetch/multiappyaml/gatsby-wordpress
  sites/platform/static/files/fetch/routesyaml/django4
  sites/platform/static/files/fetch/routesyaml/drupal10
  sites/platform/static/files/fetch/routesyaml/drupal9
  sites/platform/static/files/fetch/routesyaml/gatsby
  sites/platform/static/files/fetch/routesyaml/gatsby-drupal
  sites/platform/static/files/fetch/routesyaml/gatsby-strapi
  sites/platform/static/files/fetch/routesyaml/gatsby-wordpress
  sites/platform/static/files/fetch/routesyaml/laravel
  sites/platform/static/files/fetch/routesyaml/micronaut
  sites/platform/static/files/fetch/routesyaml/php
  sites/platform/static/files/fetch/routesyaml/platformsh-symfony-template
  sites/platform/static/files/fetch/routesyaml/quarkus
  sites/platform/static/files/fetch/routesyaml/spring-mvc-maven-mongodb
  sites/platform/static/files/fetch/routesyaml/strapi4
  sites/platform/static/files/fetch/routesyaml/typo3
  sites/platform/static/files/fetch/routesyaml/wordpress-composer
  sites/platform/static/files/fetch/routesyaml/wordpress-vanilla
  sites/platform/static/files/fetch/servicesyaml/django4
  sites/platform/static/files/fetch/servicesyaml/drupal10
  sites/platform/static/files/fetch/servicesyaml/gatsby-drupal
  sites/platform/static/files/fetch/servicesyaml/gatsby-strapi
  sites/platform/static/files/fetch/servicesyaml/gatsby-wordpress
  sites/platform/static/files/fetch/servicesyaml/platformsh-symfony-template
  sites/platform/static/files/fetch/servicesyaml/typo3
  sites/platform/static/files/fetch/servicesyaml/wordpress-composer
  sites/platform/static/files/fetch/servicesyaml/wordpress-vanilla
Labels: markdown/prose

#4369 4368 add final grid metrics screenshot to metrics pages
  sites/platform/src/increase-observability/metrics/_index.md
  sites/platform/static/images/metrics/application-metrics.png
  sites/platform/static/images/metrics/grid-metrics-RAM.png
  sites/platform/static/images/metrics/mysql-metrics-1.png
  sites/platform/static/images/metrics/php-metrics.png
  sites/platform/static/images/metrics/redis-metrics.png
  sites/platform/static/images/metrics/understanding-metrics.png
  sites/platform/static/images/metrics/workers-metrics-1.png
  sites/upsun/src/increase-observability/metrics/understand-metrics.md
  sites/upsun/static/images/observability/metrics/application-metrics.png
  sites/upsun/static/images/observability/metrics/mysql-metrics-1.png
  sites/upsun/static/images/observability/metrics/php-metrics.png
  sites/upsun/static/images/observability/metrics/redis-metrics.png
  sites/upsun/static/images/observability/metrics/workers-metrics-1.png
  sites/upsun/static/images/observability/understanding-metrics.png
Labels: markdown/prose

#4382 initial commit of drupal doc for upsun
  sites/upsun/src/get-started/stacks/drupal.md
Labels: markdown/prose

#4390 refactors to account for large linkcheck reports
  .github/workflows/scheduled-check-links.yaml
Labels: markdown/prose

#4366 4364 custom headers example
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/platform/src/create-apps/web/custom-headers.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/create-apps/web/custom-headers.md
Labels: markdown/prose

#4371 adding HTML headers for llms.txt and llms-full.txt file
  themes/psh-docs/layouts/partials/head/head.html
  themes/psh-docs/layouts/partials/head/llms.html
  themes/psh-docs/layouts/partials/page-content.html
Labels: markdown/prose

#4396 4395 adjust markdown button location
  sites/upsun/src/get-started/stacks/_index.md
  themes/psh-docs/layouts/partials/editpagebutton.html
  themes/psh-docs/layouts/partials/page-content.html
  themes/psh-docs/layouts/partials/sidebar/nav.html
Labels: markdown/prose

#4400 4397 fix minor spacing issues
  sites/upsun/layouts/shortcodes/home.html
  themes/psh-docs/layouts/partials/header/actions.html
  themes/psh-docs/layouts/partials/page-content.html
Labels: markdown/prose

#4394 Document Java continous profiling support
  sites/upsun/src/increase-observability/application-metrics/java.md
Labels: markdown/prose

#4349 4341 users can now set locale related vars default charset default collation default ctype for postgresql
  sites/platform/src/add-services/postgresql.md
  sites/upsun/src/add-services/postgresql.md
Labels: markdown/prose

#4351 feat: updated environment types table
  sites/platform/src/administration/users.md
Labels: markdown/prose

#4380 feat: added a few paragraphs to style guide
  contributing/content-style.md
Labels: markdown/prose

#4426 Updates 4421 4420 4406 4401 4391
  .github/actions/redirection-verification/package-lock.json
  search/poetry.lock
  search/pyproject.toml
  sites/platform/package-lock.json
Labels: markdown/prose

#4429 elixir: add 1.18 to supported
  shared/data/registry.json
Labels: build-fork, markdown/prose

#4385 Update _index.md
  sites/upsun/src/add-services/mysql/_index.md
Labels: build-fork, markdown/prose

#4435 Fix a few lint errors
  sites/platform/src/_index.md
  sites/upsun/src/_index.md
Labels: markdown/prose

#4433 Bump Github action versions
  .github/workflows/build-from-fork.yaml
  .github/workflows/check-labels.yaml
  .github/workflows/linting.yaml
  .github/workflows/manage-environment.yaml
  .github/workflows/pr-check-links.yaml
  .github/workflows/scheduled-check-links.yaml
Labels: markdown/prose

#4359 Remove community post link for cloudflare mtls
  sites/platform/src/domains/cdn/cloudflare.md
  sites/upsun/src/domains/cdn/cloudflare.md
Labels: build-fork, markdown/prose

#4434 Automate image optimization
  .github/workflows/optimize-images.yaml
Labels: markdown/prose

#4415 feat: adjusted metrics pages
  cypress/e2e/search.cy.js
  sites/platform/src/increase-observability/metrics/dedicated-generation-3.md
  sites/platform/src/increase-observability/metrics/dedicated.md
  sites/platform/src/increase-observability/metrics/grid.md
  sites/platform/static/images/metrics/DG2-CPU.png
  sites/platform/static/images/metrics/DG2-RAM.png
  sites/platform/static/images/metrics/DG2-disks.png
  sites/platform/static/images/metrics/DG2-filter-metrics.png
  sites/platform/static/images/metrics/DG2-how-to-read-metrics.png
  sites/platform/static/images/metrics/DG2-multiple-clusters.png
  sites/platform/static/images/metrics/DG2-mysql-disk.png
  sites/platform/static/images/metrics/DG3-app-container.png
  sites/platform/static/images/metrics/DG3-filter-metrics.png
  sites/platform/static/images/metrics/DG3-postgresql.png
  sites/platform/static/images/metrics/DG3-redis.png
  sites/platform/static/images/metrics/DG3-worker-container.png
  sites/platform/static/images/metrics/grid-appcontainer.png
  sites/platform/static/images/metrics/grid-postgresql-full.png
  sites/platform/static/images/metrics/grid-postgresql-hidden.png
  sites/platform/static/images/metrics/grid-services.png
  sites/platform/static/images/metrics/grid-workers.png
Labels: do not merge, markdown/prose

#4440 Remove the feedback feature on both sites
  .platform/applications.yaml
  .platform/services.yaml
  sites/platform/index.js
  sites/platform/src/_index.md
  sites/platform/src/feedback/_index.md
  sites/platform/src/feedback/report.html
  sites/upsun/index.js
  sites/upsun/src/_index.md
  sites/upsun/src/feedback/_index.md
  sites/upsun/src/feedback/report.html
  themes/psh-docs/layouts/_default/feedback-report.html
  themes/psh-docs/layouts/partials/feedback/form.html
  themes/psh-docs/layouts/partials/feedback/sort-buttons.html
  themes/psh-docs/layouts/partials/page-content.html
Labels: enhancement, website, markdown/prose

#4439 Fix image optimization workflow
  .github/workflows/optimize-images.yaml
Labels: markdown/prose

#4442 :memo: Update mTLS docs with request option
  sites/platform/src/define-routes/https.md
  sites/upsun/src/define-routes/https.md
Labels: build-fork, markdown/prose

#4446 limits job to run only if PR workflow completed successfully
  .github/workflows/comment-on-pr.yaml
Labels: markdown/prose
