Repository platformsh/platformsh-docs, pull requests merged in 2025-08, with the labels that each got.

#4808 4806 4807 broken links
  linkcheckerrc
  sites/platform/src/add-services/mysql/_index.md
  sites/upsun/src/add-services/mysql/_index.md
  sites/upsun/src/add-services/opensearch.md
Labels: markdown/prose

#4815 Show an example of the error you get when having a version mismatch
  sites/platform/src/languages/ruby.md
  sites/upsun/src/languages/ruby.md
Labels: build-fork, markdown/prose

#4817 Cli reference issue
  .github/workflows/generate-cli-commands-page.yaml
Labels: markdown/prose

#4834 feat: update drupal landing page
  sites/platform/src/guides/drupal/multi-site.md
Labels: markdown/prose

#4836 Add documentation for the new `rotate_passwords` mysql option.
  sites/platform/src/add-services/mysql/_index.md
  sites/upsun/src/add-services/mysql/_index.md
Labels: markdown/prose

#4687 feat: added emissions dashboard section
  sites/platform/.yaml
  sites/platform/src/development/regions.md
  sites/upsun/.yaml
  sites/upsun/src/development/regions.md
Labels: WIP, do not merge, markdown/prose

#4849 [API-BOT] Update API Docs
  shared/pages/api.html
  shared/pages/openapispec-platformsh.json
  shared/pages/openapispec-platformsh.yaml
Labels: markdown/prose, report, automated pr

#4852 adds pagination support for retrieving rules from redirection.io's api
  .github/actions/redirection-verification/index.js
Labels: markdown/prose

#4853 updates redirection checker action to support markers
  .github/actions/redirection-verification/index.js
Labels: markdown/prose

#4868 [API-BOT] Update API Docs
  shared/pages/api.html
  shared/pages/openapispec-platformsh.json
  shared/pages/openapispec-platformsh.yaml
Labels: markdown/prose, report, automated pr

#4869 Dependabot bundle aug
  package-lock.json
  sites/platform/package-lock.json
  sites/platform/package.json
Labels: markdown/prose

#4883 strapi: remove unnecessary bashism
  sites/upsun/src/get-started/stacks/strapi/add-database.md
Labels: markdown/prose

#4731 feat: added deployment modes section
  sites/platform/src/learn/overview/build-deploy.md
  sites/upsun/src/learn/overview/build-deploy.md
Labels: WIP, do not merge

#4887 adds cheerio as a dependency
  .github/actions/redirection-verification/index.js
  .github/actions/redirection-verification/package-lock.json
  .github/actions/redirection-verification/package.json
Labels: markdown/prose

#4892 adds retries and delays when trying to retrieve html content for frag…
  .github/actions/redirection-verification/index.js
Labels: markdown/prose

#4895 feat: added section about viewers
  sites/upsun/src/administration/users.md
Labels: markdown/prose

#4896 [API-BOT] Update API Docs
  shared/pages/api.html
  shared/pages/openapispec-platformsh.json
  shared/pages/openapispec-platformsh.yaml
Labels: markdown/prose, report, automated pr

#4897 Increase timeout for redirection api
  .github/actions/redirection-verification/index.js
  sites/upsun/static/images/upsun-api.svg
Labels: markdown/prose
