Repository platformsh/platformsh-docs, pull requests merged in 2025-04, with the labels that each got.

#4482 4480/4481 broken links
  sites/platform/src/add-services/opensearch.md
  sites/platform/src/create-apps/multi-app/routes.md
  sites/upsun/src/add-services/opensearch.md
  sites/upsun/src/create-apps/multi-app/routes.md
Labels: markdown/prose

#4485 feat: updated supported versions
  sites/upsun/src/add-services/clickhouse.md
Labels: markdown/prose

#4488 4487 note for historical change on regions page
  sites/platform/src/development/regions.md
  sites/upsun/src/add-services/clickhouse.md
  sites/upsun/src/development/regions.md
Labels: markdown/prose

#4490 Fix logo link to redirect on docs instead of the main site
  sites/upsun/config/_default/params.yaml
Labels: markdown/prose

#4492 docs: specify how to perform persistent migration from redis to valkey
  sites/platform/src/add-services/valkey.md
  sites/upsun/src/add-services/valkey.md
Labels: build-fork, markdown/prose

#4506 Workflow clean up
  .github/workflows/linting.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#4513 removes checkout, changes to using external action for CLI setup
  .github/workflows/build-from-fork.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#4517 workflow fixes
  .github/actions/get-pr-info/action.yaml
  .github/workflows/build-from-fork.yaml
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4520 moves us to the official upsun cli action now that it's public
  .github/actions/get-pr-info/action.yaml
  .github/actions/set-up-cli/action.yaml
  .github/actions/set-up-upsun-cli/action.yaml
  .github/workflows/build-from-fork.yaml
  .github/workflows/generate-cli-commands-page.yaml
  .github/workflows/manage-environment.yaml
Labels: markdown/prose

#4521 delay PR related activities until after build from fork workflow completes
  .github/workflows/build-from-fork.yaml
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4527 feat: added note about large file limits
  sites/platform/src/learn/bestpractices/clean-repository.md
  sites/upsun/src/learn/bestpractices/clean-repository.md
Labels: markdown/prose

#4526 feat: added payment FAQ page
  sites/platform/src/administration/payment-faq.md
  sites/upsun/.yaml
  sites/upsun/src/administration/billing/payment-faq.md
Labels: markdown/prose, newsletter

#4529 Workflow refactoring
  .github/workflows/build-from-fork.yaml
  .github/workflows/comment-on-pr.yaml
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4531 hotfix for always vs always()
  .github/workflows/build-from-fork.yaml
Labels: markdown/prose

#4532 actions platform was throwing weird parsing errors. it does not like …
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4533 have checkout fetch all
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4535 adds with property before inputs
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4537 adds a job to report check status back to the PR for the previous jobs
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4539 slight api change on checks creation workflow
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4541 i hear you like syntax so I put syntax inside syntax
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4546 Report check status from workflow
  .github/actions/report-status/action.yaml
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4548 One more set of workflow fixes
  .github/actions/report-status/action.yaml
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4550 Checkout base before continue
  .github/actions/get-pr-info/action.yaml
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4479 feat: added HTTP metrics page to platform
  sites/platform/src/increase-observability/metrics/http-metrics.md
Labels: do not merge, newsletter

#4554 corrects ONE tiny typo
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4557 trying to figure out why the workflow_run event is not triggering
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4559 adds run_id to download artifact to ensure we're getting the correct …
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4562 Update delete-project.md
  sites/upsun/src/projects/delete-project.md
Labels: markdown/prose

#4567 E2E reporting status update
  .github/workflows/pr-url-and-dependent.yaml
Labels: markdown/prose

#4568 streamlines comment workflow
  .github/workflows/comment-on-pr.yaml
  .github/workflows/pr-url-and-dependent.yaml
  CONTRIBUTING.md
Labels: markdown/prose

#4553 feat: updated registry with newest version
  shared/data/registry.json
Labels: markdown/prose

#4569 Fixes broken links to opensearch.org
  sites/platform/src/add-services/opensearch.md
  sites/upsun/src/add-services/opensearch.md
Labels: build-fork, markdown/prose

#4574 feat: adjusted top level keys
  sites/upsun/src/learn/overview/yaml/yaml-structure.md
Labels: markdown/prose

#4581 refactoring of build from fork steps
  .github/workflows/build-from-fork.yaml
Labels: markdown/prose

#4583 adds missing )
  .github/workflows/build-from-fork.yaml
Labels: markdown/prose

#4584 changes logic on how we check for active environments from forks
  .github/workflows/build-from-fork.yaml
Labels: markdown/prose
