Repository platformsh/platformsh-docs, pull requests merged in 2025-10, with the labels that each got.

#5017 Network Storage version updates
  shared/data/registry.json
Labels: markdown/prose

#5019 Rename cdn.eu.pendo.io to content.engage.upsun.com
  themes/psh-docs/layouts/_default/baseof.html
Labels: markdown/prose

#5015 Add journald info
  sites/platform/src/increase-observability/logs/forward-logs.md
  sites/upsun/src/increase-observability/logs/forward-logs.md
Labels: markdown/prose

#5023 Installing Fastly CDN
  sites/platform/src/integrations/fastly-cdn.md
  sites/upsun/src/integrations/fastly-cdn.md
Labels: markdown/prose

#5032 feat: New replica-admin permission
  sites/platform/src/add-services/mysql/_index.md
  sites/upsun/src/add-services/mysql/_index.md
Labels: markdown/prose

#5036 5034 5035 broken links link checker
  .github/actions/redirection-verification/index.js
  .github/workflows/scheduled-check-links.yaml
  sites/upsun/src/create-apps/web/custom-headers.md
  sites/upsun/src/get-started/stacks/drupal.md
Labels: markdown/prose

#4525 feat: added monitor traffic note
  sites/platform/src/administration/pricing/_index.md
  sites/platform/src/domains/cdn/managed-fastly.md
  sites/upsun/src/administration/billing/monitor-billing.md
Labels: do not merge, newsletter

#5005 Fix variable reference in deployment hook example
  sites/platform/src/guides/symfony/integration.md
Labels: build-fork, markdown/prose

#5042 adding composable image version in registry.json
  shared/data/registry.json
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/utils/updateExampleConfigFiles.js
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/utils/updateExampleConfigFiles.js
  themes/psh-docs/layouts/shortcodes/latest.html
Labels: markdown/prose

#5048 feat: adjusted note
  sites/upsun/src/administration/billing/monitor-billing.md
Labels: markdown/prose

#5052 📝 Update autoscaling docs for clarity on deployment process
  sites/upsun/src/manage-resources/autoscaling.md
Labels: build-fork, markdown/prose

#5057 Adding a note for web.commands.pre_start
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/platform/src/create-apps/app-reference/single-runtime-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/single-runtime-image.md
Labels: markdown/prose
