Repository platformsh/platformsh-docs, pull requests merged in 2025-09, with the labels that each got.

#4864 feat: removed mentions
  sites/platform/src/increase-observability/metrics/_index.md
Labels: markdown/prose

#4904 feat: moved AI section
  sites/upsun/src/get-started/AI/_index.md
  sites/upsun/src/get-started/AI/aiagent.md
  sites/upsun/src/get-started/AI/mcp.md
Labels: markdown/prose

#4906 feat: add Qdrant vector database configuration and documentation
  contributing/styles/config/vocabularies/Platform/accept.txt
  sites/upsun/src/add-services/qdrant.md
  sites/upsun/src/get-started/AI/_index.md
Labels: markdown/prose

#4912 Nix channels: add context
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#4914 [API-BOT] Update API Docs
  shared/pages/api.html
  shared/pages/openapispec-platformsh.json
  shared/pages/openapispec-platformsh.yaml
Labels: markdown/prose, report, automated pr

#4829 4828 update migration page
  sites/platform/src/learn/tutorials/migrating.md
  sites/platform/src/projects/region-migration.md
  sites/upsun/src/learn/tutorials/migrating/_index.md
  sites/upsun/src/learn/tutorials/migrating/from-psh.md
  sites/upsun/src/projects/region-migration.md
Labels: WIP, do not merge, markdown/prose

#4928 chore: add golang 1.25 to supported
  shared/data/registry.json
Labels: build-fork, markdown/prose

#4884 Autoscaling documentation
  sites/upsun/src/manage-resources/adjust-resources.md
  sites/upsun/src/manage-resources/autoscaling.md
  sites/upsun/static/images/autoscaling/Configure-autoscaling.png
  sites/upsun/static/images/autoscaling/autoscaling-console.png
  sites/upsun/static/images/autoscaling/configure-resources-1.png
Labels: WIP, do not merge, markdown/prose

#4931 feat: changed command
  sites/upsun/src/learn/tutorials/migrating/from-psh.md
  sites/upsun/src/projects/region-migration.md
Labels: markdown/prose

#4964 Fix symfony deploy command as it should be push now that deploy means…
  sites/platform/src/guides/symfony/faq.md
  sites/upsun/src/get-started/stacks/symfony/faq.md
Labels: markdown/prose

#4967 Branding - updates to repo README and contributing-related content
  CONTRIBUTING.md
  README.md
  contributing/content-style.md
  contributing/markup-format.md
  contributing/templates/concept.md
  contributing/templates/how-to.md
Labels: markdown/prose

#4981 4979 redirects
  shared/pages/api.html
  sites/platform/src/languages/java/frameworks.md
Labels: markdown/prose

#4997 Remove 24.05 from list of supported channels
  sites/platform/src/create-apps/app-reference/composable-image.md
  sites/upsun/src/create-apps/app-reference/composable-image.md
Labels: markdown/prose

#4960 ADV-2095 - Update resources init strategy for branch and activate
  sites/upsun/src/manage-resources/resource-init.md
Labels: build-fork, markdown/prose

#4959 Add `upsun init` documentation
  sites/upsun/src/administration/cli/init.md
Labels: markdown/prose

#4994 [CLI-BOT] Update on doc pages for CLI commands
  sites/platform/src/administration/cli/reference.md
  sites/upsun/src/administration/cli/reference.md
Labels: markdown/prose, report, automated pr

#5002 [API-BOT] Update API Docs
  shared/pages/api.html
  shared/pages/openapispec-upsun.json
  shared/pages/openapispec-upsun.yaml
Labels: markdown/prose, report, automated pr

#5008 AI Agents: Remove extra space to render url correctly
  sites/upsun/src/get-started/AI/aiagent.md
Labels: markdown/prose

#5011 feat: adjusted note in page
  sites/platform/src/learn/overview/build-deploy.md
  sites/upsun/src/learn/overview/build-deploy.md
Labels: markdown/prose
